### PR TITLE
fix($http): propagate status -1 for aborted requests

### LINKED ISSUE #4491: fix($http) Indicate whether a request was aborted via status.
Currently, there does not appear to be a way to determine whether a request was aborted or failed for another reason, as status is normalized to 0 in $http:

```
 /**
  * Resolves the raw $http promise.
  */
  function resolvePromise(response, status, headers) {
    // normalize internal statuses to 0
    status = Math.max(status, 0);

    (isSuccess(status) ? deferred.resolve : deferred.reject)({
      data: response,
      status: status,
      headers: headersGetter(headers),
      config: config
    });
  }
```

Internally a -1 is used to flag that the request either timed out or it was aborted via promise resolution.

What if we exposed the -1 as a valid status to give a better idea to rejection handlers why the request failed?

If this is the case I can create a PR to adress this issue.

### PR DESCRIPTION
**Pull request by pkozlowski-opensource**
Fixes #4491

### CODE REVIEW

**Comment by gabrielmaldi** [comment]
Can I help with something to make this PR move forward?

**Comment by petebacondarwin** [comment]
LGTM

**Comment by dizel3d** [comment]
Why this feature was introduced as patch for Angular 1.3.x? I think, it is a breaking change and should be introduced in Angular 1.4.x. because many developers use 0 instead of -1. [proof](http://stackoverflow.com/questions/23914893/angular-js-http-intercept-neterr-connection-refused/23915646#23915646).

**Comment by petebacondarwin** [comment]
@dizel3d - thanks for getting in touch. The status of an error was not defined as a public API in the Angular docs. The reason we used to (incorrectly) return 0 for all errors was that browsers were inconsistent in their error return values.
What we guarantee, which has not changed, is that successful requests would return a value between 200 and 299, inclusive.
To tell if a request errored, you should really be using an error handler via `then(successFn, errorFn)`. What this added was a way of telling if the error was because of a timeout.
If you must use the status to check for an error, then perhaps you should test for `<=0` rather than `==0`.

**Pull request closed without merging**
