### PR TITLE
Issue with canceling XHR request using promises - fixed

### LINKED ISSUE #10890: $resource does not abort the requests through the promise
https://github.com/angular/angular.js/blob/master/src/ngResource/resource.js#L564

### PR DESCRIPTION
**Pull request by netman92**
Fixes #10890 and #9332.

### CODE REVIEW

**Comment by netman92** [comment]
Done

**Comment by yohanh** [comment]
This fix will be add in a next version ?

**Comment by antoine-richard** [comment]
Hi

We're also experiencing this problem(#9332). See this plunker: http://plnkr.co/edit/vk9HUd?p=preview . With angular 1.2.28, it work as expected (i.e. the pending request is cancelled. I use the throttling control feature in DevTools to easily observe this).

The PR proposed here works fine for us. What is the status on this?

Please let us know if we can help you in any way.

**Comment by jtheoof** [comment]
The patch looks good. It would be nice to get it merged in the next release. I checked the logs, I'm not sure why Travis CI is complaining.

**Comment by bborowin** [comment]
What's the timeline on reviewing / merging this? We're hitting this problem too; made a local workaround but it would be nice to have it baked in.

**Comment by reubenbrown** [comment]
+1 to @bborowin's comment running into this issue as well. How did you work around it?

**Comment by netman92** [comment]
Can somebody merge this?

**Comment by caitp** [comment]
Looks good to me. Make sure subsequent requests can be cancelled start the first one has been,i recall there was an issue with that before

**Comment by netman92** [comment]
@caitp Can you give me an example? I did not understand your answer.

**Comment by okiss** [comment]
Hi @caitp 
I created a jsbin example (From PR #12525 ) to show how this fix works. Please have a look at http://jsbin.com/hoxuhotupe/edit?html,js,console,output 

If multiple requests are running, resolving the promise will cancel them all (Try clicking the 'create button' multiple times quickly and then click the 'cancel request' button. See the console output).

After you cancel a request, you can create a new request and it will not be interrupted. (Click the 'create request' button, then click the 'cancel request' button. Click the 'create request' button again and wait a few seconds. See that the request completed successfully).

This is the same behavior as was present in 1.2.x. It would be very helpful if the regression was fixed.

**Comment by caitp** [comment]
this PR has gotten extremely hard to understand, I'm not entirely sure which comments apply to the pr/issue and which ones apply to the other commits. Do you think you could rebase this and force push just so it's easier to read?

**Comment by okiss** [comment]
@caitp see #12525 . It contains just the relevant commit

**Comment by caitp** [comment]
Okay, thanks for the verification @okiss. The diff has gotten really screwed up and the PR has been closed, so it can't really be reviewed or merged.

**Comment by jtheoof** [comment]
What about the #12525 ? It is more recent, is it messed up as well?

**Comment by caitp** [comment]
Probably, it's the matter branch, bad idea

**Comment by jtheoof** [comment]
@caitp Can you have a look at #12657. @netman92 has rebased properly.

**Pull request closed without merging**
