### PR TITLE
build(travis): gracefully shut down the sauce connect tunnel after th…

### PR DESCRIPTION
**Pull request by IgorMinar**
…e tests are done running

This is to prevent sauce connect tunnel leaks.

### CODE REVIEW

**Comment by IgorMinar** [comment]
@petebacondarwin I have a similar PR pending for angular/angular. Based on the logs it seems to work fine. we need to merge this in and see if it improves the situation.

**Comment by petebacondarwin** [comment]
LGTM

**Comment by IgorMinar** [comment]
I made one more change - we now poll and block travis until the process disappears.

**Comment by IgorMinar** [comment]
merged into all branches

**Comment by petebacondarwin** [comment]
Fingers crossed!

**Pull request closed without merging**
