### PR TITLE
docs(CONTRIBUTING): add warning about forced push

### PR DESCRIPTION
**Pull request by dmitriz**
Add warning about the possible consequences of a forced push

docs(CONTRIBUTING): add warning about forced push

Replacing https://github.com/angular/angular.js/pull/13719

### CODE REVIEW

**Comment by petebacondarwin** [comment]
Instead, I think we need to change the wording to be...

```
If we suggest changes then:

* Make the required updates.
* Re-run the Angular test suite to ensure tests are still passing.
* Commit your changes to the branch
* Push to your GitHub repository (this will update your Pull Request):

If the PR gets too outdated we may ask you to rebase and force push to update the PR:

git rebase master -i
git push origin my-fix-branch -f
```

**Comment by dmitriz** [comment]
So no warning?

What if a maintainer will ask to force push forgetting the consequences?

With an old PR especially this may lead to loss of people's work.

**Comment by gkalpak** [comment]
Without squashing, there shouldn't be any loss, right ?

**Comment by dmitriz** [comment]
squashing is part of `git rebase master -i`

**Comment by petebacondarwin** [comment]
OK, so you can add the warning as a line after what I wrote :-)

**Comment by petebacondarwin** [comment]
Thanks for the changes - they are nearly right. I will fix up and merge.

**Pull request closed without merging**
