### PR TITLE
Handle undefined provider method during module loading

### PR DESCRIPTION
**Pull request by robstove**
https://github.com/angular/angular.js/issues/13481#issuecomment-163435774

### CODE REVIEW

**Comment by robstove** [comment]
I signed it!

**Comment by Narretz** [comment]
Thanks for the PR. There a few things that need to be done before this can be merged:
- [ ]  use the minErr fn instead of Error
- [ ] add a test that shows that this case is caught
- [ ] add a docs error page for this error

Would be cool if you could work on this @robstove If you have questions, feel free to ask.

**Comment by robstove** [comment]
Add the error details however due to the location of this error I wasn't able to find a good way implement a valid test case.

**Comment by robstove** [comment]
Assuming this isn't going anywhere. Closing....

**Pull request closed without merging**
