### PR TITLE
Export buildUrl in the global angular namespace

### PR DESCRIPTION
**Pull request by gdamjan**
buildUrl could be used outside of $http too, for example if the user needs
to create urls for APIs that are not natively supported in angular (EventSource for ex.)

potentionally if it's not hidden in a closure inside $http,
it might be used in other parts of angular too

### CODE REVIEW

**Comment by thiswildorchid** [comment]
+1

**Comment by blowsie** [comment]
Is there a solution for this in angular 1.3 ? 

https://github.com/angular/angular.js/issues/7429

**Comment by parliament718** [comment]
I'm also waiting for this one, has it been included in latest angular yet?

**Comment by blowsie** [comment]
@parliament718 ;

As far as I know (from looking at the source etc), this is not in 1.3 but there may be a solution coming in 1.4, for now I am manually copying this changeset in to my copy of angular
https://github.com/angular/angular.js/commit/f64afc71f2329f3084918cd532b79b6fca077e21

**Comment by slavafomin** [comment]
:+1:

**Comment by blowsie** [comment]
Docs for 1.4 found here.
https://docs.angularjs.org/api/ng/service/$httpParamSerializer

**Pull request closed without merging**
