### PR TITLE
fix($sanitize): do not trigger CSP alert/report in Firefox and Chrome

### LINKED ISSUE #16463: ngSanitize triggers CSP alert/report in Firefox
**I'm submitting a ...**

- [X] bug report
- [ ] feature request
- [ ] other 

**Current behavior:**

If ngSanitize is added as a module dependency and a Content-Security-Policy is set that does not allow inline styles then Firefox shows the following message: 

> Content Security Policy: The page’s settings observed the loading of a resource at self (“default-src”). A CSP report is being sent.

Our CSP looks like this:
> Content-Security-Policy-Report-Only: default-src 'self'; report-uri /foo

If ngSanitize is removed from the module dependencies then the CSP message disappears as well.

**Expected / new behavior:**

ngSanitize should work in Firefox without triggering CSP alerts, at least if the "ng-csp" mode is enabled.

**Minimal reproduction of the problem with instructions:**

1. Set the Content-Security-Policy to: default-src: 'self'
2. Add 'ngSanitize' as a module dependency.

**AngularJS version:** 1.6.9

**Browser:** Firefox 60.0a1 and 59.0b10

**Anything else:**
I guess the following code triggers the CSP alert, since it adds an inline <style> tag.
`
// Check for the Firefox bug - which prevents the inner img JS from being sanitized
      inertBodyElement.innerHTML = '<svg><p><style>';
`
From: https://github.com/angular/angular.js/blob/master/src/ngSanitize/sanitize.js
Line 443-444

### PR DESCRIPTION
**Pull request by peruukki**
Default to using DOMParser if it is available and fall back to createHTMLDocument if needed. This is the approach suggested in the related pull request #17013 and used by DOMPurify too. It also safely avoids using an inline style tag that causes CSP violation errors if inline CSS is prohibited.

The related unit tests in `sanitizeSpec.js`, "should not allow JavaScript execution when creating inert document" and "should not allow JavaScript hidden in badly formed HTML to get through sanitization (Firefox bug)", are left untouched to assert that the behavior hasn't changed in those scenarios.

Fixes #16463.

# AngularJS is in LTS mode
We are no longer accepting changes that are not critical bug fixes into this project.
See https://blog.angular.io/stable-angularjs-and-long-term-support-7e077635ee9c for more detail.

**Does this PR fix a regression since 1.7.0, a security flaw, or a problem caused by a new browser version?**
This fixes a regression that came with commit 7673ca7d158fffdd8cd0e8ecb1f36901fb471c84 that based on its tags appeared in version 1.7.0. It's not clear to me if it's considered a security flaw but it does hinder setting a strict Content-Security-Policy that doesn't allow inline styles.

**What is the current behavior? (You can also link to an open issue here)**
If ngSanitize is added as a module dependency and the Content-Security-Policy does not allow inline styles, a CSP violation will be reported by at least Firefox and Chrome.

Issue #16463.

**What is the new behavior (if this is a feature change)?**
No CSP violation is reported.

**Does this PR introduce a breaking change?**
No.

**Please check if the PR fulfills these requirements**
- [X] The commit message follows our [guidelines](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits)
- [ ] Fix/Feature: [Docs](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#documentation) have been added/updated
- [X] Fix/Feature: ~Tests have been added~; existing tests pass

**Other information**:
Like mentioned above, there are existing unit tests related to this change that test that badly-formatted HTML is sanitized properly, and the behavior shouldn't have changed on that regard. I don't think there is a convenient way to test CSP violations, so I didn't write any new tests.

I submitted the same fix to Angular in https://github.com/angular/angular/pull/36578, it is still being processed.

### CODE REVIEW

**Comment by koto** [comment]
The change from `<style>` to `<span>` has security consequences. The original payload (similar to what DOMPurify used) was tailored to detect the bug in Firefox HTML parser used in `innerHTML`. The actual check done after payload processing is kind of wrong (the fact whether `img` is under `svg` is irrelevant, what is important is whether any element exists with an `onerror` attribute), but incidentally - the modified payload will hinder the check even if it was right. `style` is the symptom that triggers the FF box, as the parsing context is different - changing to `span` breaks that - AngularJS would not be testing for the right thing.

A proper patch would be to default to DOMParser without testing. DOMPurify stopped testing for the FF (and Safari) bugs long time ago, and is [defaulting to DOMParser](https://github.com/cure53/DOMPurify/commit/978ebd2ae95c85e8e1b4bd2be07f826139b6ab07) for other reasons now.

**Comment by peruukki** [comment]
Thanks for the info @koto, this fix did seem suspiciously simple for an issue that had been waiting for 2 years to be resolved. 😄 So if I understood correctly, we should try to use DOMParser (`getInertBodyElement_DOMParser`) and fall back to createHTMLDocument (`getInertBodyElement_InertDocument`) if DOMParser is not available, and drop `getInertBodyElement_XHR` altogether. I'll see if I can achieve that.

**Comment by peruukki** [comment]
I made the changes, now DOMParser is used in modern browsers and the fallback was used at least on my Internet Explorer 11 virtual machine. I don't think there is still any practical way to write a test for this change as the changes are internal.

**Comment by peruukki** [comment]
One detail I noticed: the Angular repository already has an [`isDOMParserAvailable` function](https://github.com/angular/angular/blob/master/packages/core/src/sanitization/inert_body.ts#L173-L179) that uses a simpler method for the detection, `!!(window as any).DOMParser`, whereas I actually test the DOMParser functionality using `!!getInertBodyElement_DOMParser('')`. I chose the latter because [the `parseFromString` method with HTML support seems to be less supported than just the `DOMParser` property](https://developer.mozilla.org/en-US/docs/Web/API/DOMParser#Browser_compatibility) but I don't know if it makes any real-life difference and which one would be preferable.

**Comment by koto** [comment]
It sounds like a good choice. Thanks!

**Comment by Splaktar** [comment]
The test failures just appear to be caused by connection flakiness with Saucelabs. Can someone on the @angular/angular-1-contributors team restart Travis?

**Review by Splaktar — APPROVED** [review]
LGTM. I'm thankful for the great input from @koto and to @peruukki for posting this PR and getting the discussion started.

**Comment by petebacondarwin** [comment]
@koto could you give this your approval if you feel it is a safe change to make?

**Comment by koto** [comment]
This looks good, thanks Harri!

**Comment by petebacondarwin** [comment]
Thanks @peruukki - I'm changed the commit message to refer to the thing it is fixing rather than the detail of the implementation. Closed via 2fab3d4e00f4fe35bfa3cf255160cb97404baf24

**Pull request closed without merging**
