### PR TITLE
Added missing closing square bracket

### PR DESCRIPTION
**Pull request by ghost**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Docs update

**What is the current behavior? (You can also link to an open issue here)**
basic example to define an update / PUT action is missing the closing array square brackets.

**What is the new behavior (if this is a feature change)?**
Added the missing "]"

**Does this PR introduce a breaking change?**
No

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [ ] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

**Other information**:

### CODE REVIEW

**Comment by EyalRonel** [comment]
I signed it!

**Comment by EyalRonel** [comment]
Is this pending merge?

**Comment by gkalpak** [comment]
It has been merged already.

**Comment by EyalRonel** [comment]
Thanks 👍

**Pull request closed without merging**
