### PR TITLE
fix($compile): handle boolean attributes in `@` bindings

### LINKED ISSUE #13767: input[checkbox] doesn't catch checked in scope directive
The attribute "checked" is not recovered in the scope of a directive.
This seems broken since version 1.4.4
https://plnkr.co/edit/0j7Y9mkeP4m2waCLYLxU?p=preview
Working on 1.3.15
https://plnkr.co/edit/GN4K5EdtfHxPpe7x3OCc?p=preview

### PR DESCRIPTION
**Pull request by petebacondarwin**
Closes #13767

### CODE REVIEW

**Comment by petebacondarwin** [comment]
To be backported to 1.4

**Comment by Narretz** [comment]
Looks good. However, can you add a comment that explains why we have to do that? I'm not convinced it's angular that is modifying these boolean attributes. Isn't it the browser that converts the content of boolean attributes to "true"?

**Comment by petebacondarwin** [comment]
Here is plunker that shows the problem is fixed by this PR: https://plnkr.co/edit/mk9BJODWJdYFhMpw3nGa?p=preview

**Comment by petebacondarwin** [comment]
@Narretz here is the line where the boolean conversion happens I believe: https://github.com/angular/angular.js/blob/master/src/ng/directive/attrs.js#L339

**Comment by Narretz** [comment]
You are right, thanks for the link. Can't hurt to put it in a little comment, though ;)

**Comment by petebacondarwin** [comment]
Will do!

**Pull request closed without merging**
