### PR TITLE
Fix ngMock window.inject() stack trace reporting on PhanthomJS for master branch

### PR DESCRIPTION
**Pull request by jurko-gospodnetic**
Fixes & adds a tests for issue #13591 for the angular `master` branch.

This does the same work as pull request #13592 does on the angular `1.4.x` branch.

### CODE REVIEW

**Comment by jurko-gospodnetic** [comment]
Could this get merged? It's a simple bug fix, amply commented and with relevant tests added.

**Comment by jurko-gospodnetic** [comment]
Could this pull request be merged? It's a simple bug-fix, well commented and with relevant tests added. Leaving it hanging here just makes it attract conflicts. :worried:

**Comment by gkalpak** [comment]
Cleaned it up a bit and merged. @jurko-gospodnetic, it would be great if you could make sure it works as expected on PhantomJS.

**Comment by jurko-gospodnetic** [comment]
@gkalpak hi & thanks for merging.

I ran the code through PhantomJS and it works as expected. I also ran angular's `ngMock` related `test:jqlite` test suite using PhantomJS and it passes and some custom added `console.log()` calls report not having stack information before throwing the error and having it after throwing & catching it, as expected.

There are some other parts that fail when you run the full angular test suite fails on PhantomJS, but I did not want to get into that at this time.

Btw. nice catch with throwing and catching not constructing a different error instance but updating the `stack` in the original error object.

**Comment by gkalpak** [comment]
Thx for getting back !

> There are some other parts that fail when you run the full angular test suite fails on PhantomJS

Yeah, PhantomJS is not use of the officially supported browsers, so we don't run tests against it and our testsuite is not 100% "PhantomJS-compatible". But many people are using it in their projects without a problem (including myself).

**Pull request closed without merging**
