### PR TITLE
test($rootScope): add tests clarifying $watchGroup oldValues behavior

### LINKED ISSUE #16024: RELEASE: Document behavior change in watchGroup in master
**I'm submitting a ...**

- [ ] bug report
- [ ] feature request
- [x] other (Please do not submit support requests here (see above))

**Current behavior:**
In 1.6, a watchGroup, every expression is watched individually, and this means the oldValue in the actionFn only changes if the underlying expression has changed. This means if expression 2 changes, but expression 1 does not, in the next actionFn invocation, the oldVal / newVal for expression 1 will be the same as in the last invocation. **This is logical, but unexpected since watch and watchCollection don't have this behavior. It also makes it impossible to see which expression has changed before the current invocation.**

In master, the behavior is consistent with watch / watchCollection in a way that the oldVal / newVal diff is based on the invocation of the actionFn. However, **now the oldVal can be the same as the newVal once the expression has changed at least once, which will never happen in watchC or watch after the first invocation.**

~~This was changed accidentially (I assume) in https://github.com/angular/angular.js/commit/c2b8fab0a480204374d561d6b9b3d47347ac5570~~

~~The validity of the 1.6 behavior has been discussed and approved here https://github.com/angular/angular.js/issues/8671#issuecomment-52960680~~

**Expected / new behavior:**
~~Either:~~

- ~~revert the change~~
- mark the new behavior as intended.
  - This needs new tests (the commit didn't break any tests, so there must be some missing)
  - identying possible BCs and workarounds
  - an update of the changelog

**Minimal reproduction of the problem with instructions:**
http://plnkr.co/edit/sFO6B2zUhRwwF9bkrxe3?p=preview

**Angular version:** master

**Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Anything else:**

### PR DESCRIPTION
**Pull request by jbedard**
Closes #16024

The first group seem related but have always passed.  The second group fail in v1.6.x as noted in the comments.  IMO these tests (with the notes about 1.6) show how weird the `oldValues` were before.

~~Still need to add the BREAKING CHANGE message.~~

### CODE REVIEW

**Review by gkalpak — APPROVED** [review]
LGTM except that:
1. You need to have a `:` after `BREAKING CHANGE` in the commit message (per [guidelines][1]) :grin:
2. The breaking change notice doesn't make it clear that it refers to `$watchGroup()`.
3. Since this is a `test(...)` commit, it won't be included in the changelog (so we still need to manually include the BC, I think).

[1]: https://github.com/angular/angularjs.org/blob/c346cbcabb55ebbb337b17dfb86dd191b58a264a/src/google-code-prettify/prettify.css#L29

**Comment by jbedard** [comment]
I've updated the commit message and removed the extra comments from the tests.

**Comment by jbedard** [comment]
Also created https://github.com/angular/angular.js/issues/16514 for updating the changelog like we discussed

**Review by gkalpak — APPROVED** [review]

**Comment by jbedard** [comment]
Is the BC message 100% clear? There must be at least one typo in there! :laughing:

**Comment by gkalpak** [comment]
> Is the BC message 100% clear?

It is to me.

> There must be at least one typo in there!

Well...if you absolutely want to fix a typo, you can fix _"will will lways"_ :grin:

**Comment by jbedard** [comment]
Will fix that. Now I know you read it! 😄

**Comment by jbedard** [comment]
Fixed the typo in the commit message.

**Comment by Narretz** [comment]
I've merged the commit without the BC message. In a test scope commit it's just confusing.

**Pull request merged**
