### PR TITLE
feat: add new module "ngStyle" support css loading via component

### PR DESCRIPTION
**Pull request by meiram-tr**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
feat

**What is the current behavior? (You can also link to an open issue here)**
Exist in angular 2, not yet in angular 1.x

**What is the new behavior (if this is a feature change)?**
Add new module to load css styles via components like angular 2 does.

for example: 
```js
var mod = angular.module('helloStylesApp', ['ng', 'ngStyle']);
mod.component('helloStyles', {
  templateUrl: 'hello-styles/hello-styles.html',
  // add dynamically styles for comopnent
  styleUrls: ['./base.css', './hello-styles/hello-styles.css'],  // or styles: 'a {color: red; } h2 {color: green;}',
  // another option is to use:
  controller: ['$style', '$styleRequest', '$timeout', function ($style, $styleRequest, $timeout) {
    // Add style dynamically 
    $style.addStyleUrls(['./base.css', './hello-styles/hello-styles.css']).then(function (data) {
      ... 
    });
  
    // Remove style dynamically 
    $style.removeStyle(['./hello-styles/hello-styles.css']);
    
    // Or just fetch the style for js manipulation
    $styleRequest('./hello-styles/hello-styles.css').then(function(cssText){
      ...
    });
  }]
});
```

**Does this PR introduce a breaking change?**
No

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**Other information**:

The implementation of this feature considered the minimum changes to the compile function in order to keep the code as is.

### CODE REVIEW

**Comment by gkalpak** [comment]
Hi @MeirAmar. I see you've been hard at work here :smiley:

Has this feature been discussed somewhere? If yes, you should link to the discussion. If not, keep in mind that major changes (such as this one) should be discussed first so that we can better coordinate our efforts, prevent duplication of work, and help you to craft the change so that it is successfully accepted into the project.

Can you add a summary of what this feature is about (e.g. what it does and how it works)?

**Comment by MeirAmar** [comment]
Hi @gkalpak, 
I tell you the truth this is my first PR for the Angular project. I have searched a little in the git comments and the PRs for some similar feature but I didn't found any (Maybe there is one out there and i didn't found yet). Anyway, where should such a discussion thread should be? I will add more about this feature (I thought what I written in the behavior is enough ;) ).

Thanks
Meir

**Comment by gkalpak** [comment]
You could have opened an issue on GitHub for discussion.

##
All the "new behavior" section says is:

> Add new module to load css styles via components like angular 2 does.

That is clearly inaccurate (as shown in your example that follows) and likely impossible :smiley: (since Angular has its own HTML and CSS parsers, which AngularJS does not).

**Comment by MeirAmar** [comment]
@gkalpak - thanks for your clarification.  I was misunderstood, I meant "like" by syntax only. 
I will try to make myself clearer. I added a new issue https://github.com/angular/angular.js/issues/15805 as you suggested let me know if you have another notes/remarks for me.

Meir

**Comment by Narretz** [comment]
This is not gonna happen as we are in LTS

**Pull request closed without merging**
