### PR TITLE
x5 optimization: do not run watchers on isolated scopes if their isolated bindings hasn't changed

### PR DESCRIPTION
**Pull request by kostat**
This optimization reduces number of running watchers by x3 - x10 in apps with big number of isolated scopes.
#### How?

Do not run the isolated scope watchers if its scope definition bindings (e.g. `{label: '@'}`) hadn't changed.
#### Motivation

The common use case for  directives with isolate scope is to create kind of a widget. With isolate scope bindings it "connects" to its "public" interface and should implement its internal functionality using _ONLY_ these fields, model-wise. In other words, any inner watchers should entirely depend (directly or indirectly) on the "public" interface. Any direct watchers to parental scopes is discouraged.
Let's evaluate scenarios of what happens then:
- Templating: the mapped field is used inside a template, e.g. there is a mapping like `label: '@'` and somewhere in the template `{{label}}`. While the template is linked, it installs a watch that evaluates the expression. It's clear that if the outer `@label` is not changed it's useless to evaluate the expression since it's not changed. Consider that the expression can be more complex: `{{label}}: {{getFullName()}}`. Currently, all this runs several times during $digest cycle for nothing.
- Custom watches: the user installs a watch using a `function(){...}`. The function must return a value , in many cases the value is computed and the computation can be untrivial. The sad part is that if the isolated bindings hasn't changed, this computation should return the same value! So again, it will run for nothing...

Now consider an app that makes an intensive use of "widgets", like a typical LOB app. This optimization substantially boosts its performance (x5-x10).
#### Cons

Unfortunately this change can break an existing code. If the user creates watches to parental scopes, the system might behave abnormally: if the callback will change some scope values, the UI can be not updated.
- In the first place, this kind of watchers is discouraged and can be considered as a bug in user code
- I provide a method `scope.$setDirty()` that can be used to "fix" the problem

In any case, this issue makes this PR inappropriate for minor release. So there are 2 options:
1. The directive will mark somehow that a new isolated scope behavior can be used, in this case no old code will be broken and this can be merged.
2. Wait for a major release.

In my opinion (1) is better: like in Google [Guava](https://github.com/google/guava), there is a concept of `@Beta` features. This way the users might test the new functionality and provide feedback before it's released.

---

I created a demo app, which logs "skipped" scopes and # of watcher checks. In original angular number of checks is x3 - x10.

http://ngforms.azurewebsites.net/

### CODE REVIEW

**Comment by lgalfaso** [comment]
This PR would break an angular app for too many people, so unless we implement something like Zone.js or something similar, then this cannot land. If you still think that there is some value that would help with this, then please send an email to the angular forum, explain the idea and create a document explaining all the side-effects. Thanks

**Comment by petebacondarwin** [comment]
@kostat - thank you for all the time that you have put into this feature. We do appreciate any effort to improve the performance of Angular.

Just to be clear, I had a quick play with this too.  The PR needed a bit of rebase-love but now we do indeed have a unit test failure, which is related to the new `bindToController` feature.

This test fails:

```js
    it('should update @-bindings on controller when bindToController and attribute change observed', function() {
      module(function($compileProvider) {
        $compileProvider.directive('atBinding', valueFn({
          template: '<p>{{At.text}}</p>',
          scope: {
            text: '@atBinding'
          },
          controller: function($scope) {},
          bindToController: true,
          controllerAs: 'At'
        }));
      });

      inject(function($compile, $rootScope) {
        element = $compile('<div at-binding="Test: {{text}}"></div>')($rootScope);
        var p = element.find('p');
        $rootScope.$digest();
        expect(p.text()).toBe('Test: ');

        $rootScope.text = 'Kittens';
        $rootScope.$digest();
        expect(p.text()).toBe('Test: Kittens');
      });
    });
```

With the following error:

```
Expected 'Test: ' to be 'Test: Kittens'.
```

Also for an additional working broken example see the following pair of plunkers:

* No optimisation: http://plnkr.co/edit/TzdAbvIj0DkrAX0gQa6v?p=preview
* With optimisation: http://plnkr.co/edit/DhTGVsErIGpIWmoDdvAJ?p=preview

The application code is pretty simple:

```js
// Code goes here

angular.module('app', [])

.factory('auth', function() {
  var loggedIn = false;
  return {
    isLoggedIn: function() {
      return loggedIn;
    },
    login: function() {
      loggedIn = true;
    },
    logout: function() {
      loggedIn = false;
    }
  };
})

.directive('loginview', function(auth) {
  return {
    restrict: 'E',
    scope: {},
    template: 'LoginView: <div ng-show="isLoggedIn">Logged In</div>',
    link: function($scope) {
      $scope.$watch(function() { return auth.isLoggedIn(); }, function(isLoggedIn) {
        $scope.isLoggedIn = isLoggedIn;
      });
    }
  };
})


.run(function($rootScope, auth) {
  $rootScope.login = function() {
    auth.login();
  };
  $rootScope.logout = function() {
    auth.logout();
  };
});
```

The thing to note is that we are watching an external service from inside our isolated scope. This is a common pattern in Angular applications and with the optimisation in place, we never get any update to the isolated scope when the `auth` service changes.

**Comment by kostat** [comment]
@petebacondarwin: thanks for your comments, it was a nice surprise to see that someone actually looks into this.
Let me state _again_ the problem and hopefully contribute to sharpening it, as folks are trying to fix something in this area, like #10658.

The problem: as the application gets larger, number of $watchers running in each $digest increases non linearly (more $watchers -> more chances for multiple cycles) making it to run slow. But the real problem is that *most of them run for nothing* and there is *no mechanism to detect this in advance*.

Therefore I think that #10658 tries to solve the very same problem in a different way.

Now let me tell the logic behind the solution I propose. The goal was simple: "How to make it in a way to not break stuff subtly without really knowing why". While designing the feature, I set several requirements:

1. Declarative. No API like $suspend/$resume as this will make every case special. Ideally it must be a flag/indication on DDO.
1. Integrates well into angular architecture. So I can explain to the developers what to do and what not to do and it will be easily understood.
1. Effective - must prevent most of unneeded $watcher checks.
1. Opt-in. (It's not part of my PR, as there is no convention for this; clearly it can be easily added).

When I first encountered directives with isolated scope, I immediately compared them with controls/widgets existing in other UI toolkits (not only JS based). In *all* systems I know, displaying data that comes not from widgets properties (i.e. public widget interface) is discouraged. (In most cases it's not even possible since widgets come from 3rd party vendors - jquery, teleric, infragistics, openfaces - I cannot remember a component that displays anything that is not passed via public API).

Due to unknown (to me) reason this is OK in angular, and you refer this as a broken use case... in loginview. To fix it, I would recommend to make 'auth' a dependency for controller, have a method isLoggedIn() on it that will delegate to 'auth' service. Then the directive will look like this and work:

```javascript
.directive('loginview', function() {
  return {
    restrict: 'E',
    scope: {
       visible: '=',
    },
    template: 'LoginView: <div ng-show="visible">Logged In</div>'
  };
})
```

And used as `<loginview ng-controller="myController as ctrl" visible="ctrl.isLoggedIn()" />`.

In any case, it was a very clear message to developers - display data/$watch things that come from isolated scope definition only. So we did not encountered 'subtle breakages' while using this feature.

P.S. of course it's easy to fix the bindToController test failure if there will be an interest in this PR.

**Comment by lgalfaso** [comment]
Hi, it looks clear that https://github.com/angular/angular.js/pull/10221#issuecomment-72199927 https://github.com/angular/angular.js/pull/10221#issuecomment-72295412 show different realities of what a directive is. The later makes the assumption that a directive only reacts based on a change from a bind on the parent scope. The former does not make this assumption and directive can change based on whatever event.
As Pete said, Angular developers do not make the assumptions made in the PR. People expect directive to have some smartness and logic in them. I would also vote against making this an opt-in, the reason being that for this to work __all__ of your directives need to work this way, and as soon as any third party module is added, you have to be sure that it works in this specific way. This is a burden just too big.

**Comment by kostat** [comment]
@lgalfaso:
> for this to work all of your directives need to work this way

This is not true. This can be safely work per directive, provided the opt-in indication is on DDO.

**Comment by petebacondarwin** [comment]
If it were opt-in then indeed it can and should be on a per-directive basis.

Let's identify all the possible cases that would break, even on an opt-in directive - then we can either ensure that they are all prevented or agree what would be an acceptable documented limitation.

One case that @lgalfaso has brought up is proper resolution of promises inside an isolated scope.  @kostat - could you take a look at how this could be handled? I don't think that this would be an acceptable limitation; whereas not watching things outside the isolated scope could be.

**Comment by kostat** [comment]
@petebacondarwin: ok, will look into it

**Comment by kostat** [comment]
@petebacondarwin: resolution of promises: one option would be to expect a promise from the listener. if yes, we can subscribe to it and fix the situation. So in the @lgalfaso use case the user will write:
```javascript
function FooContoller($scope, $q) {
  $scope.$watch('foo', function() {
    return $q.when().then(function() {
      $scope.bar = $scope.foo;
    });
  });
}
```
Another option is to require the user to invalidate the scope explicitly:
```javascript
function FooContoller($scope, $q) {
  $scope.$watch('foo', function() {
    $q.when().then(function() {
      $scope.bar = $scope.foo;
      $scope.$setDirty();
    });
  });
}
```
My take is that both should be supported.

---
Regarding the broken use cases - I think it would be not easy to identify all of them or the list might be  long with many esoteric things like ancestors scopes, services etc. Instead, I suggest to say what to do, since the message is very simple: listener code/template will be updated only if one of "public" bindings has changed. + the promises use case above.

**Comment by lgalfaso** [comment]
In Angular 1, we lack the machinery to detect when promises are resolved and when timers executed (and in what context/scope), so this cannot land. Angular 2 adds some machinery that makes this possible (and adds the concept of a pure directive), but this machinery is too heavy to be just added to Angular 1. Closing this as there is no easy way for Angular 1 to have this machinery without too many breaking changes.

**Pull request closed without merging**
