### PR TITLE
Disallow non-isolate scope & default controllerAs to be $ctrl

### PR DESCRIPTION
**Pull request by shahata**

### CODE REVIEW

**Comment by gkalpak** [comment]
LGTM (if travis is happy) :+1:

**Comment by petebacondarwin** [comment]
LGTM - merging

**Comment by shahata** [comment]
Oops, forgot to add a breaking change note...

**Comment by petebacondarwin** [comment]
Right, we will have to remember to add it to the CHANGELOG.

**Comment by gkalpak** [comment]
(Stating the obvious) also, remeber not to add it to the migration docs (`v1.4  -->  v1.5`) :smile:

**Comment by petebacondarwin** [comment]
Or at least not to mention the "previous" form of the component helper :-)

**Pull request closed without merging**
