### PR TITLE
docs: cleanup of directive animation classes 

### PR DESCRIPTION
**Pull request by brettdewoody**

### CODE REVIEW

**Comment by brettdewoody** [comment]
I signed it!

**Comment by brettdewoody** [comment]
Being my first PR on this repo I'm not sure how to proceed. Do I need to fix my PR?

**Comment by Narretz** [comment]
I don't think the changes are quite correct. `add`, `enter` etc. don't mean the classes that are added, these are the actual events that are fired by the animation code.

**Comment by brettdewoody** [comment]
Do you think it would be helpful to add an examples of the classes added using for each directive?

**Comment by Narretz** [comment]
We had a great overview over the phases until the 1.3.x docs: https://code.angularjs.org/1.3.18/docs/api/ngAnimate/service/$animate We should get those back in.some way.

**Pull request closed without merging**
