### PR TITLE
doc(angular.bootstrap): document debugInfoEnabled

### PR DESCRIPTION
**Pull request by thorn0**
Or is it not documented for a reason?

### CODE REVIEW

**Comment by gkalpak** [comment]
I think it is a private option (aka not documented on purpose).
It is only useful for debugging, and for that there is already [angular.reloadWithDebugInfo][1].
[1]: https://docs.angularjs.org/api/ng/function/angular.reloadWithDebugInfo

**Comment by thorn0** [comment]
`reloadWithDebugInfo` calls `location.reload()`. If someone resorts to using `angular.bootstrap`, it usually means that his/her app isn't bootstrapped automatically after the page is loaded.

**Comment by gkalpak** [comment]
The `config.debugInfoEnabled` property in `bootstrap()` is only used internally for implementing `angular.reloadWithDebugInfo()`.

If the user wants to have debug info enabled:

* permanently: They should use `$compileProvider.debugInfoEnabled(true)`.
* temporarily (for debugging): They should use `angulat.reloadWithDebugInfo()`.

--
There is no need to use the `config.debugInfoEnabled` property in `bootstrap()`.
I think it should stay private (i.e. undocumented).

**Comment by thorn0** [comment]
It's enabled by default. But I just reread the source of `angular.bootstrap` and found out that passing `debugInfoEnabled: false` to this function actually doesn't have any effect. Only `true` does.

**Comment by thorn0** [comment]
So this option doesn't fully control `debugInfoEnabled` as it can only enable it, but can't disable. Thus it really doesn't look suitable for public API.

**Pull request closed without merging**
