### PR TITLE
fix(sanitize): handle newline characters inside <script> for IE

### PR DESCRIPTION
**Pull request by lgalfaso**
Tweak the regex used match characters inside <script> and <style> to a IE compatible regex.

### CODE REVIEW

**Comment by petebacondarwin** [comment]
I thought the normal way to match anything is `[\W\w]*`. Does that work with IE <11?
I would rather not be sniffing this.

**Comment by petebacondarwin** [comment]
Or I think I meant `[\s\S]`

**Comment by lgalfaso** [comment]
@petebacondarwin let me try

**Comment by lgalfaso** [comment]
@petebacondarwin Travis failed as there was some issue with SourceLabs, but the relevant test now passed

**Comment by lgalfaso** [comment]
this is breaking Travis, so landing this 030a42e79dec8a4bb73053762f7a54d797a058f6

**Pull request closed without merging**
