### PR TITLE
docs(guide/Directives): mentioned shorthand for "return function()"

### PR DESCRIPTION
**Pull request by zbycz**
The shorthand is little confusing, added clarification.

### CODE REVIEW

**Comment by Narretz** [comment]
Hi, thanks for your PR! However, before we can merge we need you to sign the CLA.

**Comment by Narretz** [comment]
Imo, we should change the example to use the verbose way of defining a directive. That makes it clearer.

**Comment by lgalfaso** [comment]
Agree with @Narretz

**Comment by zbycz** [comment]
Quite contrary, i'd like to learn that the shorthand exists - it can be seen in other projects as well. Just the clarification was missing. 

I signed the cla, should i do something more? (On https://cla.developers.google.com/clas i see my individual CLA with correct email and github name..)

**Pull request closed without merging**
