### PR TITLE
Update cacheFactory.js: Added peek() for returning all keys

### PR DESCRIPTION
**Pull request by zsong**
Added peek() for returning all keys.

### CODE REVIEW

**Comment by eranimo** [comment]
Can we get this in?

**Comment by ajwhite** [comment]
This appears abandoned. Plus, the commits do not follow the contribution guidelines so there's still work that needs to be done. Plus a rebase.

**Comment by axschech** [comment]
Is anything happening with this?

**Comment by jmdobry** [comment]
You can replace Angular's `$cacheFactory` with [angular-cache](https://github.com/jmdobry/angular-cache) instead, and get goodies like this right now.

It's a point of discussion, but I think certain parts of Angular should be as lightweight as possible (or removed entirely). You then bring in various libraries (like angular-cache) that are really good at what they do to augment your app, so Angular doesn't have to be a slow-moving behemoth.

**Comment by JohannesHoppe** [comment]
I use this:


```javascript
app.config(['$provide', function($provide) {

    // monkey-patches $templateCache to have a keys() method
    $provide.decorator('$templateCache', [
        '$delegate', function($delegate) {

            var keys = [], origPut = $delegate.put;

            $delegate.put = function(key, value) {
                origPut(key, value);
                keys.push(key);
            };

            // we would need cache.peek() to get all keys from $templateCache, but this features was never
            // integrated into Angular: https://github.com/angular/angular.js/pull/3760
            // please note: this is not feature complete, removing templates is NOT considered
            $delegate.getKeys = function() {
                return keys;
            };

            return $delegate;
        }
    ]);
}]);
```

**Comment by petebacondarwin** [comment]
I agree with @jmdobry here. Please use custom implementations of caching, such as https://github.com/jmdobry/angular-cache, or roll your own, as @JohannesHoppe has done.

**Comment by DinisCruz** [comment]
I  just implemented @JohannesHoppe idea on https://github.com/DinisCruz/Maturity-Models using coffee script.

Here is the code and tests

**Patches.coffee**
```coffee
angular.module('MM_Graph')
  .config ($provide)->

      $provide.decorator '$templateCache', ($delegate)->                 # adds a keys() method to $templateCache
                                                                         # (based on http://stackoverflow.com/a/37834469/262379)
        keys = []                                                        # variable to store keys added
        origPut = $delegate.put                                          # capture the original put method
        $delegate.put = (key, value)->                                   # replaced it with our own
          origPut(key, value)                                            # call original
          keys.push(key)                                                 # store value in keys variable

        $delegate.get_Keys = ()-> keys                                   # new method to return keys

        return $delegate
```

**Patches.test.coffee**
```coffee
describe '| angular | Patches ', ->

  beforeEach ()->
    module('MM_Graph')

  it '$templateCache.get_Keys',->
    inject ($templateCache)->
      test_Key   = 'an_Key'
      test_Value = 'an_Value'
      
      using $templateCache, ()->
        @.keys().assert_Is [ 'put'    , 'get'  , 'remove', 'removeAll',   
                             'destroy', 'info' , 'get_Keys'           ] # confirm method was added to object
        
        @.get_Keys().size().assert_Is $templateCache.info().size        # check get_Keys size
        @.get_Keys().assert_Not_Contains test_Key                       # confirm test key is not there
        
        @.put test_Key, test_Value                                      # add a new key/value pair
        
        @.get_Keys().assert_Contains test_Key                           # confirm that test key is now there
        
        @.get(test_Key).assert_Is test_Value                            # confirm that test value is now mapped to test key

        @.get_Keys().size().assert_Is $templateCache.info().size        # double check that this still works ok
```

**Comment by gkalpak** [comment]
You also need to patch `remove` fwiw.

**Comment by maniakill** [comment]
I don't know if anyone is interested in this anymore, but I have update the code  @JohannesHoppe for a `remove` method also.
` $provide.decorator('$templateCache', [
	        '$delegate', function($delegate) {

	            var keys = [], origPut = $delegate.put, origRem = $delegate.remove;

	            $delegate.put = function(key, value) {
	                origPut(key, value);
	                if(keys.indexOf(key) === -1){
		                keys.push(key);
		            }else{
		            	keys[key]= value;
		            }
	            };

	            $delegate.remove = function(key) {
	                origRem(key);
	                keys.splice(keys.indexOf(key),1);
	            };

	            $delegate.getKeys = function() {
	                return keys;
	            };

	            return $delegate;
	        }
	    ]);`

**Comment by anoopmd** [comment]
Thanks for the solution @JohannesHoppe

**Comment by JohannesHoppe** [comment]
Hey guys, you should all switch to Angular 2/4 now! ;-)

**Comment by logist** [comment]
AngularJS 1.7+ requires template cache implementation to return template value in put() since https://github.com/angular/angular.js/commit/fb00991460cf69ae8bc7f1f826363d09c73c0d5e

New function definition would be 

> I don't know if anyone is interested in this anymore, but I have update the code @JohannesHoppe for a `remove` method also.
> ` $provide.decorator('$templateCache', [
> 
> ```
>         '$delegate', function($delegate) {
> 
>             var keys = [], origPut = $delegate.put, origRem = $delegate.remove;
> 
>             $delegate.put = function(key, value) {
>                 if(keys.indexOf(key) === -1){
> 	                keys.push(key);
> 	            }else{
> 	            	keys[key]= value;
> 	            }
>                 return origPut(key, value);
>             };
> 
>             $delegate.remove = function(key) {
>                 keys.splice(keys.indexOf(key),1);
>                 return origRem(key);
>             };
> 
>            
> 
>             $delegate.getKeys = function() {
>                 return keys;
>             };
> 
>             return $delegate;
>         }
>     ]);`
> ```

**Pull request closed without merging**
