### PR TITLE
fix(rootScope, ngRepeat): add support for objects created with Object.create(null) for ngRepeat and $watchCollection

### PR DESCRIPTION
**Pull request by HeberLZ**
Basically, the hasOwnProperty method was being called from an object gotten from the user. When that object was initially created with Object.create(null), it didn't inherit from Object so it didn't have the hasOwnProperty method throwing an "undefined is not a function" error. 

This was fixed by executing hasOwnProperty.call(object, key) instead of object.hasOwnProperty(key)

### CODE REVIEW

**Comment by petebacondarwin** [comment]
I added some tests and landed this for 1.4.x.

**Comment by ocombe** [comment]
I guess @HeberLZ never made it home :(

**Comment by imcotton** [comment]
@ocombe, I think the man just fine according to his GitHub activity :relieved:

**Comment by HeberLZ** [comment]
I'm really sorry about this, completely forgot about this pr because at the company i used to work at, we stopped using Object.create(null)

**Pull request closed without merging**
