### PR TITLE
Modified the short date using yyyy

### PR DESCRIPTION
**Pull request by chowlouise**
Improved short date for nl, fr,, en and de

### CODE REVIEW

**Comment by lgalfaso** [comment]
Hi, thanks for the PR! The locale information is retrieved and auto-generated from Google closure library. If there is any change, then this change should be performed there (and the changes will get eventually propagated here). Check "Localization Issue" at https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#-found-an-issue

Closing this but feel free to comment on the issue when the changes are accepted in the other project and the locale files need to be generated.

**Comment by chowlouise** [comment]
by the way i could not find the files in https://github.com/google/closure-library/tree/master/closure/goog/i18n? which file i need to change in order to achieve the same changes?

**Comment by lgalfaso** [comment]
The file is https://github.com/google/closure-library/blob/master/closure/goog/i18n/datetimesymbols.js

**Comment by chowlouise** [comment]
thanks a lot

**Pull request closed without merging**
