### PR TITLE
Remove unneeded window reference

### PR DESCRIPTION
**Pull request by david-mark**
The document object is global.

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

**What is the current behavior? (You can also link to an open issue here)**

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change?**

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Other information**:

### CODE REVIEW

**Comment by david-mark** [comment]
I signed the CLA.

**Comment by david-mark** [comment]
The global `document` identifier needs to be added to here as well:
https://github.com/angular/angular.js/blob/07849779ba365f371a8caa3b58e23f677cfdc5ad/.eslintrc-browser.json

For some reason I don't see that file in my fork (at least not on GitHub). (?)

**Comment by gkalpak** [comment]
> The document object is global.

Depends on the environment :smiley:

This was deliberately added in #14345, in order to prevent a certain type of issues or make some usecases easier (see #14345 for more info).

**Comment by david-mark** [comment]
Couldn't imagine using AngularJS in Node (e.g. with jsdom), but apparently some can. :)

**Pull request closed without merging**
