### PR TITLE
optimize angularInit function . do not foreach candidate if the element is retrived

### PR DESCRIPTION
**Pull request by omarProgrammer**
If the element Module is retrived then do not foreach for retrive a candidate children element

### CODE REVIEW

**Comment by gkalpak** [comment]
This seems like a reasonable change. Note that you need to [sign the CLA][1], before we can merge it ?

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#cla

**Comment by omarProgrammer** [comment]
@gkalpak  please can you help me to  resolve CLA i have registred with my email i signed my userName's github.

Regards
Omar

**Comment by gkalpak** [comment]
@omarProgrammer, afaik you need to sign the CLA with the email that appears on the commit (which is not necessarily the same as the one you've registered with on GitHub).

If the email is the same (can't check right now) and it's still not recognized, let us know and someone will look into it :smiley:

**Comment by gkalpak** [comment]
@omarProgrammer, I see you have 2 accounts in GitHub (@omarProgrammer and @OmarBERRABEH) and the first 2 commits seem to have different author than the 3rd. That's why @googlebot can't verify the CLA (for at least one of the commits).

BTW, if the first two commits are just cancelling each other out, you can get rid of them altogether.

**Comment by petebacondarwin** [comment]
Closing due to lack of response.

**Pull request closed without merging**
