### PR TITLE
feat(ngResource): allow a resource URL to be a closure called when building URL

### PR DESCRIPTION
**Pull request by carab**
Hi everyone,

I was in need of dynamic URL resources for a project where the user can configure from which API the data is fetched.

I didn't find any way to do this properly, but I saw that URL param value can be a function called to get the effective value, so I did the same with URL.

Thanks.

### CODE REVIEW

**Comment by doshprompt** [comment]
+1 for this, it's pretty old and also it seems trivial, can someone please reconsider adding this into the ng codebase

**Comment by caitp** [comment]
$resource instances aren't created before the config phase of the application, so is there any reason why you can't just build the URL pattern you want statically?

I don't feel strongly one way or the other about this, I guess

**Comment by carab** [comment]
Actually, I needed this once because my app allowed the use to switch between several configurations.
I didn't look at it for a while so I need to update the pull request to fix the conflicts.

**Comment by doshprompt** [comment]
@caitp My use case is the same as @carab, depending on some configuration set by the user the base url for the api endpoint will change, for example from us.api.com/objects to eu.api.com/objects etc.

**Comment by caitp** [comment]
@doshprompt but the thing is, this can be configured during the config phase, and then you can still use the static URL. This doesn't really require any dynamic URL

**Comment by caitp** [comment]
I prefer to keep potential side effects out of the framework, but see what other people think. @petebacondarwin do you have an opinion here?

**Comment by petebacondarwin** [comment]
I agree with @caitp - you can create a service that instantiates a new resource if the configuration changes.  Perhaps something along the lines of:


```js
mod.factory('resources', function($resource) {
  var service = {
    configureResources: function(newUrl) {
      service.myResource = $resource(newUrl, ...);
    }
  };
  service.configureResource('some/default/url');
  return service;
});

mod.controller('Ctrl', function($scope, resources) {
  $scope.$watch('url', function(value) {
    resources.configureResource(value);
  });

  $scope.getItems = function() {
    $scope.items = resources.myResource.query();
  };
});
```

**Comment by carab** [comment]
I see, it's indeed a better solution, don't know why I didn't think about
it.
Thank you for your time.

2015-01-07 20:22 GMT+01:00 Pete Bacon Darwin <notifications@github.com>:

**Pull request closed without merging**
