### PR TITLE
Facebook was mispelled as Faceb0ok

### PR DESCRIPTION
**Pull request by stevenw**

### CODE REVIEW

**Comment by caitp** [comment]
@pc035860 do you have an opinion on this?

**Comment by pc035860** [comment]
@caitp Nope. Good to go!

**Comment by caitp** [comment]
great thanks!

**Comment by stevenw** [comment]
I signed it!

**Comment by caitp** [comment]
Steve, can you make sure you've signed it with the email the patch was committed with? That will help out a lot.

**Comment by stevenw** [comment]
Its definitely the same email address as my github. I also created the patch using the github.com browser  editor, no git client.

**Comment by caitp** [comment]
Thanks, the robot should confirm that in a few hours i believe

**Comment by caitp** [comment]
Will re-close when confirmed

**Comment by stevenw** [comment]
anyway I can get this off of my list?

**Comment by caitp** [comment]
well, I'm not sure why I reopened this, but yeah

**Pull request closed without merging**
