### PR TITLE
perf($compile): use static jquery data method to avoid creating new instances

### PR DESCRIPTION
**Pull request by jbedard**
Really minor, but the static `jqLite.data` does the same thing when there is only one node...

### CODE REVIEW

**Comment by lgalfaso** [comment]
Mmm... not sure about this change. Creating a new instance should not be that expensive for us to have to optimize this...

**Comment by jbedard** [comment]
It's not expensive at all in a method like this. But it's also simpler (less code) imo so it seemed like a positive change to me...

**Comment by lgalfaso** [comment]
using `data` (or any other method) this way is documented nor supported. I see no reason why we should start using them in this way

**Comment by jbedard** [comment]
The jquery version is [documented](https://api.jquery.com/jquery.data/) and the jqlite version is equivalent (although not documented).  They are already used in a few places where it does actually make a difference (linking).

**Comment by jbedard** [comment]
Also note that the `hasData` call right above this line is also the static version (and there is no instance version), so I think it makes sense for this line to do the same.

**Comment by lgalfaso** [comment]
Mmm... ok.

LGTM

**Comment by petebacondarwin** [comment]
Landed as 9b90c32f31fd56e348539674128acec6536cd846

**Pull request closed without merging**
