### PR TITLE
Route continues to be processed even if providing a redirectTo

### PR DESCRIPTION
**Pull request by jardilio**
If a route defines a redirectTo value, the current route should stop processing the route and instead wait to process the route of the redirect. 

Currently, what is happening is that Angular detects a redirectTo value and updates $location, but then continues processing the route that was intended to be redirected. Templates are loaded, resolves are processed, ng-view then updates the view with a new template and instantiates the controller all for a route that should have been redirected.

A common use case for assigning a function to the redirectTo is to validation authentication, permission check, or some other logic to determine if the route should continue or redirect else where. In the end, this happens, but in between, unexpected results may occur by updating the view and instantiating controllers for logic that wasn't expected to be executed.

http://plnkr.co/edit/8QlA0ouuePH3p35Ntmjy?p=preview

### CODE REVIEW

**Comment by petebacondarwin** [comment]
LGTM - I am going to rebase and see if it breaks anything.
There is a small chance of a Breaking Change in case people expected a redirected controller to run...

**Comment by maximnaidenov** [comment]
@petebacondarwin Seems there is a regression in latest ngRoute 1.6.3 and resolves are again  processed twice for routes that have redirectTo value. Most likely the regression is caused by [feat($route): implement `resolveRedirectTo` ](https://github.com/angular/angular.js/commit/e9865654b39c71be71034c38581a8c7bd16bc716)

**Comment by petebacondarwin** [comment]
@maximnaidenov - can you provide a reproduction? That commit was from almost a year ago.

**Comment by maximnaidenov** [comment]
@petebacondarwin While preparing a sample I realized the problem is in my code and is provoked by the restructuring in the mentioned feature. Sorry for bothering you.

**Pull request closed without merging**
