### PR TITLE
fix(jqLite): return if element is undefined

### PR DESCRIPTION
**Pull request by seaside98**
ngAnimate has problems removing elements, causing errors. A detailed explanation of this can be found at #8796.

See #9485

[Review on Reviewable](https://reviewable.io/reviews/angular/angular.js/12226)

### CODE REVIEW

**Comment by seaside98** [comment]
I signed it!

**Comment by lgalfaso** [comment]
Without a way to know how the original issue happen, I am inclined not to merge this PR.

@matsko do you have enough information to know if this is still an issue with 1.4.x?

**Comment by seaside98** [comment]
How am I the only one dealing with this? I just started a new, completely unrelated project, and I'm getting ng339 errors. The only similarity I can find is that they both have long (300+ items) ```ng-repeat```s.

**Comment by seaside98** [comment]
@lgalfaso @matsko This bug is breaking yet another one of my apps. I have uploaded some code to jsbin for demonstration purposes. Basically, I am just ng-repeating a large list and then rapidly changing the values of the list. Obviously this isn't how I am encountering the bug in my apps, but it is the easiest way to demonstrate the problem. This bug is quite annoying to replicate, sometimes the app breaks on my first try, other times it will go for several minutes with no problems at all. 

http://jsbin.com/vayade/edit?html,js,output You will probably have to rerun the script a number of times to get the bug to show up (```b.ng339 does not exist```). 

Also, I am using **Safari 8.0.8**. I have not been able to replicate this issue in Chrome, though I don't spend nearly as much time with Chrome.

**Comment by lgalfaso** [comment]
@seaside98 run the script at the jsbin ~50 times and not even once the error show up. Is there some specific step that needs to happen for this error to trigger?

**Comment by seaside98** [comment]
Luck, really. I've found that lag helps.

In the meantime, I will try to build something that will break more consistently. I don't you if you have already read this, but if you haven't, the following is a detailed technical explanation of the bug. https://github.com/angular/angular.js/issues/8796

**Comment by td-edge** [comment]
@seaside98 You're not the only one dealing with this issue. A co-worker and I just stumbled across it with similar specifications. We are using angular 1.4.4 with ng-repeat of a long list and get the error randomly. The main development is being completed and checked in safari. I can post our stack trace if you want.

**Comment by seaside98** [comment]
@td-edge After updating to OS X El Capitan, I haven't seen the problem. The only pattern I can seem to find is that somehow the safari dev console must be causing enough lag to make this bug show up. Glad to hear I'm not the only one.

**Comment by Narretz** [comment]
Closing, see https://github.com/angular/angular.js/issues/9485#issuecomment-170402817

**Pull request closed without merging**
