### PR TITLE
use forEach instead of Object.keys in compiler Attributes constructor

### PR DESCRIPTION
**Pull request by jiubao**
use forEach instead of Object.keys in compiler Attributes constructor

### CODE REVIEW

**Comment by jiubao** [comment]
@googlebot I signed it!

**Comment by gkalpak** [comment]
I believe `Object.keys() + for-loop` was used for performance reasons.
What is the reason (other than readability maybe) for changing it ?

**Comment by jiubao** [comment]
@gkalpak:
1. Are there so many cases that `attributesToCopy` has a deep prototype inheritance structure?
2. Suppose it is the case, why not refactor `forEach` to use `Object.keys` instead of `for in` in the last two `else`:
```javascript
function forEach(obj, iterator, context) {
    ...
    } else if (typeof obj.hasOwnProperty === 'function') {
      // Slow path for objects inheriting Object.prototype, hasOwnProperty check needed
      for (key in obj) {
        if (obj.hasOwnProperty(key)) {
          iterator.call(context, obj[key], key, obj);
        }
      }
    } else {
      // Slow path for objects which do not have a method `hasOwnProperty`
      for (key in obj) {
        if (hasOwnProperty.call(obj, key)) {
          iterator.call(context, obj[key], key, obj);
        }
      }
    }
    ...
```
so that it does not have the `for in` performance issue, meanwhile get `forEach` benefits:
* support `obj.forEach`:
```javascript
    } else if (obj.forEach && obj.forEach !== forEach) {
        obj.forEach(iterator, context, obj);
    }
```
* may be faster in `isBlankObject` case:
```javascript
    } else if (isBlankObject(obj)) {
      // createMap() fast path --- Safe to avoid hasOwnProperty check because prototype chain is empty
      for (key in obj) {
        iterator.call(context, obj[key], key, obj);
      }
    }
```
)

**Comment by petebacondarwin** [comment]
Here is the relevant commit: https://github.com/jiubao/angular.js/commit/54fa16e45d8769ce6708a28388326db0eea53c7e

`attributesToCopy` always has extra properties up the prototype chain.

**Comment by jiubao** [comment]
OK, thanks for the explains!

**Pull request closed without merging**
