### PR TITLE
ngClick using ngTouch fires twice issue on iOS

### LINKED ISSUE #6251: ngClick using ngTouch fires twice
ngTouch 1.2.1 on Safari iOS 7 fires a second time by tapping wherever on the screen:

http://jsfiddle.net/coma/2hWWa/embedded/result/

http://stackoverflow.com/questions/21708730/why-are-multiple-click-events-fired-when-using-ngtouch/21766071#21766071

### PR DESCRIPTION
**Pull request by NorikDavtian**
This closes #6251

### CODE REVIEW

**Comment by NorikDavtian** [comment]
Signed

**Comment by NorikDavtian** [comment]
@mato75 it is ready to be merged.. it is not merged yet.. you can click on the files changed tab above and copy the changes to test it out for now.. hopefully makes it to the next release..

**Comment by mato75** [comment]
This fix doesn't resolve the problem. Now no even is triggered. I have a problem when tapping on input, the keyboard is not opened.

**Comment by NorikDavtian** [comment]
@mato75 then that might be a different issue, cause this issue is regarding events firing twice.. I suggest creating a new issue with a plunker example would speed up fixing your specific issue.

**Comment by cvbuelow** [comment]
Any plans to merge this? We need this fix.

**Pull request closed without merging**
