### PR TITLE
chore(injector): avoid invoking noop

### PR DESCRIPTION
**Pull request by mechpen**

### CODE REVIEW

**Comment by flhs** [comment]
I signed it!

**Comment by Narretz** [comment]
What's the problem with invoking noop? I suspect this was done for a reason.

**Comment by flhs** [comment]
Not a problem.  Maybe just coding style.  Please feel free to reject the pull request.

**Comment by lgalfaso** [comment]
Landed as b6389eedda4f24cf23d994fc22f030067c4ab13d

**Pull request closed without merging**
