### PR TITLE
fix() apostrophe in url

### PR DESCRIPTION
**Pull request by dmartres**
bug fix on $location service in case that url contains apostrophes

### CODE REVIEW

**Comment by gkalpak** [comment]
Thx for the PR, @dmartres!

From a quick look, I don't think the issue is specific to apostrophe. The main problem seems to be that we are comparing `self.url()` to `lastBrowserUrl`, but `lastBrowserUrl` can be set from different sources, not always with the same encoding/decoding. I think it boils down to two main cases:

- In some places, we set `lastBrowserUrl` to `location.href` (which is undecoded).
- In other places we set `lastBrowserUrl` to a value indirectly based on `$location.$$url`, which is passed through `decodeURIComponent`.

IMO, we should address the issue at its core and always use the same encoding/decoding when setting `lastBrowserUrl` (even if that will be a larger undertaking).

@dmartres, would you like to take a stab at it?

**Comment by dmartres** [comment]
You're Right, but now I can't work on that :( . Should I report this as an issue?
Perhaps someone can take a look based on this discussion.

**Comment by gkalpak** [comment]
Yes, please :smiley:

**Comment by gkalpak** [comment]
Thx for opening the issue. Closing this.

**Pull request closed without merging**
