### PR TITLE
Fix call angular.isUndefined in $cacheFactory doc

### PR DESCRIPTION
**Pull request by idoo**

### CODE REVIEW

**Comment by idoo** [comment]
@googlebot I signed it!

**Comment by Narretz** [comment]
These functions are usually available without `angular` while in the main angular closure. Did you experience them being undefined?

**Comment by Narretz** [comment]
Oh I see now it's in the docs. Never mind my comment then.

**Comment by gkalpak** [comment]
@Narretz, the code belongs to an example (in the docs), so it **is** needed.

**Comment by idoo** [comment]
@gkalpak it's not working in current version
https://docs.angularjs.org/api/ng/service/$cacheFactory

**Comment by Narretz** [comment]
Thx @gkalpak. Would also be nice to backport this to 1.4.

**Comment by Narretz** [comment]
@idoo You have to give Travis about 20 minutes to complete the tests etc. Only then is the site updated.

**Comment by gkalpak** [comment]
Backported to `v1.4.x` as 808f984.

**Pull request closed without merging**
