### PR TITLE
chore(i18n): add samoan locale

### PR DESCRIPTION
**Pull request by DrewShirts**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Chore: This PR adds the Samoan locale file for ngLocale.

**What is the current behavior? (You can also link to an open issue here)**
There currently is not a locale file for Samoan in ngLocale.
https://github.com/angular/angular.js/issues/7246

**What is the new behavior (if this is a feature change)?**
This adds the ability to translate content to Samoan.

**Does this PR introduce a breaking change?**
No.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our [guidelines](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits)
- [ ] Fix/Feature: [Docs](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#documentation) have been added/updated
- [ ] Fix/Feature: Tests have been added; existing tests pass
**Other information**:
No tests are available: See angular.js issue 7246: https://github.com/angular/angular.js/issues/7246
This was copied and then adapted from angular/bower-angular-i18n (originally committed by @spiffy2man: https://github.com/angular/bower-angular-i18n/pull/26).

### CODE REVIEW

**Comment by DrewShirts** [comment]
I signed the cla.

**Comment by Narretz** [comment]
Thanks for the PR. However since we are in Long Term Stability mode we are not going to add new locales to AngularJS.

**Comment by DrewShirts** [comment]
> Thanks for the PR. However since we are in Long Term Stability mode we are not going to add new locales to AngularJS.

@Narretz, I can understand that. How long will this have to wait until we can add the Samoan locale to angular.js? Can this be scheduled for when it will be an approvable PR?

**Comment by Narretz** [comment]
Sorry if I wasn't clear, but feature development for AngularJS is completely over. We advise everyone to use the new Angular: https://angular.io/
However, with i18n you can simply take the Samoan ngLocale module you created and add it to your application without it being in an official release.

**Comment by DrewShirts** [comment]
> Sorry if I wasn't clear, but feature development for AngularJS is completely over. We advise everyone to use the new Angular: https://angular.io/
> However, with i18n you can simply take the Samoan ngLocale module you created and add it to your application without it being in an official release.

Sounds good. Will do.

**Pull request closed without merging**
