### PR TITLE
Updated to danish standards

### PR DESCRIPTION
**Pull request by Squazz**

### CODE REVIEW

**Comment by Squazz** [comment]
I signed it!

**Comment by lgalfaso** [comment]
Please check https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#-found-an-issue under "Localization Issue"

**Comment by Squazz** [comment]
@lgalfaso thanks for the link. An edit have been requested at the right place

**Comment by lgalfaso** [comment]
@Squazz once the change goes into Google closure, feel free to open a new issue to generate the locale files once again.

**Comment by Squazz** [comment]
@lgalfaso I will try to, but I'm sure I know how to :P

**Comment by lgalfaso** [comment]
if you just open an issue with "Please regenerate the locale to see the changes from XX reflected", is good enough. Someone will recreate the files

**Comment by Squazz** [comment]
@lgalfaso ok, thanks man! :+1:

**Pull request closed without merging**
