### PR TITLE
docs(input[radio]): explain what happens with same name on multiple inputs

### LINKED ISSUE #15009: ng-if around a single radio button removes the entire ngModelController from the formController
Currently, when wrapping a single radio button input inside a ng-if, and when the ng-if expression evaluates to "false", the ngModelController is removed entirely from the formController.

Plunker:
https://plnkr.co/edit/6KwTDlydGdC1VHtLoszg?p=preview

A workaround is to use ng-show, but sometimes ng-if is preferable, and should be able to work as well. The current situation also baffles developers as it is non-trivial.

Angular version: 1.5.7

### PR DESCRIPTION
**Pull request by gkalpak**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Docs update.

**Does this PR introduce a breaking change?**
No

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our [guidelines](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits)
- [ ] ~~Fix/Feature: [Docs](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#documentation) have been added/updated~~
- [ ] ~~Fix/Feature: Tests have been added; existing tests pass~~

**Other information**:
Closes #15009.

### CODE REVIEW

**Comment by gkalpak** [comment]
This is what it looks like:
input-radio-docs

**Comment by Narretz** [comment]
2 things we should note:

- Since AngularJS uses ngModel to set the radio state, and not the name, the radio state is not constrained to the parent form, but to the scope the ngModel is in.
- You can still give the radios in a group the same name, but if you need to access each ngModelController individually, you cannot do it

**Comment by gkalpak** [comment]
I do mention that the state of the radion button is determined based on the model data. I am afraid that saying something like "the radio state is not constrained to the parent form, but to the scope the ngModel is in" would sound unnecessarily complicated.

I will expand on what happens when using the same name for multiple radios.

**Review by Narretz — APPROVED** [review]
Ok. It's implicit that when the model changes the checked status, it's not restricted to the parent form.

**Review by petebacondarwin — APPROVED** [review]

**Pull request closed without merging**
