### PR TITLE
test(ngOptions): fix flaky test on Firefox 54+ and Safari 9

### PR DESCRIPTION
**Pull request by gkalpak**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Reduce (remove?) test flaky-ness.

**What is the current behavior? (You can also link to an open issue here)**
A particular `ngOptions` test is very flaky on Firefox 54+ (possibly due to a (buggy?) optimization).

**What is the new behavior (if this is a feature change)?**
The test is more reliable on all browsers.

**Does this PR introduce a breaking change?**
No.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] ~~Docs have been added / updated (for bug fixes / features)~~

### CODE REVIEW

**Comment by gkalpak** [comment]
In case anyone is wondering, this is what caused the issue (afaict):

- On Firefox and Chrome (didn't check other browsers), the `selected` property is implemented as a getter/setter property on the `HTMLOptionElement` prototype (not the `<option>` element itself).
- We were defining a getter/setter `selected` property on the `<option>` elements and spying on it.
- It seems that in certain cases (possibly when a specific optimization was triggered), Firefox would ignore our getter/setter spy and use the getter/setter on the prototype (potentially only for `get` operations).

**Comment by Narretz** [comment]
As discussed, I think we should merge this and possibly skip the test altogether on Safari where it also sometimes sporadically fails.

**Review by Narretz — APPROVED** [review]

**Comment by Narretz** [comment]
Let's merge it as is, and see if there are Safari failures later

**Comment by gkalpak** [comment]
I disabled the test on Safari 9. Once Travis is green, I'll merge it.

**Comment by Narretz** [comment]
There still time to revert!

**Comment by gkalpak** [comment]
Too late, I squashed the commits 😛

**Pull request closed without merging**
