### PR TITLE
docs(error/nobase): tag base wasn't displayed properly

### PR DESCRIPTION
**Pull request by saamed**
Replaced < with &lt and > with &gt;

### CODE REVIEW

**Comment by saamed** [comment]
I signed it!

**Comment by petebacondarwin** [comment]
It looks like it is rendering properly for me...

screen shot 2016-02-08 at 02 15 25

You should not need to escape HTML characters in code blocks.

**Comment by Narretz** [comment]
@petebacondarwin In the code block above the Description, there's a gap where `<base>` should be. I tried to fix this before. Let me see if I still have a branch with a fix.

**Comment by petebacondarwin** [comment]
OK but that is not the problem that this PR is trying to fix

**Comment by Narretz** [comment]
See https://github.com/angular/angular.js/pull/14033

**Pull request closed without merging**
