### PR TITLE
Dynamic option can hold empty value now so you don't have to initially p...

### PR DESCRIPTION
**Pull request by slavede**
...ut it inside select (issue #11470)

### CODE REVIEW

**Comment by slavede** [comment]
I signed it!

**Comment by petebacondarwin** [comment]
@slavede - thanks for this PR. It looks good for the scenario of adding in a dynamic empty element. Isn't it great when a fix can be so simple.

I have two concerns that we need to resolve:

* what happens if there was already a static empty option when a dynamic empty option appears?
* what happens when a dynamic empty element is removed?
  * in the case that there was already a static empty option
  * in the case that there was no empty option already

**Comment by slavede** [comment]
Sorry, I was/am kinda busy this week. Let me think about this over the weekend and come up with some suggestion

**Comment by petebacondarwin** [comment]
Great! Here is the link you need https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit

**Comment by slavede** [comment]
1) that really shouldn't matter because self.emptyOptions is only used in checking if ngmodel is set to unknown value so we can set it to empty:

    if (isUndefined(value) && self.emptyOption) {
        self.removeUnknownOption();
        $element.val('');
      } else {
        self.renderUnknownOption(value);
      }
2) tbh, currently self.emptyOption is not even checked in removeOption and if you now remove empty option, self.emptyOption would remain set so that's I believe another bug we could open/fix

**Comment by slavede** [comment]
@petebacondarwin what do you think?

**Comment by petebacondarwin** [comment]
@slavede thanks for this. I tweaked the tests, added the bit about removing the empty option and then squashed the commits.

**Pull request closed without merging**
