### PR TITLE
fix(compare-master-to-stable.js): include current version in comparisons

### LINKED ISSUE #10816: compare-master-to-stable.js script doesn't work properly after switch to 1.4
The output says that it compares master with 1.2.x (instead of 1.3.x). To be investigated / fixed.

### PR DESCRIPTION
**Pull request by rphv**
Change to include current prerelease versions in comparisons

Closes #10816

### CODE REVIEW

**Comment by pkozlowski-opensource** [comment]
@rphv you are fast :-) Thnx for the reactivity!

**Comment by rphv** [comment]
restart Travis-CI build

**Comment by rphv** [comment]
restart Travis-CI build

**Comment by rphv** [comment]
Build fails with errors like:

`ScriptTimeoutError: Timed out awaiting response to command "switchToFrame" after 30000 ms (WARNING: The server did not provide any stacktrace information)`

Restarting.

**Comment by pkozlowski-opensource** [comment]
@rphv don't worry about the build failures - we've got some issues with automated testing on TravisCI lattly...

**Comment by petebacondarwin** [comment]
This was actually fix already in https://github.com/angular/angular.js/commit/452d1cd66e8109fd5d19189207ac4be16ad827b5

**Pull request closed without merging**
