### PR TITLE
user formatNumber from ExternalAPI

### PR DESCRIPTION
**Pull request by unspike**
allow to use 'formatNumber' function from ExternalAPI
to make more effective filters and directives with apps

<pre>
    function publishExternalAPI(angular) {
+           'formatNumber': formatNumber,
        });
</pre>

### CODE REVIEW

**Comment by pkozlowski-opensource** [comment]
@AreYouSiries there is something wrong with your PR, I'm not sure what is the code change you wanted to propose...

**Comment by AreYouSiries** [comment]
my mistake i guess, my first pull request.
I want to offer to make a function 'formatNumber' in a public  accessible.

<pre>
	function publishExternalAPI(angular) {
		extend(angular, {
			'bootstrap': bootstrap,
			'copy': copy,
			'extend': extend,
			'equals': equals,
			'element': jqLite,
			'forEach': forEach,
			'injector': createInjector,
			'noop': noop,
			'bind': bind,
			'toJson': toJson,
			'fromJson': fromJson,
			'identity': identity,
			'isUndefined': isUndefined,
			'isDefined': isDefined,
			'isString': isString,
			'isFunction': isFunction,
			'isObject': isObject,
			'isNumber': isNumber,
			'isElement': isElement,
			'isArray': isArray,
			'version': version,
			'isDate': isDate,
			'lowercase': lowercase,
			'uppercase': uppercase,
			'callbacks': { counter: 0 },
			'getTestability': getTestability,
			'$$minErr': minErr,
			'$$csp': csp,
			'formatNumber': formatNumber,
			'reloadWithDebugInfo': reloadWithDebugInfo
		});
</pre>

**Comment by pkozlowski-opensource** [comment]
@AreYouSiries you'vee started your commit off the 1.3.x branch and sent the PR against the master branch - this is why things got messed up. 

Regarding the proposed change - we are trying to limit the public API surface of various helpers so it is unlikely that it would get merged...

**Comment by AreYouSiries** [comment]
but 'formatNumber' function really helpful for different filters and customising i guess

**Pull request closed without merging**
