### PR TITLE
docs($rootScope.Scope): fixed typo on $watch docs

### PR DESCRIPTION
**Pull request by witcold**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

**What is the current behavior? (You can also link to an open issue here)**

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change?**

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**Other information**:

### CODE REVIEW

**Comment by witcold** [comment]
I signed it!

**Comment by frederikprijck** [comment]
I don't think that was a typo.

> This should not be used to watch for changes in objects that are or contain File objects due to limitations with angular.copy.

still sounds correct, whereas:

> This should not be used to watch for changes in objects that are or contain File objects due to limitations with angular.copy.

does not.

I guess it's ment to say that you should use it on both
- File Objects
- Objects that contain File 

Which does need the `or`.

**Comment by witcold** [comment]
Thanks, now it's clear to me. Yeah, the best solution here is rephrasing, may be with "or contain" in brackets.

**Comment by gkalpak** [comment]
> rephrasing, may be with "or contain" in brackets.

SGTM :+1:

**Comment by Narretz** [comment]
@witcold Do you still want to update this PR?

**Pull request closed without merging**
