### PR TITLE
Add sudo before apt-get

### PR DESCRIPTION
**Pull request by sssemil**
docs

### CODE REVIEW

**Comment by sssemil** [comment]
I signed it!

**Comment by Narretz** [comment]
Since I'm not using Linux / MacOs I can't say if this is "correct". I do believe that sudo should only be used when appropriate, and not generally. I think this is then out of scope for the docs, since we cannot know if someone needs sudo or not.

**Comment by gkalpak** [comment]
I'm (mainly) on Windows too, but I think `apt-get install` does indeed need `sudo` (except maybe for very specific, uncommon setups).

That said, we are about to merge #14416, which will overwrite this change anyway.
@sssemil, if you are confident `sudo` is necessary, please check back in a few days and submit a new PR against the updated tutorial.

Thx !

**Comment by sssemil** [comment]
Cool, I'm sure that apt-get requires sudo, so I'll reopen it later. Cheers.

**Pull request closed without merging**
