### PR TITLE
Modified CHANGELOG.md

### PR DESCRIPTION
**Pull request by eeeqxxtg**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
    Docs update

**What is the current behavior? (You can also link to an open issue here)**
```
  $sceDelegateProvider.resourceUrlWhite**L**ist([    (#1159)
 ```  

**What is the new behavior (if this is a feature change)?**
```
  $sceDelegateProvider.resourceUrlWhite**l**ist([    (#1159)
 ```  

**Does this PR introduce a breaking change?**
Dose not

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**Other information**:

### CODE REVIEW

**Comment by gkalpak** [comment]
Good catch!
You need to sign the CLA though, before we can merge this.

**Comment by eeeqxxtg** [comment]
I signed it

**Comment by eeeqxxtg** [comment]
I changed my primary email of github

**Comment by gkalpak** [comment]
Apparently, it didn't work for googlebot 😕 
Maybe you could try to open a new PR.

**Pull request closed without merging**
