### PR TITLE
chore(docs.angularjs.org): allow robots in partials/ but prevent inde…

### PR DESCRIPTION
**Pull request by Narretz**
…xing

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

**What is the current behavior? (You can also link to an open issue here)**

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change?**

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our [guidelines](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits)
- [ ] Fix/Feature: [Docs](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#documentation) have been added/updated
- [ ] Fix/Feature: Tests have been added; existing tests pass

**Other information**:

### CODE REVIEW

**Review by gkalpak — APPROVED** [review]
LGTM
(Not sure what happened with Travis. The job was cancelled. Did you cancel it?)

**Comment by Narretz** [comment]
Yeah I changed the commit message and pushed it twice again and cancelles these jobs. The initial one is green

**Comment by mgol** [comment]
@narretz In such cases I wouldn’t cancel the last job as it’s then confusing during the review.

**Review by mgol — APPROVED** [review]

**Comment by Narretz** [comment]
@mgol You are right, I cancelled the wrong builds - sorry

**Pull request merged**
