### PR TITLE
chore(gruntfile): check the node version before starting

### PR DESCRIPTION
**Pull request by petebacondarwin**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

**What is the current behavior? (You can also link to an open issue here)**

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change?**

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Other information**:

We specify the node version that is required to run the build in the `.nvmrc`
file. So let's check that the current node version satisfies this and report
a helpful message if it is not.

### CODE REVIEW

**Comment by gkalpak** [comment]
How about printing a warning instead? It might be too restrictive and the version might not matter for certain tasks.

**Comment by mgol** [comment]
I like it. I have sth like that in build systems of most of my non-trivial projects.

@gkalpak A warning will just be ignored in lots of output... If we want to make it a soft warning, I'd use [inquirer](https://www.npmjs.com/package/inquirer) to ask the user if they really want to run the task with an unsupported version.

**Comment by mgol** [comment]
@petebacondarwin Note, though, that when we switch to Node 6 we might want to try using ES6 in our Node.js code. In that case this check would not even run in older Nodes due to parse errors.

The workaround for that would be to have `Gruntfile.js` have just this check & then require another file that would contain the "true" Gruntfile written in ES6.

**Comment by petebacondarwin** [comment]
@gkalpak - generally I just run `nvm use` whenever I change folder to a new project, which just fixes up the version for me with very little overhead.

**Comment by mgol** [comment]
@petebacondarwin I have a script that does it for me automatically every time I switch to a different directory: https://github.com/creationix/nvm#calling-nvm-use-automatically-in-a-directory-with-a-nvmrc-file

I don't even have to remember about `nvm use`. :)

**Comment by gkalpak** [comment]
So, are you saying that you don't care about the poor souls that can't or won't use `nvm use` or zsh hooks? Fair enough :smiley:

LGTM

**Comment by thorn0** [comment]
@petebacondarwin FYI `nvm` doesn't work on Windows.

**Comment by petebacondarwin** [comment]
This version - https://github.com/coreybutler/nvm-windows - works for me on Windows...

**Comment by gkalpak** [comment]
Me too :smiley:

**Pull request merged**
