### PR TITLE
Update step_03.ngdoc with corrected grammar and usage

### PR DESCRIPTION
**Pull request by atenhar**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
docs edits.
Purely grammar and usage edits.

**What is the current behavior? (You can also link to an open issue here)**

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change?**

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Other information**:

Some more usage and grammar edits.

### CODE REVIEW

**Comment by atenhar** [comment]
I signed the CLA!

**Comment by gkalpak** [comment]
Thx for the fixes :+1:

I kept the spaces around the em&mdash;dash, since I think it makes the text more readable, is consistent with the rest of the tutorial and is matter of style (from what I understand).

**Comment by atenhar** [comment]
Of course!

I'm planning on working through the rest of the tutorial material, because
I'm trying to learn Angular, and will want to make other grammatical and
usage edits. Can you let me know if there is anything I should change or
keep in mind when making edits and pull requests? I've never used github
before.

Thanks,
Andrew

On Tue, Jun 28, 2016 at 3:47 AM, Georgios Kalpakas <notifications@github.com
> wrote:

> Thx for the fixes 👍
>
> I kept the spaces around the em—dash, since I think it makes the text more
> readable, is consistent with the rest of the tutorial and is matter of
> style (from what I understand).
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/angular/angular.js/pull/14834#issuecomment-228989043>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ATPWtEDYHF0ypeYRPiDj94IZzu1_QAILks5qQN-_gaJpZM4I_jRh>
> .
>



-- 
*sent from internet*

**Comment by gkalpak** [comment]
Awesome!

A good tip for pull requests is to keep them small and focused. E.g. having one PR per step is better than having one giant PR for the whole tutorial (unless there are very few modifications per step).

If you want to go the extra mile, there are some conventions we follow regarding our [commit messages][1] :smiley:

Thx and have fun learning Angular!

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit

**Pull request closed without merging**
