### PR TITLE
docs(guide/External Resources): Added a course

### PR DESCRIPTION
**Pull request by packtpartner**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

feature

**What is the current behavior? (You can also link to an open issue here)**

linked to course

**What is the new behavior (if this is a feature change)?**

linked to course

**Does this PR introduce a breaking change?**

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Other information**:

Added a new course under Paid Onsite

### CODE REVIEW

**Comment by petebacondarwin** [comment]
This course is actually "paid online" not "paid onsite". But I will fix up and merge.

**Comment by packtpartner** [comment]
Sorry for my ignorance. Thanks @petebacondarwin

**Comment by gkalpak** [comment]
@packtpartner, @petebacondarwin fixed that while merging - you don't need to do anything :smile:

**Comment by packtpartner** [comment]
@gkalpak thanks a lot. Will it show on https://docs.angularjs.org/guide/external-resources anytime soon?

**Comment by gkalpak** [comment]
@packtpartner, it should be visible already.

**Comment by petebacondarwin** [comment]
It is now that our CI server got back up and running

**Comment by packtpartner** [comment]
Sorry for the trouble, but I am still unable to see it featured on https://docs.angularjs.org/guide/external-resources @petebacondarwin @gkalpak

**Comment by gkalpak** [comment]
Hm...it is listed (as `Packt`) under **Courses > Paid online**. (You had originally added it under **Courses > Paid on-site**).

But looking at it, it looks morw like a book, right?

**Comment by petebacondarwin** [comment]
It is an online course.

**Comment by petebacondarwin** [comment]
It is just packaged as an ebook

**Comment by packtpartner** [comment]
Thanks for all your help @petebacondarwin @gkalpak :)

**Pull request closed without merging**
