### PR TITLE
Providing an example of customizing actions on $resource factory.

### PR DESCRIPTION
**Pull request by yilinglu**

### CODE REVIEW

**Comment by gkalpak** [comment]
Interesting (I had never noticed that).
I think we should properly document `$resourceProvider` instead.

**Comment by gkalpak** [comment]
@yilinglu, would you be interested in submitting a PR, properly documenting the `$resourceProvider` ?

--
By _"properly documenting"_, I mean adding ngdoc comments (to the provider and its methods/properties), so that `$resourceProvider` appears in the docs as a separate entry (under `ngResource -> provider`).
To get an idea of what I am talking about, you can take a look at any other documented provider (e.g. [$routeProvider][1]).

[1]: https://github.com/angular/angular.js/blob/master/src/ngRoute/route.js#L23

**Comment by yilinglu** [comment]
OK. I will write it up and submit a PR in the next couple of days.

**Comment by gkalpak** [comment]
Awesome, thx !
Feel free to ping me if you need anything (or if you want me to take a look when it's ready).

**Comment by yilinglu** [comment]
[PR submitted.] (https://github.com/angular/angular.js/pull/11910) Please review.
Thanks.

**Comment by gkalpak** [comment]
Closing in favor of #11910.

**Pull request closed without merging**
