### PR TITLE
chore(package.json): remove unused grunt-jasmine-node

### PR DESCRIPTION
**Pull request by thorn0**
At least, it looks unused.

### CODE REVIEW

**Comment by lgalfaso** [comment]
`npm run test-i18n` ?

**Comment by thorn0** [comment]
Does is use grunt?

**Comment by gkalpak** [comment]
`npm run test-i18n` is using `jasmine-node` directly ([package.json#L20-L21][1]).

[1]: https://github.com/angular/angular.js/blob/bd0915c4007dcc5b0cae6968598731117c510ffa/package.json#L20-L21

**Comment by Narretz** [comment]
If Travis passes, does that mean we can safely remove it?

**Comment by Narretz** [comment]
Do we need to update the shrinkwrap for this, too?

**Comment by gkalpak** [comment]
I think we do.

**Comment by thorn0** [comment]
done

**Pull request closed without merging**
