### PR TITLE
Fix #10259 (mouseenter in svg template in IE)

### LINKED ISSUE #10259: "ng-mouseenter" broken in SVG template in Internet Explorer 9-11
IE breaks on the line 3047

    if (!related || (related !== target && !target.contains(related))) {

SVG in IE has no "contains" method

example http://jsfiddle.net/4pe5pyn3/

Angular version - 1.3.4

### PR DESCRIPTION
**Pull request by askuzminov**
Fix of issue https://github.com/angular/angular.js/issues/10259

### CODE REVIEW

**Comment by ben-botto-bgi** [comment]
Will this bug be addressed in an upcoming release?  It's a pain to have to manually patch or pull in jQuery for a mouseenter bug.

**Comment by jacobpierce** [comment]
One workaround in [some use cases](https://developer.mozilla.org/en-US/docs/Web/Events/mouseenter) is to use `mouseover`/`mouseout` rather than `mouseenter`/`mouseleave`, e.g. this fiddle works in IE11 when changed to over/out: https://github.com/angular/angular.js/issues/10259

**Comment by petebacondarwin** [comment]
Moving to 1.4.x 
It also needs unit tests before it can be merged.

**Comment by petebacondarwin** [comment]
I have a test and an tidy up of this PR here: https://github.com/angular/angular.js/compare/master...petebacondarwin:issue-10259

**Pull request closed without merging**
