### PR TITLE
feat(q): Resolve any promise of array/hash input (q.any)

### PR DESCRIPTION
**Pull request by candreoliveira**
Issue reference: https://github.com/angular/angular.js/issues/11808

$q is a service inspired by Kris Kowal's Q.

It's usual in frontend applications to make requests to some APIs and based on (at least) a response continue processing the business logic.

For example: An e-commerce almost always needs to receive coupons, vouchers and/or freight discounts. A good architecture will separate responsabilities into distinct micro-services. However, the "perfect" ui could be a single input text. So, we'd use a single input to dispatch 3 requests (3 end-points: coupon, voucher and freight discount) and based on any answer apply the user discount. Hence, we need the ability to manage all requests into a single promise.

The Kris Kowal's Q has the method "any" and I think It's very helpful.

### CODE REVIEW

**Comment by realityking** [comment]
Since Angular is aligning it's promises with ES6, I think it would be better to name it after [`Promise.race`](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Promise/race).

**Comment by motin** [comment]
+1 on including this, albeit called $q.race() as per @realityking's suggestion

**Comment by twilczak** [comment]
I think this feature as implemented is fundamentally different than Promise.race, and probably shouldn't use that name. It don't see a native feature for this in ES6.

**Comment by ryanray** [comment]
+1

**Comment by jrencz** [comment]
Note that `.any` as implemented here has different semantics than `.race` as in the Spec.

`.race` will get rejected after the first one of the promises given to it gets rejected. `.all` will wait for all of them to get rejected.

This implementation cannot be named `.race`.

There's #12929 for race

**Comment by petebacondarwin** [comment]
We are going to implement `$q.race()` (because it is part of the ES6 Promise spec) and only document how one could implement one's one version of `any()` (because it is not part of the spec).

**Pull request closed without merging**
