### PR TITLE
fix(*): remove text-shadow from prettify theme

### PR DESCRIPTION
**Pull request by frederikprijck**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Styling improvement

**What is the current behavior? (You can also link to an open issue here)**
The styling on the AngularJS bits (tags, attributes, placeholders) in the code examples include a white colored text-shadow on a light blue background. This makes text difficult to read.

**What is the new behavior (if this is a feature change)?**
This commit removes this shadow to improve readability.

**Does this PR introduce a breaking change?**
No

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our [guidelines](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits)
- [ ] Fix/Feature: [Docs](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#documentation) have been added/updated
- [ ] Fix/Feature: Tests have been added; existing tests pass

**Other information**:
 #16495

### CODE REVIEW

**Comment by gkalpak** [comment]
Is this the right place to fix it? I thought the site was built off of https://github.com/angular/angularjs.org (in which case [this is the style][1] you would need to override).
Has that changed as part of the recent refactorings in hosting infrastructure, @Narretz?

[1]: https://github.com/angular/angularjs.org/blob/c346cbcabb55ebbb337b17dfb86dd191b58a264a/src/google-code-prettify/prettify.css#L29

**Comment by Narretz** [comment]
That's right, Angularjs.org is not built from this here repository.

**Comment by frederikprijck** [comment]
Oh that's confusing, the css file looks very alike. But I guess that's why I asked you how to be able to verify this change locally.

What's the css file in this repo used for ?

**Comment by gkalpak** [comment]
The `prettify.css` files are used for [google-code-prettify][1], which we use on both pages.

[1]: https://github.com/google/code-prettify

**Comment by frederikprijck** [comment]
@gkalpak Does the changes in this repo makes sense? To align both of them ?

**Comment by gkalpak** [comment]
I don't think we use light-blue, highlighted regions here.

**Pull request closed without merging**
