### PR TITLE
feat(ng): add directive for visible and invisible elements

### PR DESCRIPTION
**Pull request by jacobscarter**
when you need to preserve a hidden elements dom space ngVisible and ngInvisible will allow you to do so

### CODE REVIEW

**Comment by jacobscarter** [comment]
The `ngInvisibleDirective` undefined variable I will figure out, in regards to the error for `ngNonBindableDirective` being undefined, I did not create that directive or modify it, I don't know why that is throwing an error but ill look into it.

**Comment by petebacondarwin** [comment]
@jacobscarter - thanks for putting this PR together. I am afraid that we have had long debates about this directive in the past in #11115. We have chosen not to include it in the core. See https://github.com/angular/angular.js/issues/11115#issuecomment-76154055

**Comment by caitp** [comment]
You could totally publish it as a third party module, though, or maybe get it upstream into one of angular-ui's "utility" packages (I can't recall the names OTOH)

**Comment by jacobscarter** [comment]
@caitp @petebacondarwin thanks for the replies, it was a cool learning experience and thanks for the advice.

**Pull request closed without merging**
