### PR TITLE
fix(ngAnimate): ensure that "element" caintains html node

### PR DESCRIPTION
**Pull request by interstella-5555**
Ensure that "element" jqlite wrapper contains html node. It results in an error if it is defined but empty.

### CODE REVIEW

**Comment by Narretz** [comment]
Thanks for the PR. Can you please:
- show the bug / scenario / issue that is fixed by this change
- write a test that shows the problem

**Comment by kwypchlo** [comment]
Sure @Narretz, I will try to reproduce the problem in an isolated case, though I will need some days for that as it happened in my project at work.

**Comment by matsko** [comment]
+1 :)

**Comment by Narretz** [comment]
Closing because we have no demo of the problem :(

**Pull request closed without merging**
