### PR TITLE
fix($animate): invalid CSS class names should not break subsequent elements

### LINKED ISSUE #12674: ng-show is not working when ng-class is having array expression
ng-show is not working (angularjs version 1.4.4) when ng-class is having array expression

Here is the plnkr to demonstrate the issue. 

http://plnkr.co/edit/qNTsC8sWS7b1u76zvfbO?p=preview

### PR DESCRIPTION
**Pull request by petebacondarwin**
The postDigest handler was not being added if the first element in
to modify the CSS classes contained invalid CSS class names. This meant
that subsequent valid CSS class changes were not being handled since we
were not then adding the handler for those correct cases.

Closes #12674

### CODE REVIEW

**Comment by petebacondarwin** [comment]
Here is the Plunker showing the issue with the fixed version of Angular: http://plnkr.co/edit/Zux7ICpKvsh6oa25vlzr?p=preview

**Comment by petebacondarwin** [comment]
The diff looks more complicated that it is. I pulled two functions, `updateData` and `handleClassChanges`, from out of the `addRemoveClassesPostDigest` function. This means that we are not having to recreate them on every call and also makes the `addRemoveClassesPostDigest` easier to grok.

**Comment by Narretz** [comment]
Without the refactor, it would be easier to see what actually changed semantically, though ;)

**Comment by matsko** [comment]
LGTM. Excellent work.

**Comment by petebacondarwin** [comment]
@Narrate you're right. I should have made two commits

**Comment by petebacondarwin** [comment]
Here is the plunker with the most recent fix: http://plnkr.co/edit/ppS7j623Wz4DifRRBjtu?p=preview

**Comment by petebacondarwin** [comment]
@Narretz - there I have broken the PR into two commits.

**Comment by Narretz** [comment]
@petebacondarwin I almost down dare to say it, but ... it's actually `refactor`, not `refact`.

**Comment by petebacondarwin** [comment]
Doh!

**Comment by petebacondarwin** [comment]
@Narretz shouldn't you be asleep?

**Pull request closed without merging**
