### PR TITLE
docs(changelog): add deprecation notice

### PR DESCRIPTION
**Pull request by wesleycho**
- Add deprecation notice for `angular.lowercase` and `angular.uppercase`

This should address #14316

### CODE REVIEW

**Comment by Narretz** [comment]
So we did something strange with this. We deprecated the methods and removed their docs, which I think only adds to the confusion. Imo, ww should also re-add the docs, but give the methods the `@deprecated` tag

**Comment by petebacondarwin** [comment]
Can we add the deprecation and removal versions to the deprecation notice?

**Comment by Narretz** [comment]
I can do that. to be removed in 1.7?

**Comment by petebacondarwin** [comment]
Yep - although I think we will need to leave the functions in-place internally.

**Comment by mgol** [comment]
@petebacondarwin as long as they're not exposed, it doesn't matter. Once we no longer need them, we can remove them then even in a patch release.

**Comment by Narretz** [comment]
Yes, we use them internally. So we should remove them from the public angular object in 1.7

**Pull request closed without merging**
