### PR TITLE
Docs ngmessageformat examples

### PR DESCRIPTION
**Pull request by Narretz**
- add examples for gender and gender + plural to the ngMessageFormat docs
- move the docs to the ngMessageFormat module namespace, as $$messageFormat is a private service

### CODE REVIEW

**Comment by Narretz** [comment]
Did you fix the build errors?

**Comment by petebacondarwin** [comment]
It build fine locally.... oops

**Comment by petebacondarwin** [comment]
Is it the e2e tests?

**Comment by Narretz** [comment]
One was in style checks but that was probably fixed by building locally.
The others were docs. We'll see

**Comment by petebacondarwin** [comment]
I have pushed the ci-check fix

**Comment by petebacondarwin** [comment]
I will fix up the e2e tests now - sorry

**Pull request closed without merging**
