### PR TITLE
fix issue 12699: Context hierachy is not destroyed within a destroyed…

### PR DESCRIPTION
**Pull request by yoann-antoviaque**
… context, making memory leaks worse

### CODE REVIEW

**Comment by yoann-antoviaque** [comment]
I signed it!

**Comment by lgalfaso** [comment]
Would it be possible to see something that shows that this makes the GC any better?

**Comment by yoann-antoviaque** [comment]
I refactored the code to prevent changing the order '$destroyed' is broadcasted and clarify what is done: just remove links between each scope of the destroyed tree, preventing leaking the whole tree when someone keeps a reference on a child.

this helps in the application i am working on which has some memory leaks:
- each leak retains less memory
- it is easier to find the leak origin in a memory dump as there is no more references between destroyed contexts and therefore less retainer objects to go through

**Comment by jbedard** [comment]
Note that this could hurt performance, traversing an entire scope tree just in case an app has a memory leak...

**Comment by yoann-antoviaque** [comment]
Well, if i'm not mistaken we already traverse the whole tree when broadcasting $destroyed without performance issue.
It does not add complexity (while it's true that we add a small overhead on destroy).

**Comment by jbedard** [comment]
Event broadcasting only traverses branches which have a listener for that event: https://github.com/angular/angular.js/blob/681affef591273615e4505811eec663d0c0d1bb4/src/ng/rootScope.js#L1273

**Comment by yoann-antoviaque** [comment]
The pointed line is difficult to understand (thanks for the "insanity warning" ;)) and I will trust you on this.
There is added complexity but I have not found it problematic in my relatively complex case

**Comment by dcherman** [comment]
Copying a comment from the issue:

There should be no logical changes here. In both cases, you're severing the path to the GC roots, so the scope and all descendants should immediately become eligible for GC ( assuming nothing leaked in descendant scopes ).

IMO, it seems like the solution here is to not have memory leaks in your code, or fix them if they're present.

**Comment by Narretz** [comment]
Based on the lack of a good test for this, and the skeptical comments here and the comments in the issue, I'm going to close this. A change that touches such hot code should be really bulletproof, and this it is not.

**Pull request closed without merging**
