### PR TITLE
docs(misc-core): Add `undefined` as in/outputs of to/fromJson

### PR DESCRIPTION
**Pull request by wesalvaro**
Request Type: docs

Component(s): misc-core

Impact: small

Complexity: small

Detailed Description:
It is acceptable to pass and possible to receive `undefined` when using the `angular.toJson` and `angular.fromJson` methods.

### CODE REVIEW

**Comment by lgalfaso** [comment]
Hi, this might be a little bit personal, but instead of saying that you can pass `undefined` I would say that the parameter is optional. One way or another, if we are going to relax this, then we need some tests

**Comment by wesalvaro** [comment]
I don't think I would change it to an optional parameter. If you call it without an argument, nothing will ever happen; that's the wrong way to call it. However, you can certainly pass in `undefined`, in which case you'll get `undefined` back. There are a variety of scenarios where that would be reasonable. I'll add some tests if this will be merged, no problem.

**Comment by lgalfaso** [comment]
> I don't think I would change it to an optional parameter. If you call it without an argument, nothing will ever happen

that is fair

> I'll add some tests if this will be merged, no problem.

sounds good

**Comment by wesalvaro** [comment]
Added test for `fromJson`, there was already a test in place for `toJson`.

**Comment by mprobst** [comment]
YMMV, but I'd rather consider this a bug in the implementation - there's no point in calling the method with an undefined argument, as nothing is going to happen. So the user code calling you is most certainly wrong in some way (it's most likely expecting to parse some JSON).

So the best behaviour would be to fail early instead of silently trucking along.

**Comment by wesalvaro** [comment]
Good point, Martin. This should be turned into a bug that is fixed.

After all, JSON.parse(undefined) is a SyntaxError.

**Pull request closed without merging**
