### PR TITLE
docs(guide/External Resources): Added books and videos

### PR DESCRIPTION
**Pull request by packtpartner**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

feature

**What is the current behavior? (You can also link to an open issue here)**

linked to book page

**What is the new behavior (if this is a feature change)?**

linked to book page

**Does this PR introduce a breaking change?**

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Other information**:

Added 3 books and 3 videos

### CODE REVIEW

**Comment by packtpartner** [comment]
I signed the CLA

**Comment by Narretz** [comment]
Hi, materials that concern Angular 2 should be in the Angular 2 documentation. This repo is only for Angular 1.

**Comment by packtpartner** [comment]
Can you direct me to the Angular 2 documentation?

**Comment by Narretz** [comment]
Repo: https://github.com/angular/angular: docs page: https://angular.io/docs/ts/latest/

But I'm not sure if they have a section for external resources yet

**Comment by packtpartner** [comment]
Thanks @Narretz 
Any idea how can I edit the doc page (https://angular.io/resources) or if there is anyone to contact?

**Comment by gkalpak** [comment]
@packtpartner, the repo for angular.io is https://github.com/angular/angular.io.

**Pull request closed without merging**
