### PR TITLE
docs : update unit-testing-component-controllers

### PR DESCRIPTION
**Pull request by musclor**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

docs update

**What is the current behavior? (You can also link to an open issue here)**

https://github.com/angular/angular.js/issues/15968

**What is the new behavior (if this is a feature change)?**

Removes a useless spec.

**Does this PR introduce a breaking change?**

No

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**Other information**:

### CODE REVIEW

**Comment by frederikprijck** [comment]
@musclor Just a few more remarks with regards to your previous PR:

> Hello @frederikprijck
> 
> Finally I did not put any example because :
> 
> - I believe this part of the document is to demonstrate how to test a component controller easily with $componentController.
> - I wanted to provide the same spec as you but it will fail because the heroDetail component needs an external template...
> - I think testing a component and bindings requires a dedicated chapter.
> I suggest to complete this page https://docs.angularjs.org/guide/unit-testing if someone wants to add more examples.
> 
> I agree with you that the warning regarding $componentController should not be there. As far as I am concerned removing the useless spec is the most important for now.
> 
> Thank you for your review and comments :)

- I think the components page should explain how to test a component, or shouldn't explain testing at all. (I prefer the first one).
- I'm not sure what you mean.
- I'd say a small, dedicating testing section in the components section isn't bad either to start with?

Btw, any reason you closed the previous PR and created a new one? There's no need for that, you can simply update existing PR's by pushing new commits to your branch on which you created the PR!

**Comment by musclor** [comment]
Hi @frederikprijck 

As per the section 'Testing Directives With External Templates' of https://docs.angularjs.org/guide/unit-testing : if the test directory hierarchy differs from the application's, the test with $compile will fail because of an unexpected GET to retrieve the template from the server. 

I am sorry I closed the previous PR the reason is I only used the link on 'Improve this Doc' of Angular's website during the whole process. Thank you for your advice I will try to do like that next time.

Kind regards

**Comment by frederikprijck** [comment]
@musclor Afaik this does not mean you can't test it. It even explains what you need to do in order to ensure this is not going to be a problem. 

Anyhow, doesn't matter now.

**Comment by musclor** [comment]
You are refering to a sub section of 'Testing Directives' which uses $compile. Furthermore the directive example uses `template` instead of `templateUrl ` so there is no problem there.

The fact that the PR is merged does not mean we cannot do further improvements to the documentation ! ;p

Have a nice day

**Comment by frederikprijck** [comment]
@musclor I'm not sure what you're saying I'm refering to, but this is what I'm talking about: https://plnkr.co/edit/JUbGZuFZG2FPnNK18Kal?p=preview

The tests are green. Even tho I wouldn't use the `$templateCache` approach in the docs, the test itself doesn't change when switching between templateUrl and template.

**Comment by musclor** [comment]
@frederikprijck It's because you are using $templateCache (same as karma-ng-html2js-preprocessor).

If you comment it the templateUrl test will fail.

**Comment by frederikprijck** [comment]
@musclor I'm totally confused about what you're trying to point out.

If you want to have tests with templateUrl, you need to use any of those. Commenting that out or not using `karma-ng-html2js-preprocessor` is not how you need to write tests for components using a templateUrl.

This is getting to chatty, feel free to ping me over at https://gitter.im/angular/angular.js to discuss this offline.

**Comment by musclor** [comment]
Nothing more to add @frederikprijck 

`If you want to have tests with templateUrl, you need to use any of those.`

Exactly what I tried to say from the begining actually :)

**Pull request closed without merging**
