### PR TITLE
fix(ngResource): stop /. collapsing affecting parameter values

### PR DESCRIPTION
**Pull request by jowiho**
Request Type: bug

How to reproduce: Create a resource with URL '/myservice/:myparam'.
Call the resource with '.foo' as the value for myparam.
After resolving the parameter, ngResource incorrectly collapses the URL to '/myservice.foo', while in fact collapsing '/.format' to '.format' should only happen if '.foo' is part of the original resource URL. It should not affect parameter values like '.foo'.

Component(s): ngResource

Impact: small

Complexity: small

This issue is related to: 

**Detailed Description:**

The ngResource documentation states: "If the parameter before the suffix is empty, :resource_id in this case, then the /. will be collapsed down to a single .. If you need this sequence to appear and not collapse then you can escape it with /.."

But the resource.js implementation always replaces "./" instance with ".", regardless if these are caused by an empty parameter before the suffix. If the "." comes from the parameter value, ngResource should not touch it.

This pull request changes the ngResource behavior to match the documentation.

**Other Comments:**

### CODE REVIEW

**Comment by acotiuga** [comment]
Has this PR been abandoned? Could we have this merged soon?

**Comment by gumatias** [comment]
Are there any interests in merging this PR? It's been requested for 2 years so far. Would be nice to have this fix in. Thanks!

**Comment by gkalpak** [comment]
I am not a big fan of this change tbh.

1. First of all it is a breaking change that will benefit only few usecases.
2. It complicates things even more (it's less clear to me what will and what will not be collapsed after the change).
3. The current implementation of the fix will fail on certain edge cases. Two cases were it will fail to correctly collapse `/.` into `.` (off the top of my head):
    - `resource/:id.:suffix1:suffix2`, where `id --> null`
    - `resource/:id.:suffix`, where `id --> null`, `suffix --> 'spec.js'` and `suffix` has been replaced before `id`
4. It is already possible to support the usecase, e.g. by using appropriate functions as param-defaults (that will escape leading `.` for example). This requires a little more boilerplate, but we are talking about an uncommon usecase, so... 

Anyway, in order to consider this for merging we need to fix the edge cases, provide better docs and rebase against master.

<sub>But I am still not a fan :stuck_out_tongue: </sub>

**Comment by wangshan** [comment]
I'm hit by the same problem, I understand your concerns but it's a very annoying problem. It can't retrieve files like .gitignore which is quite common if you want to build something with github. I have to escape the dot on my frontend and then remove the escape in the backend before sending it to third party APIs.

**Comment by gkalpak** [comment]
I understand that. (Besides, I already said I am willing to consider this change.)
That said this PR is still not in a mergeable state (see my previous comment).

If anyone wants to step up and give it a shot, I'll be happy to help and review :smiley:

**Pull request closed without merging**
