### PR TITLE
docs($rootScope.Scope): clarify $watchGroup "oldValues" argument

### PR DESCRIPTION
**Pull request by Narretz**
This should help to prevent issues such as #8671, #12452, #16004.

Closes #12643

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
docs

**What is the current behavior? (You can also link to an open issue here)**
unclear docs

**What is the new behavior (if this is a feature change)?**
hopefully clearer docs :)

**Does this PR introduce a breaking change?**
No

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**Other information**:

### CODE REVIEW

**Review by gkalpak — COMMENTED** [review]
This does not apply to master any more (changed with #15854). Let's hold off on this, until we investigate the implications of that change.

**Comment by Narretz** [comment]
@gkalpak I think we should still merge this into 1.6.x Wdyt?

**Review by gkalpak — APPROVED** [review]
LGTM

**Comment by gkalpak** [comment]
I agree. It is good to go for 1.6.x.

**Pull request merged**
