### PR TITLE
fix(input): patched input cjk binding bug on IE11 browser. (angularjs v1.4.4)

### PR DESCRIPTION
**Pull request by powerumc**
Related #12659 

I append "if condition" code about ie11.

### CODE REVIEW

**Comment by Narretz** [comment]
Dupe of #12661

**Comment by Narretz** [comment]
Oops, didn't see this was for master. We usually backport these fixes from master without an extra PR.

**Comment by powerumc** [comment]
Do I have any problem for this pull request? :)

**Comment by Narretz** [comment]
We've recently fixed an issue with IE and compositionevents. It's possible that this PR was obsoleted by it. However, it's difficult to tell because there are no tests in this PR. Closing then. Sorry we never properly triaged this,

**Pull request closed without merging**
