### PR TITLE
docs(angular.extend): Added a simple Example to explain the simple us…

### PR DESCRIPTION
**Pull request by vsirohi**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

**What is the current behavior? (You can also link to an open issue here)**

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change?**

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**Other information**:

…age of the angular.extend.

I did not get much from the documentation here on how and where I will use extend. It was a lot better and very easy to understand with the help of a simple example. I have added the same example here. Might be helpful for others.

### CODE REVIEW

**Comment by vsirohi** [comment]
I did not get much from the documentation here on how and where I will use extend. It was a lot better and very easy to understand with the help of a simple example. I have added the same example here. Might be helpful for others.

**Comment by vsirohi** [comment]
I signed it!

**Comment by gkalpak** [comment]
@vsirohi, have you closed this intentionally ?

**Comment by Narretz** [comment]
Imo, this example is too opionated and doesn't make clear that extend will overwrite existing properties.

**Comment by Narretz** [comment]
I'm going to close this PR because we cannot merge it in its current state, as we are either waiting for more information, tests are missing, or required code changes haven't been made. 
Feel free to reopen this PR or open a new one if you have remdied the issues pointed out.

**Pull request closed without merging**
