### PR TITLE
fix(ngValue): set property in addition to attribute

### PR DESCRIPTION
**Pull request by Narretz**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
bug fix / minor feature

**What is the current behavior? (You can also link to an open issue here)**
ngValue cannot be used to bind to text inputs after they have been modified by the user

**What is the new behavior (if this is a feature change)?**
The above becomes possible

**Does this PR introduce a breaking change?**
Technically yes, but it's unlikely to affect anyone

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

### CODE REVIEW

**Comment by gkalpak** [comment]
LGTM
<sub>(Make sure to add `Closes #14031` in your commit message.)</sub>

**Comment by Narretz** [comment]
Looks good but breaks a ton of select tests ... :D

**Comment by gkalpak** [comment]
Travis obviously sees things different than me :stuck_out_tongue:

**Comment by Narretz** [comment]
Landed as https://github.com/angular/angular.js/commit/e6afca00c9061a3e13b570796ca3ab428c1723a1

**Comment by gkalpak** [comment]
What happened with Travis? What was causing the failures and was it fixed?

**Comment by Narretz** [comment]
I had previously changed the order of setting: if you do first attribute, then prop, the select tests fail. If you do it the other way round, everything works.

**Pull request closed without merging**
