### PR TITLE
docs(error/ctrlreg): Typo in the Controller Logic

### PR DESCRIPTION
**Pull request by ghost**
docs(error/ctrlreg): Typo in the Controller Logic

None of the current documentation causes for this error reference verifying the controller logic itself. However, this error could indicate that there is an error in the controller logic, similar to the code below (note the ill-placed semicolon on the first line):

```javascript
UserService.addNewGame(gameObject);
  .then(redirectToTeamSchedule);
```

Removing the semicolon from the first line of the controller logic alleviates the $controller:ctrlreg error.

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
docs update

**What is the current behavior? (You can also link to an open issue here)**
Error: $controller:ctrlreg -- A controller with this name is not registered.
Solutions in the current documentation do not cover all possible reasons for the error.

**What is the new behavior (if this is a feature change)?**
docs update with additional detail as to where a code error may exist if a $controller:ctrlreg error is triggered

**Does this PR introduce a breaking change?**
no

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**Other information**:

### CODE REVIEW

**Comment by frederikprijck** [comment]
Doesn't this depends on how you're registering your controllers ?

Tried a comparable plunkr and got another error message: https://plnkr.co/edit/2pT57JXV3AI5GEUdYRyu?p=preview

**Comment by gkalpak** [comment]
Saying "you might have a typo" is a very generic message and is not helpful imo. It is the same as saying "your JavaScript must be valid", but this should be considered a prerequisite.

Also, as @frederikprijck said, you should already get a different error because your JavaScript is invalid in the first place. But in any case, it is always possible to have a typo that leaves you with syntactically correct code, which behaves totally different that you expect. AngularJS should not try to be smart on what your error could be.

The error message says what is the problem as far as AngularJS is concerned (in this case the fact that the controller is not registered) and gives you a couple of hints on common causes (but definitely not an exhaustive list).

##
I am going to close this, because it doesn't add anything useful to the message.
But we appreciate your taking the time to submit a PR and would love to see more of this in the future :wink:

**Comment by danzera** [comment]
OK - Thanks for the feedback. The error message just seemed to be misleading, but I’m pretty new to Angular, and full-stack dev in general, so I can’t say I’m an expert on error verification and where the responsibility lies.

I must have been mistaken about where Angular ends and JS begins.

**Comment by gkalpak** [comment]
👍 
BTW, you might want to look into [eslint][1] :wink:

[1]: http://eslint.org/

**Comment by danzera** [comment]
Thanks! I just switched over from Atom to VS Code last week and haven’t installed a linter yet. Not sure how I’ve gotten by this long without one. Guess it’s just forced me to pay closer attention, but can’t catch ‘em all sometimes.

Sorry for wasting your time.

**Pull request closed without merging**
