### PR TITLE
Interpoilate directive controller name

### PR DESCRIPTION
**Pull request by karaxuna**
In directive `xDir` directive if you have:

``` javascript
restrict: 'E',
scope: true,
controller: '@',
name: 'component',
```

Then you shall be able to pass controller name dynamically, like:

``` html
<x-dir component="{{'a' + 'b'}}"></x-dir>
```

This way I'll be able to use `ab` controller in directive.

### CODE REVIEW

**Comment by petebacondarwin** [comment]
What is the use case for this level of dynamism?

**Comment by karaxuna** [comment]
I was trying to create universal form input. For example:

    <x-input component="textbox"></x-input>

So it needs dynamic template that angular already has and all the directive options to be dynamic. I ended up with manually building new tag with same attributes in compile and replacing current one.

**Comment by petebacondarwin** [comment]
How does allowing the name of the controller to be defined as an interpolation on the template help with this?

**Comment by Narretz** [comment]
Closing due to lack of feedback.

**Comment by hieutranagi47** [comment]
Hi,

I actually face the same issue on AngularJS#1.7.2 because I would like to reuse a directive container, but content of the directive can be changed by another template in need:

```
<ng-transclude></ng-transclude>
<section class="tooltip-container">
    <div class="container-content">
        <ng-template ng-if="!template">
            <article class="tooltip-header" ng-if="header">
                <div class="tooltip-title">
                    <h5 class="tooltip-text">{{header ? header : 'Tooltip header'}}</h5>
                </div>
                <div class="tooltip-action" ng-if="actionControl">
                    <span class="tooltip-action-container">
                        <i class="icon icon-check"></i>
                    </span>
                    <span class="tooltip-action-container" ng-click="close()">
                        <i class="icon icon-close"></i>
                    </span>
                </div>
            </article>
            <article class="tooltip-body">
                <div class="body-content">
                    <p>{{content ? content : ''}}</p>
                </div>
            </article>
            <article class="tooltip-footer"></article>
        </ng-template>
        <ng-template 
            ng-if="template" 
            ng-include="template" 
        ></ng-template>
    </div>
</section>
```

and directive:

```
return {
            link: link,
            restrict: 'AE',
            scope: {
                closeMe: '<',
                customClass: '@',
                actionControl: '<',
                header: '@',
                content: '@',
                template: '@'
            },
            controller: '@',
            name: 'ctrl',
            controllerAs: 'vm',
            transclude: true,
            templateUrl: './utilities/directives/tooltip-container/tooltip-container.html'
        };
```
The custom template:
```
<script id="file-actions.html" type="text/ng-template">
    <article class="tooltip-header">
        <div class="tooltip-title">
            <h5 class="tooltip-text">Header here</h5>
        </div>
        <div class="tooltip-action">
            <span class="tooltip-action-container">
                <i class="icon icon icon-check"></i>
            </span>
            <span class="tooltip-action-container" ng-click="close()">
                <i class="icon icon-close"></i>
            </span>
        </div>
    </article>
    <article class="tooltip-body">
        <div class="body-content">
            <p>This is my content</p>
            <a ng-click="vm.hackeMe()">Click me</a>
        </div>
    </article>
    <article class="tooltip-footer"></article>
</script>
```
and I use it:
```
<a class="clickable-item" 
                                    tooltip-container 
                                    custom-class="iloveu"
                                    header="Custom header"
                                    action-control="true"
                                    content="content here"
                                    template="file-actions.html"
                                    ctrl="FileAction"
                                >
                                    <i  class="icon" ></i>
                                </a>
```
Then I can create a FileAction controller to use for this directive similar:
```
angular
        .module('app')
        .controller('FileAction', FileAction);
        function FileAction() {
        var vm = this;

        vm.hackeMe = function() {
            console.log('Click me');
        };
    }
```
The issue is:
```
TypeError: Cannot read property 'prototype' of undefined
    at $controller (angular.js:11152)
    at setupControllers (angular.js:10215)
    at nodeLinkFn (angular.js:10007)
    at angular.js:10438
    at processQueue (angular.js:17396)
    at angular.js:17444
    at Scope.$digest (angular.js:18557)
    at Scope.$apply (angular.js:18945)
    at done (angular.js:12799)
    at completeRequest (angular.js:13056)
```

**Pull request closed without merging**
