### PR TITLE
fix(ngOptionsDirective): fix form pristine (use !equals function instead of !==  for issue 13211)

### PR DESCRIPTION
**Pull request by m-amr**
This pull request is related to Issue

https://github.com/angular/angular.js/issues/13211

it solves form $pristine and $dirty wrong values in case of multi select element 

prevoiusValue and nextValue are array for example

```
previousValue = [1,2]
nextValue = [1,2]
```

The are the same value but the === operator will return false because they are array
after some debugging i found that these lines cause the problem

```
if (!ngModelCtrl.$isEmpty(previousValue)) {
      var nextValue = selectCtrl.readValue();
      if (ngOptions.trackBy ? !equals(previousValue, nextValue) : previousValue !== nextValue) {
        ngModelCtrl.$setViewValue(nextValue);
        ngModelCtrl.$render();
      }
    }
```

what cause the problem is ngOptions.trackBy is undefined and 
(previousValue !== nextValue) i will be true becuase [1,2] !== [1,2]

### CODE REVIEW

**Comment by m-amr** [comment]
I signed it!

Date: Tue, 17 Nov 2015 17:13:55 -0800

**Comment by Narretz** [comment]
Thanks for the PR.I think we are very specifically only using equals with track by because of performance issues. But I think this is the right place to fix it. We should probably use equals also if the select is multiple.

**Comment by m-amr** [comment]
@Narretz 
Thanks for your feedback
I understand that angular is not always use equals function to compare the values
due to performance issue

i improved my solution 
now we should use equals function to compare values 
in case of  ngOptions.trackBy  or select is multiple (values are not primitive)
else we use equal operator to compare values (values are Primitive)

i added this lined to fix the problem

    var isNotPrimitive = ngOptions.trackBy || multiple;
    if (isNotPrimitive ? !equals(previousValue, nextValue) : previousValue !== nextValue) {
         ngModelCtrl.$setViewValue(nextValue);
         ngModelCtrl.$render();
     }
    
I think this fix the problem and won't cause performance Issue in case select is single value.

**Comment by Narretz** [comment]
Looks good. I'll merge it tomorrow.

**Pull request closed without merging**
