### PR TITLE
Remove expression sandbox

### PR DESCRIPTION
**Pull request by petebacondarwin**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

refactor

**What is the current behavior? (You can also link to an open issue here)**

The angular expression parsers attempts to sandbox the expressions to prevent unrestricted access to the global context.

**What is the new behavior (if this is a feature change)?**

The sandbox is removed, as it was not a real security feature.

**Does this PR introduce a breaking change?**

No

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**Other information**:

TODO:
- fill out the commit message
- more refactoring to remove unnecessary vars
- look into further performance improvements

### CODE REVIEW

**Comment by mgol** [comment]
Once it has a proper commit message and a couple of unused vars at the top of the file are removed (I only found some cached methods, that's all) I think it's ready to land. Performance improvements can be addressed in subsequent PRs/commits, I like that this one mostly cleanly removes stuff.

Other than that, LGTM.

**Comment by gkalpak** [comment]
The changes LGTM. Wrt commit message:

- [ ] According to [this well-respected resource][1], the type should be `refactor` :grin:
- [ ] Update with URL to blog post. <sub>(Just putting it here as a reminder.)</sub>

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#user-content-type

**Comment by thorn0** [comment]
Oh! In a project I work on, we have expressions that can be edited by users. They're used in dynamically composed templates. For us, it is a real security feature. :confused:

**Comment by petebacondarwin** [comment]
This is precisely why we are removing it. It is not a security feature.

**Comment by petebacondarwin** [comment]
@gkalpak - I always get that wrong :-(

**Pull request closed without merging**
