### PR TITLE
An example implementation of .directive `bind`

### PR DESCRIPTION
**Pull request by kentcdodds**
Example implementation to implement #10007

Based on [this comment](https://github.com/angular/angular.js/issues/10007#issuecomment-77763231) by @gautelo.

**Note** This PR was created using the github editor and is expected to be more instructional than anything. Not expected to be merged.

### CODE REVIEW

**Comment by kentcdodds** [comment]
By the way, do we not have a `reverseExtend` function already? Basically, that function is just like `angular.extend` but will not overwrite properties. If there's something already there then awesome.

**Comment by kentcdodds** [comment]
Note, I closed the PR because this is not expected to be merged. Just wanted to provide an example. This PR would amount to an api like so:

```javascript
ngModule.directive('myFoo', function() {
  return {
    bind: {
      bar: '='
    },
    template: '<pre ng-bind="myFoo.bar | json"></pre>'
  };
});
```

Pros:

 - People don't have to learn a new method - simplifies learning curve... maybe
 - Very easily override default options (such as `controllerAs`)

Cons: 

 - People don't have to learn a new method - Overloaded DDO is one of the most confusing parts of angular.

Very interested to hear what others have to say about this.

**Comment by mzgol** [comment]
I'd prefer to see a new method. Having bind set some other properties by default seems confusing. Also, I'd like no new API to set restrict to EA; they should be separated: E for components, A for decorators.

**Comment by gautelo** [comment]
Nice! :)

**Pull request closed without merging**
