### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by hardikvasa**
Minor modifications to the readme.md for clear understanding

### CODE REVIEW

**Comment by hardikvasa** [comment]
I signed it!

**Comment by Narretz** [comment]
Thanks for the PR. However, I am not 100% sold that these are clearer. What's wrong with "syntax" instead of "functionality"? And two-way data-binding is a pretty established concept.

**Comment by pkozlowski-opensource** [comment]
Agree with @Narretz - IMO the existing wording is better. -1 for this change from me.

**Comment by hardikvasa** [comment]
I just wanted to make it a little clearer. The word 'Syntax' is little specific to its usage pattern. The sentense denotes that one can extend its features (and not modify HTML statements)...and so a little generalized term 'functionality'. Hope it helps! Sorry if it is not found appropriate.

**Comment by Narretz** [comment]
While the readme text isn't that great, this is not a huge improvement either.

**Pull request closed without merging**
