### PR TITLE
removed ignored 'placeholder' attribute

### PR DESCRIPTION
**Pull request by nexus-uw**
input[type="date"] does not support the placeholder attribute (ref: http://www.w3schools.com/tags/att_input_placeholder.asp).

Also I present this as a contender for the smallest possible PR to this repo.

note: if this PR is acceptable, I expand it to include the remaining ignored placeholders in this file.

### CODE REVIEW

**Comment by Narretz** [comment]
Yes, this change is acceptable! Before we can merge however, we need for you the following things:
- [ ] sign the CLA
- [ ] change the commit message to `docs(input): remove ignored placeholder attribute`
- [ ] make sure it's all one commit

**Comment by gkalpak** [comment]
I think we still want to keep the placeholder, because some browsers (including Firefox) do not support `type="date"` and fallback to `type="text"`. In such cases, the placeholder is very helpful imo.

**Comment by Narretz** [comment]
@gkalpak Ah, yes you are right. I guess this can't be merged then :(

**Comment by nexus-uw** [comment]
poop. 

well thanks for the quick review.

**Pull request closed without merging**
