### PR TITLE
fix(inputs): ignoring input events in IE caused by placeholder changes o...

### PR DESCRIPTION
**Pull request by jbedard**
...r focus/blur on inputs with placeholders

This is my attempt at fixing #8242 as well as the extra placeholder issues with focus/blur. I'm assuming I'm missing a weird test case that still breaks somewhere, but I still think this is an improvement (it definitely is for my use cases).

### CODE REVIEW

**Comment by paquettea** [comment]
Not listening on "oninput" creates an issue on IE10 and IE11. The "clear field" button that is present in input type="text" and input type="search" is only firing oninput event (no onchange), so as it is right now, clearing the field with the button is not updating the ng-model value. I did a module to fix this because it seems there is quite a debate on what to do right now. I think that this tickets needs to be re-opened

https://github.com/paquettea/angular-ie-clearfield-databinding

**Comment by petebacondarwin** [comment]
OK let's take another look

**Comment by jbedard** [comment]
I think this is a method of modifying the input value that we missed.  This has two issues (only in IE) that I've found so far:
* If you clear a search box angular doesn't see the change until blur (when a change event fires).  This delays the ng-model update.
* The change event will not fire if the value is the same as when the input gained focus. This never updates the ng-model so the model value is wrong.

Should we open a new bug for this though?

**Comment by petebacondarwin** [comment]
@jbedard and @paquettea - if this is causing problems then let's open a new bug for it.

**Pull request closed without merging**
