### PR TITLE
README updated with SPA info

### PR DESCRIPTION
**Pull request by ghost**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Just light update to README featuring how easy you can build SPA using AngularJS

**What is the current behavior? (You can also link to an open issue here)**
It just does not mention about SPA at all

**What is the new behavior (if this is a feature change)?**
A new paragraph added with the info about SPA

**Does this PR introduce a breaking change?**
No, very light README update

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Other information**:

### CODE REVIEW

**Comment by vpavlov1199** [comment]
I signed it!

**Comment by vpavlov1199** [comment]
The Travis CI build failed, however I did not commit anything that might cause it. It's only readme text change. What should I do?

**Comment by frederikprijck** [comment]
> The Travis CI build failed, however I did not commit anything that might cause it. It's only readme text change. What should I do?

@vpavlov1199 The Travis build failed due to an incorrect commit message.

See: https://travis-ci.org/angular/angular.js/jobs/255645397

```
Validate commit messages in PR:
yarn run v0.27.5
$ "/home/travis/build/angular/angular.js/node_modules/.bin/commitplease" "e6d5fe7dea795d02eb2eab6ac69aca81a3edc99d..388b61785883115f052bc7a0566be89e9dac96ed"
Invalid commit message, please fix:
- First line must be <type>(<scope>): <subject>
Need an opening parenthesis: (
Commit message was:
README updated with SPA info
```

**Comment by Narretz** [comment]
I'm not sure if this is necessary at this time. Most people know that AngularJS is best used for Single Page Applications, but *new* projects should be started with Angular. So it doesn't make sense to claim that *AngularJS is the major JavaScript framework* for SPAs.
The official docs  are also written on the assumption that you are building an SPA, so I don't know how useful it is to mention this specifically. 
What we could do is mention SPA somewhere in the existing readme, as the word is currently not used at all. 
But I don't think we need a complete paragraph.

**Comment by frederikprijck** [comment]
I think it's a great thing to direct people to Angular as the go-to framework for SPA's these days. Mentioning SPA's for AngularJS wouldn't hurt (but I don't think it has alot of added value), but it definitely isn't the major SPA framework atm.

**Comment by Narretz** [comment]
I'm going to close this PR because we cannot merge it in its current state, as we are either waiting for more information, tests are missing, or required code changes haven't been made. 
Feel free to reopen this PR or open a new one if you have remdied the issues pointed out.

**Pull request closed without merging**
