### PR TITLE
feat(ngRoute): add method $route.silent(path) for change location path without triggering route controller

### PR DESCRIPTION
**Pull request by kulikov**

### CODE REVIEW

**Comment by marcalj** [comment]
I need the same function for query string update without triggering route controller! :)

Something like: ```$location.searchSilent('sf', SearchFilter.getForRouteParams());```

**Comment by icruces** [comment]
@marcalj That is possible with the option `reloadOnSearch = false` in your routeProvider configuration.

**Comment by marcalj** [comment]
@icruces Unfortunately if you set ```reloadOnSearch = false```, when you change manually the query string AngularJS doesn't trigger anything, and it's a feature I need.

**Comment by gkalpak** [comment]
AFAICT, the main usecase is changing the URL to something that would match the same route (with different `routeParams`), but not re-instantiate the controller/view. Because changing the URL to something that does not match the same route (or no route at all) would break user expectations (such as reloading, deep-linking, etc).

If that is indeed the case, there is an alternative PR (#15002), which implements something equivalent with `reloadOnSearch` but for the whole URL. So, as long as the new URL maps to the same route, the route is not being "reloaded".

##
This has some benefits over this PR:
- It is more predictable (being an explicit configuration option, rather than an imperative call).
- Per-route configurable (which means less boilerplate - you configure it once, then don't care how the URL is changed).
- More consistent with the existing `$route` API and .

##
My understanding (from reading through this thread) is that #15002 would cover the usecase people brought up here. Does anyone have a usecase that would not be covered?

**Comment by petebacondarwin** [comment]
Closing in favour of #15002

**Pull request closed without merging**
