### PR TITLE
docs(tutorial/11 - REST and Custom Services): Add a note that new test d...

### PR DESCRIPTION
**Pull request by kenhtanaka**
...ependencies cause a failure that can be cleared by restarting Karma.

### CODE REVIEW

**Comment by kenhtanaka** [comment]
I've signed the CLA, Contributor License Agreement.

**Comment by pkozlowski-opensource** [comment]
I'm not big fan of this change the way it is written. Maybe we should advise people to stop Karma before going to a next step instead?

**Comment by kenhtanaka** [comment]
I think it would be clear to advise people to stop Karma before going to the next step (and then restart afterward). Do I reword this and then issue another pull request?

**Comment by petebacondarwin** [comment]
Please reword and then add a new commit to this PR. We can merge and rebase etc when it is good.

**Comment by petebacondarwin** [comment]
Closing due to lack of activity.

**Pull request closed without merging**
