### PR TITLE
refactor(minErr): code cleanup

### PR DESCRIPTION
**Pull request by LeonardoBraga**
Removes a "magic number" (2) used multiple times in the code.
Removes unnecessary variables "arg" and "prefix".
Removed a condition within the "for" loop that generates query string parameters.
Adds a test case to ensure URL parameters are generated as expected.

### CODE REVIEW

**Comment by LeonardoBraga** [comment]
After applying the changes requested by @ilanbiala, I would like to know if there are any other adjustments or questions that might be holding this PR. Thanks!

**Comment by lgalfaso** [comment]
@LeonardoBraga will review this in the next day or two

**Comment by LeonardoBraga** [comment]
Thanks, @lgalfaso!

**Comment by LeonardoBraga** [comment]
@lgalfaso did you have the opportunity to take a look at this one?

**Comment by lgalfaso** [comment]
landed as b146cae02c6345d324b1c53845fb01b783226669

**Pull request closed without merging**
