### PR TITLE
chore(npm): Make require()-able as part of publish script

### PR DESCRIPTION
**Pull request by bclinkinbeard**
Deletes main field of package.json and creates index.js that is CommonJS compatible

/cc @caitp

### CODE REVIEW

**Comment by caitp** [comment]
@petebacondarwin I'd like to get this into the release today. Just going to test it real quick. That cool with you?

**Comment by caitp** [comment]
so, on my system, the `sed` call on package.json is getting `-e` passed as the value to `-i`, which is weird. I'm not sure if that's happening for you or not, but we might need to add a safety check just to prevent that from happening

**Comment by bclinkinbeard** [comment]
Not sure I follow. I'm not super familiar with sed tbh, but the deleteJsonProp function is using `sed -i -e`, which could very well be wrong. Is that the call you are referring to?

**Comment by caitp** [comment]
yes, I thought you added it, didn't check the diff =) @IgorMinar do you know if we were using that utility before and it worked right on jenkins?

**Comment by caitp** [comment]
wait, it is added in the diff :< hmmm

**Comment by bclinkinbeard** [comment]
Oh, I should probably just remove -e, no?

**Comment by bclinkinbeard** [comment]
Just pushed another commit combining the flags. I think that is right...

**Comment by caitp** [comment]
no, you definitely don't want to combine the flags... here's an idea, just leave it as it was before and delete the package.json-e if it exists, that probably is fine

**Comment by bclinkinbeard** [comment]
> delete the package.json-e if it exists

Sorry, I don't know what you mean by that.

**Comment by caitp** [comment]
.. if the file exists (`package.json-e`), remove it

**Comment by caitp** [comment]
well, I guess this won't make it for 1.3.9 :( sorry man.

**Comment by caitp** [comment]
...or maybe it will, we'll see :>

**Comment by bclinkinbeard** [comment]
I think this should be correct. Apparently some versions of sed require a suffix be passed to `-i`, so I've set it to use a blank string.

Fingers crossed! :)

**Comment by petebacondarwin** [comment]
sed is well outside of my comfort zone. If you two are happy with that then so am I.

**Comment by caitp** [comment]
just tested with the latest commit, looks good here

**Comment by caitp** [comment]
lgtm~

**Comment by caitp** [comment]
eh pete, should we backport this? I guess future 1.3 releases would want it too

**Comment by bclinkinbeard** [comment]
Sweet!

**Comment by petebacondarwin** [comment]
@caitp - let's put it in 1.4 and 1.3 but not 1.2 OK?
Feel free to merge then we have our release SHAs.

**Comment by caitp** [comment]
it is done~

**Comment by spacepluk** [comment]
thank you guys :)

**Comment by petebacondarwin** [comment]
I understand that there might be a problem with this?

**Comment by bclinkinbeard** [comment]
@petebacondarwin Yea we realized some shortcomings. https://github.com/angular/angular.js/pull/10732 now has the correct, improved version.

**Pull request closed without merging**
