### PR TITLE
feature(misc core): add ngId directive

### PR DESCRIPTION
**Pull request by RichardLitt**
Request Type: feature

How to reproduce: 

Component(s): misc core

Impact: large

Complexity: medium

This issue is related to: 

**Detailed Description:**

See below.

**Other Comments:**

There wasn't an ngId directive. While ngClass works a lot of the time - and ngClassOdd/Even and all of the $animate effects are incredibly useful - a directive that switches Ids would help with the way I configure Sass files, and would just be generally useful. I couldn't find any mention of an ngId directive around, probably due to poor google-fu, but here's a start.

### CODE REVIEW

**Comment by lgalfaso** [comment]
With the possibility to use `ng-attr-id`, then this PR is no longer needed

**Comment by RichardLitt** [comment]
@lgalfaso using `ng-attr-id` can lead to invalid HTML. Are we ok with that?

**Comment by caitp** [comment]
`data-ng-attr-id` should keep people relying on validators happy

**Comment by RichardLitt** [comment]
Word.

**Pull request closed without merging**
