### PR TITLE
remove useless code in function jqLiteBuildFragment

### PR DESCRIPTION
**Pull request by deplay**
discussed at #14810

remove useless code in function jqLiteBuildFragment

### CODE REVIEW

**Comment by deplay** [comment]
I signed it!

**Comment by Narretz** [comment]
Can you please update the commit message  according to our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format

**Comment by deplay** [comment]
@Narretz 
is it ok?
or anything else is needed?
thank you

**Comment by Narretz** [comment]
Not quite, sorry. In the commit message, you should write "refactor" instead of "fix". 
And ofr the future, make sure that there are no merge commits on the branch (i.e. amend the commit instead)

**Comment by deplay** [comment]
@Narretz 
I will delete this refactor branch after merge.

**Comment by gkalpak** [comment]
@deplay, as @Narretz said, it makes things easier for us (and hopefully you), if the change was on a single commit with the appropriate commit message.
Something to keep in mind for the next time :smiley:

**Comment by deplay** [comment]
@gkalpak Thank u for your suggestion.
also @Narretz ,thank you for your patient reply on this PR.
I will follow the rules in later contributions.

**Pull request closed without merging**
