### PR TITLE
ngClass[Odd/Even] overhaul (2)

### PR DESCRIPTION
**Pull request by gkalpak**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Fix, Test, Refactor, Perf

**What is the current behavior? (You can also link to an open issue here)**
Broken, inefficient.

**What is the new behavior (if this is a feature change)?**
Fixed, efficient.

**Does this PR introduce a breaking change?**
No (to the best of my knowledge).

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] ~~Docs have been added / updated (for bug fixes / features)~~

**Other information**:
This is a cleaned up version of #15228 (I didn't want to rebase #15228 to avoid losing existing comments or their context).

So, #15243 applies to this PR as well.

### CODE REVIEW

**Review by drpicox — APPROVED** [review]

**Comment by drpicox** [comment]
I'm ok.

**Comment by drpicox** [comment]
@googlebot OK

**Review by drpicox — APPROVED** [review]

**Comment by drpicox** [comment]
I am okay with these commits being contributed to Google.

**Comment by drpicox** [comment]
@googlebot I am okay with these commits being contributed to Google.

**Comment by gkalpak** [comment]
Actually, I don't think @googlebot can understand that. Just having your confirmation here should be enough. Thx!

**Comment by drpicox** [comment]
You're welcome.

**Comment by gkalpak** [comment]
Merged into master and v1.6.x (all changes) and 1.5.x (the fix only).

**Pull request closed without merging**
