### PR TITLE
camelCase directive in html referenced as kebab-case, The kebab-case shall be camel-case

### PR DESCRIPTION
**Pull request by rohitbind**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

**What is the current behavior? (You can also link to an open issue here)**

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change?**

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**Other information**:

In line no 71 and 72 `camelCase` is directive name and in HTML the it is said that it should be kebab-case where as it should be 'camel-case'.

I felt that beginners who is trying to learn from tutorial can get confused.

### CODE REVIEW

**Comment by Narretz** [comment]
Hm, I see the problem. We should use an example name for the component then, instead of camelCase, kebab-case, because the new example can also be confusing.

**Comment by rohitbind** [comment]
Hi Narretz,
travis failed what could be the reason, I just edited the doc. Is there is any problem from my side?

**Comment by gkalpak** [comment]
Thx for the PR, but this change is invalid. The used case is indeed called kebab-case.

**Comment by gkalpak** [comment]
I think it's best to add links to definitions of camel/kebab case.

**Comment by rohitbind** [comment]
I am not getting if I create a component with name 'camelCase' can I call that component in html by using 'kebab-case'?

**Comment by Narretz** [comment]
The names are not the real component names. It's just to illustrate that when defining the component, you do it like this: myCustomComponent. And when using it in the template do: my-custom-component

**Comment by gkalpak** [comment]
cb31067 hopefully improves the explanation of casing.

**Comment by rohitbind** [comment]
Thanks for accepting the suggestion :+1: :)

**Pull request closed without merging**
