### PR TITLE
docs(filter): Note about exact match in object

### PR DESCRIPTION
**Pull request by jpribesh**
Added note that when filtering for specific matches in javascript you MUST wrap the object key in quotes. Also provided example.

### CODE REVIEW

**Comment by jpribesh** [comment]
I signed it!

**Comment by gkalpak** [comment]
I don't think you have to ([proof][1]).
Have you seen this issue with a particular version ?

[1]: http://codepen.io/ExpertSystem/pen/BygNQN?editors=101

**Comment by jpribesh** [comment]
I am seeing this issue with v1.2.28

**Comment by jpribesh** [comment]
I just tested this on 1.3.15, and looks like the quotes aren't needed there. Perhaps there is some other issue causing this side effect for me.

**Comment by jpribesh** [comment]
I was also referring to using the filter in the js file. Either way it seems to work without the quotes [Proof](http://codepen.io/anon/pen/JoQEKg) Ill go ahead and close this pr, and open a new one if I figure out what is causing it in my code.

**Pull request closed without merging**
