### PR TITLE
Extending ng-model to hidden fields

### PR DESCRIPTION
**Pull request by stsvilik**
Hidden fields need to be able to set ng-model too. A good use case would be a hybrid solution such as MVC.net where forms are still submitted to the server (instead of pure AJAX post)

### CODE REVIEW

**Comment by yoonchee** [comment]
I am building a hybrid Django/AngularJS app and was trying to use some custom controls like sliders. I tried using ng-model on a hidden input that stores and posts the value of slider widget. To my surprise, ng-model didn't work on hidden input fields and I am commenting on this thread.

I think it should at least be documented that ng-model doesn't work with hidden inputs.

**Comment by hurkanakbiyik** [comment]
This is confusing. I think angular need ng-hidden.

**Comment by petebacondarwin** [comment]
Most of the use cases I have seen so far in this thread are using the hidden input as some interface to 3rd party code, which updates the value of the hidden input in some way, and that people expect `ngModel` to deal with this and make that value appear on the scope. `ngModel` listens in to DOM events like `change`, `blur` and `keydown` to trigger updates to the `$viewValue` and so to the value on the scope.

The question that occurs to me is how is Angular supposed to be aware of this change on a hidden input?

In the scenarios discussed in this issue, I don't believe that the hidden input element is going to trigger any particular DOM event just because another piece of code updates its value. One needs to look at that particular 3rd party code, on a case by case basis, and create a directive that will connect to the relevant event or callback.

I think we should put in place an error message if you try to use `ngModel` on a hidden input, which links to documentation about how to bind data "one way" for form submission and also advice on how one might connect to a 3rd party library that happens to update hidden inputs.  What do you think @caitp?

**Comment by Aldekein** [comment]
As I wrote before: 

> http://en.wikipedia.org/wiki/Principle_of_least_astonishment should be used there.
> ng-model in input type="hidden" should raise console error/warning

If it doesn't work - let it be documented, but not silent.

**Comment by CageFox** [comment]
gyarra above posted absolutely correct thoughts:

"1) There are valid situations where a hidden input may change, and the change should be reflected in the model.
2) As a new Angular developer, I expected ng-model to work with hidden fields.
3) There's no downside to allowing ng-model to work for hidden fields.

Conclusion: Update ng-model to work when applied to hidden fields. Developers want and expect this, for good reasons. There is no downside"

Everyone can check it by yourself, just find definition of

var inputType = {

In angular.js and replace

  'hidden': noop,

with

  'hidden': textInputType,

This simple update completely resolves the issue without any noticeable downside effects

So, my vote is for "Update ng-model to work when applied to hidden fields"

**Comment by lgalfaso** [comment]
https://github.com/angular/angular.js/pull/2574#issuecomment-77846367 is spot on. `ngModel` is for 2-way binding and a hidden field is not for 2-way binding.
The only thing that would make sense it to generate a warning when putting an `ngModel` on a hidden field.

**Comment by petebacondarwin** [comment]
Could someone provide a PR with this warning in place?

**Comment by CageFox** [comment]
Explain, please, why the hidden field is bad for 2-way binding. 

Why not to allow 2-way bind it for those who need it

Why not to implement simple and highly demanded feature, that can be implemented by changing 1 line of code?

**Comment by lgalfaso** [comment]
@CageFox browsers generate no events when the value of a `input[type=hidden]` changes, so the one line change that you posted only does 1-way data binding.

**Comment by CageFox** [comment]
The change event didn't generated automatically, but can easyly be fired by code

Of course it is simplier to force all users to fully refactor all old code (jquery/native javascript), but may be it is more fair not to force and allow to mix it?

**Comment by lgalfaso** [comment]
@CageFox what do you mean with "but can easily be fired by code"? You mean that angular should watch the value of the element and then generate the event?

**Comment by CageFox** [comment]
Easily fired bo code like $(".change_me").trigger("change")

I manage 15+ years old business web application, and there is ton of old code written by many different people. Storing variables in hidden inputs is typical for old school apps. I personally always use patched like "'hidden': textInputType" angular, it allows me to use ng-model to inputs and freely change between input types without changing other directives

And I think this patch costs nothing at all for those not using hidden inputs, so why not implement it?

**Comment by hiteshghanshas** [comment]
<input class="field_camp" type="text" name="Token" style="display: none;"  ng-model="signup.Token"  ng-init="signup.Token=Token"/> ${Token}
and in angular part.
var data = { Token:$scope.signup_form.Token.$modelValue, };
all my data is going in post , just not this 'token' in hidden field. what should i do.

**Comment by hiteshghanshas** [comment]
input class="field_camp" type="text" name="Token" style="display: none;"  ng-model="signup.Token"  ng-init="signup.Token=Token      ${Token}

**Comment by gkalpak** [comment]
@hiteshghanshas, this sounds like a general support question. You should try on one of the [appropriate support channels][1].
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx !

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

**Comment by WillsB3** [comment]
Sorry, but this assumption is silly in my opinion.

Just because the user cannot interact with a hidden input doesn't mean that another directive isn't interacting with it dynamically.

Example: We have a component which allows you to add/remove items from a list. The items are modelled as objects in an array called `items` on the directive controller. This array is used to render the list of items in the directive template. When a user adds an item via the widget a new object gets added to this `items` array. 

Now, we need a way to submit the contents of the list to the server. Our Application is a combination of Django rendered pages and Angular "components". These Angular components are most often just custom field widgets. In the above example we use a input field, along with ngModel, and ngModels $parsers, $formatters and $validators to serialise the representation of `items` into a string of JSON, and to handle validation using the usual validation pipeline as offered by the built in directives. When the user submits the form the stringified JSON it sent to the backend via a normal `POST` request where the server then converts the data back into a dictionary.

This works great, as long as the input is type `text` and not `hidden`. We're using Angulars built in support for $parsers, $formatters and $validators to do conversion between $viewValue and $modelValue data formats, which feels correct. We're also implementing a custom $validator which ensures that our custom field is marked as invalid if it's marked as required and the user deletes all the items in the list - This also feels correct, again, because we're using Angulars built in support for providing custom $validators. If we use `ng-value` (to make the value actually update correctly, as per this issues discussion) we loose the ability to use $parsers, $formatters and $validators on this field.

Many apps aren't 100% Angular/SPA and still use server rendered pages. In these cases where the frontend does not submit data over an API, but instead uses regular old form fields and form POST, the inability to use plain text fields containing serialized json behind custom UI controls means that we have to resort to things like using `<input type="text>" and then just hiding the input with CSS and setting `tabindex=-1`...

Of course, in an "ideal" world we'd all be building SPAs in Angular where the only backend we have is an API, but that's simply not the case for everyone ;)

**Comment by petebacondarwin** [comment]
IMO the component that handles the list manipulation should support ngModel instead, then you could apply the result of that to the ngValue on the hidden input.

**Comment by WillsB3** [comment]
Hi Pete,

I agree - in hindsight that would probably have been a better solution. I still believe that the ng-model behaviour not working on input type hidden is not obvious. We're not yet running the latest version of 1.x, so I wasn't seeing the warning that sounds like it was implemented. 

Perhaps a small addition to the ngModel section in the docs would be helpful for furture users too?

**Comment by artoale** [comment]
@petebacondarwin true enough, adding support for ng-model in the list manipulation directive makes total sense. Still, there might be plenty of reason for it not being able to support it. Simple one, depending on an external library you have no control over.

**Comment by petebacondarwin** [comment]
A workaround could be to use a non-visible text input element rather than a hidden input element.
E.g.

```html
  <input type="text" ng-model="$ctrl.listValue" some-formatter-directive style="display: none">
```

See http://plnkr.co/edit/EY8EkysbgQMXt38YxG20?p=preview for a working example.

**Comment by whiplashomega** [comment]
Use case I encountered, that I then had to do a jQuery workaround.  My login page is server-rendered, and includes a hidden field with a cfsr token as a preset value.  I am submitting the login information via AJAX post in angular.  I needed angular to pull the server provided cfsr token from the hidden field into the model so that it could be submitted with the login request.  ng-value data-binds the wrong way for my purposes.  I had to workaround using jQuery().val() and set the value of my cfsr token at login submission time rather than use angular native data-binding.

**Pull request merged**
