### PR TITLE
Please let us use shims for old IE

### PR DESCRIPTION
**Pull request by S-YOU**

### CODE REVIEW

**Comment by S-YOU** [comment]
I signed it!

**Comment by Narretz** [comment]
which ie9 versions does this affect? IE8 is unsupported since 1.3

**Comment by S-YOU** [comment]
You don't have to support IE8. but, that angular works well with shims.
But with above code, IE throw error for the whole file.

**Comment by lgalfaso** [comment]
I have to disagree with @S-YOU, IE8 is not supported starting with 1.3. This is, IE8 is strictly not supported and this is with or without shims.
If you would like to have this change, then there are other projects that do code transformation to make some browsers happy (eg https://github.com/StoryCloud/webkit-assign) you are free to clone their projects and make Angular 1.4.x work for IE8, but I see no reason for merging this.

**Comment by S-YOU** [comment]
Sigh! the whole point of using shims is to be able to use official angularjs, not someone else build.
And StoryCloud/webkit-assign is irrelevant, its about webkit, not related to IE.

**Comment by realityking** [comment]
@S-YOU 

What you could do use is use babel's [propertyLiterals](http://babeljs.io/docs/advanced/transformers/es3/property-literals/) transform in your build process to do this automatically.

**Comment by S-YOU** [comment]
Thanks for info @realityking. Good to know that. I indeed built my own.

**Comment by Narretz** [comment]
Turns out we need to do this anyway to support Android 2.3: https://github.com/angular/angular.js/commit/1cc9c9ca9d9698356ea541517b3d06ce6556c01d

**Comment by S-YOU** [comment]
IE haters, hahaha. Now, I have my own fork of what I wanted. No more negative noises!

**Comment by gkalpak** [comment]
@S-YOU, fwiw, this particular one is already fixed as @Narretz mentioned in https://github.com/angular/angular.js/pull/12593#issuecomment-133112958.

**Pull request closed without merging**
