### PR TITLE
Typo/mismatch fix

### PR DESCRIPTION
**Pull request by ghost**
There is an mismatch for status in controller and test. 
In controller $scope.status = 'ERROR!' and in test we expect($rootScope.status).toBe('Failed...') so the test will fail;

### CODE REVIEW

**Comment by toastman** [comment]
I signed it!

**Comment by toastman** [comment]
@Narretz You don't agree with my suggestion ? Please look at $htmlBackend docs https://docs.angularjs.org/api/ngMock/service/$httpBackend

**Comment by gkalpak** [comment]
@toastman, he must totally agree with your suggestion, because he (@Narretz) merged it into master (159efdd) :smile:

**Comment by toastman** [comment]
@gkalpak Thank you, I'm just misunderstood ("This pull request is closed, but the toastman:patch-1 branch has unmerged commits.")

**Pull request closed without merging**
