### PR TITLE
feat(filterFilter): compare object with custom `toString()` to primitive

### LINKED ISSUE #10464: filterFilter compare custom objects in 1.3.6
First off all I am a big fan of the changed behavior as I can do finally filtering complex data as I could in angular 1.0.x

Only the default comparator should not return false if  actual or expected is an object.

My use case are mongodb ObjectIds with a custom toString function.
From angular 1.0 to 1.3.5 the filterFilter could compare this custom object with a string or another ObjectId.

I know I can use my one comparator but i think the new comparator is a bit to picky.
A string like `'[object'` is in my opinion a user error.

WDYT?

### PR DESCRIPTION
**Pull request by m7r**
Closes #10464

### CODE REVIEW

**Comment by pkozlowski-opensource** [comment]
@m7r I've left some additional comments to the tests - not a big deal, I can change those while merging, but would like to have your feedback on those.

**Comment by m7r** [comment]
@pkozlowski-opensource why is the milestone set from 1.3.9 to 1.4?

**Comment by m7r** [comment]
@pkozlowski-opensource what are the next steps?

**Comment by petebacondarwin** [comment]
I tweaked this and landed it. Thanks @m7r

**Pull request closed without merging**
