### PR TITLE
docs(guide/Scopes): fixed a type

### PR DESCRIPTION
**Pull request by skuhnow**

### CODE REVIEW

**Comment by skuhnow** [comment]
I signed it!

**Comment by Narretz** [comment]
Are you sure about this? "accounted for" is a common phrase, and without the "for" the sentence sounds strange.

**Comment by skuhnow** [comment]
I'm not a native speaker, so I'm not sure. For me it sounds strange with the "for"

**Comment by gkalpak** [comment]
Thx for the PR, but the sentence was correct.
"Account for" is a valid idiom (e.g. see http://idioms.thefreedictionary.com/account+for).

**Pull request closed without merging**
