### PR TITLE
Add min group size to number patterns.

### PR DESCRIPTION
**Pull request by radmaneshp**
The whole part of Polish numbers are grouped in 3's separated with a space (and a comma for the decimal separator), but only after there are at least 5 digits in the whole part - https://pl.wikipedia.org/wiki/Separator_dziesi%C4%99tny:

  3,14
  0,178011392519
  157,3567
  5348,26
  25 772,1
  9 212 345,576213

This change adds a new optional number format property, gMinSize, which if set causes the whole part of a number to only be grouped if it is greater than or equal to gMinSize.

### CODE REVIEW

**Comment by Narretz** [comment]
Hi, thanks for the Pr.
We import the Google Closure i18n library for localization, which means any changes to the files in this repo are overwritten when we re-import the library.
It's possible that the gMinSize property exists in the closure lib (we don't use all of them). Otherwise, you can try to get your changes for Polish accepted into the google closure i18n library.

**Comment by radmaneshp** [comment]
Could you point me to where these files come from in https://github.com/google/closure-library/tree/master/closure/goog/i18n? I can't find them and I thought they were Angular specific since it's about filtering?

**Comment by Narretz** [comment]
Ah, I see. The filter changes are independent of the locale file changes, The filters are part of angular core, so we could talk about adding the filter change without the changes in the locale files.

**Comment by radmaneshp** [comment]
Sounds good. How do I revert the locale changes from this pull request?

**Comment by Narretz** [comment]
Remove the changes locally, commit them, and then squash the commits together via git rebase -i (check the docs for that). Then git push -f to update the PR.
By the way, you should ideally create your pull requests on a separate branch.

**Comment by Narretz** [comment]
Please also check the commit message guidelines under https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit Thanks!

**Comment by radmaneshp** [comment]
Sorry, I am new to github and I am just using this guthub website, not a local client. I will do the updates to my locale client, but is there a way to do git rebase -i and git push -f from this github website?

**Comment by Narretz** [comment]
I don't think there's a way to rebase using the Github website. If you are doing a new PR, you don't have to rebase your commits necessarily.

**Comment by radmaneshp** [comment]
I just committed the changes to my client and I see they are automatically being picked up now. Hopefully that works like git rebase -i and git push -f?

**Comment by Narretz** [comment]
Yes, they are being picked up, but what we want in the end is a single commit with all changes, not many commits. That means you have to squash the commits together (with rebase).

**Comment by radmaneshp** [comment]
OK, no worries. I'll redo from scratch. A couple of last questions:

1) Using the GitHub website, to work on a new branch do I just create a new branch of of my forked repository of angularjs, or do I create a new branch directly from the angualrjs repository?

2) During my next review, if I get suggestions for changes, how do I make them using the website without having multiple commits? If it's not possible, could we do the review on this one now so I can get all those items fixed first then redo it?

**Pull request closed without merging**
