### PR TITLE
Set theme jekyll-theme-time-machine

### PR DESCRIPTION
**Pull request by devs4p**

### CODE REVIEW

**Comment by devs4p** [comment]
I signed it

**Comment by devs4p** [comment]
I have signed it

**Comment by Narretz** [comment]
Can you explain what this does? Our docs are not on github pages and not processed with jekyll.

**Comment by gkalpak** [comment]
Ooops, I didn't realize you had commented on it, @Narretz.
I am pretty sure this was an accident. (If not, speak up, @devs4p 😄)

**Pull request closed without merging**
