### PR TITLE
docs(tutorial/10 - Event Handlers): missing unit test

### PR DESCRIPTION
**Pull request by sandormajor**
In the doc there stands "You also have to refactor one of your unit tests because of the addition of the `mainImageUrl`
model property" but the spec was missing the test of `mainImageUrl`

### CODE REVIEW

**Comment by Airborn22** [comment]
I signed it!

**Comment by Airborn22** [comment]
There is a pull request for the phonecat app but it's failing now because of an issue on master: https://github.com/angular/angular-phonecat/pull/279

**Comment by Narretz** [comment]
Thanks for the PR. The way I see it, the description is accurate: You need to update the test, because the `phone` on the scope is different now. We can add an additional expect/test for the mainImageUrl, but it is already tested in the e2e test.

**Comment by Airborn22** [comment]
Thank you @Narretz, I created a pull request for the test but all the builds are failing there for some reason. I will create a new pull request later.

**Comment by Narretz** [comment]
You don't have to open a new PR, you can push --force to your branch and it iwll update the PR.

**Comment by gkalpak** [comment]
The tutorial has changed quite a bit (with #14416).
If you think this change is still relevant, please submit a new PR against the latest code.

Thx !

**Pull request closed without merging**
