### PR TITLE
chore(test): bump Protractor version to 2.0.0

### PR DESCRIPTION
**Pull request by juliemr**

### CODE REVIEW

**Comment by petebacondarwin** [comment]
LGTM - merging into master (and stable?)

**Comment by juliemr** [comment]
I will merge into master and stable.

**Comment by juliemr** [comment]
Merged as 
master: c7ebce6fb8eae878caab4810067f5adef0d1f908
stable: 3bdb39f667dc3ae5db148fe2ca3665af87efe2e1

**Comment by petebacondarwin** [comment]
Thanks. I got distracted :-)

**Pull request closed without merging**
