### PR TITLE
docs(guide/Conceptual Overview): change "factory" to "constructor"

### PR DESCRIPTION
**Pull request by alirezamirian**
Controller functions are treated as **constructor** functions by angular, not **factory** functions and
controllers instances are created by instantiating their registered **constructor** function

### CODE REVIEW

**Comment by Narretz** [comment]
Aren't thje docs saying the controllers are created by a controller factory? Sure, the actual controller is defined by a constructor, but it is created by a factory.

**Comment by alirezamirian** [comment]
From [docs](https://docs.angularjs.org/guide/controller):
> In Angular, a Controller is defined by a JavaScript **constructor function**

I'm not sure if the module API `.controller` ( which is used for **registering** a controller inside some module, not **creating** it) is being called **factory**.
If this is the case, I still don't feel right about it.

**Comment by Narretz** [comment]
Then maybe the sentence should be:
> In the previous section we saw that controllers are registered using a constructor function.

Regardless what the change is, the next sentence will feel unconnected if we change factory to constructor. So we should take that into account.

**Comment by Narretz** [comment]
You were right here - this was chnaged here https://github.com/angular/angular.js/commit/88f3517db2a66b3b8a1a5888e07ccca7c6604c01

**Pull request closed without merging**
