### PR TITLE
optimization in isBoolean

### PR DESCRIPTION
**Pull request by zaheerehmad**
typeof comparison with string is slower than triple equal comparison.

### CODE REVIEW

**Comment by pkozlowski-opensource** [comment]
@zaheer-ahmed could you please share some evidence (jsPerf or similar) of it being faster?

**Comment by pkozlowski-opensource** [comment]
Checking Travis build results there seem to be some test failrues that look legitimate. Those would have to be fixed.

**Comment by lgalfaso** [comment]
rebasing on top of master should fix the Travis error

**Comment by pkozlowski-opensource** [comment]
@zaheer-ahmed haven't hear from you regarding the benchmark / rebase so going to close this one for now. Happy to re-open when you've got more info.

**Pull request closed without merging**
