### PR TITLE
feat(jqLite): use querySelectorAll instead of getElementsByTagName in jqLite.find

### PR DESCRIPTION
**Pull request by jankuca**
Addresses #3586

### CODE REVIEW

**Comment by mzgol** [comment]
If we were to use an external CSS selector engine, we might as well use the
most popular & battle-tested one in the world: Sizzle that is included in
jQuery... 18 KB minified. The one @caitp linked to is 10 KB, so also not
extremely small.

BTW, Sizzle will be dropping support for browsers not supported by jQuery
which will decrease its size.

I feel that escapes jqLite's goal, though - if we want to be more
feature-complete & stable even if that sacrifices the size, we have jQuery
for that.

**Comment by mzgol** [comment]
Correction: since only gzipped sizes matter; here they are:

Sizzle: 6.9 KB
CSS_selector_engine: 4.6 KB

And note that the next Sizzle version will be smaller.

**Comment by bzitzow** [comment]
+1

**Comment by starzou** [comment]
+1

**Comment by daniellmb** [comment]
+1

**Comment by caitp** [comment]
>  fixing this properly is non trivial and won't happen in 1.3. moving this back to backlog.

I think it's time for this one to be closed. we can take another attempt at this in the future (with the next level of DOM), but I don't think there's much hope for the aspirations of this right now.

**Pull request closed without merging**
