### PR TITLE
fix(ngAnimate): ensure that minified repaint code isn't removed

### LINKED ISSUE #9936: different behavior angular-animate.js angular-animate.min.js (1.2.26) in Firefox 33.0.2
I use SolydK 64bit with latest Firefox (33.0.2). The following code behaves different when using minified version of angular-animate:

----------- html ------------------
```
<!DOCTYPE html>
<html lang="de" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>AnimateTest</title>
    <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.2.26/angular.min.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.2.26/angular-animate.js"></script>
    <link href="main.css" rel="stylesheet" type="text/css">
</head>
<body data-ng-app="ngAnimate">
    <div class="animate-show" data-ng-hide="showPartial">
        Some content here ...
    </div>
    <input type="checkbox" data-ng-model="showPartial">Click here ...
</body>
</html>
```

----------- css --------------------
```
.animate-show {
    -webkit-transition:all linear 0.5s;
    transition:all linear 0.5s;
    line-height:20px;
    opacity:1;
    padding:10px;
    border:1px solid black;
    background:white;
}

.animate-show.ng-hide {
    line-height:0;
    opacity:0;
    padding:0 10px;
}

.check-element {
    padding:10px;
    border:1px solid black;
    background:white;
}
```

------------------------------------

Using the unminified version of angular-animate everything works fine. Using the minified version hiding the `<div>` is animated but showing is not (it just pops out). In Chromium everything works as expected so it could be a Firefox-Bug, but with Angular Version 1.3.1 things are working in Firefox too ... so it should be an issue you can solve in the 'stable' branch by yourself ...

### PR DESCRIPTION
**Pull request by matsko**
Closes #9936 

1.2 / 1.3 / 1.4

### CODE REVIEW

**Comment by petebacondarwin** [comment]
LGTM.  @Narretz does this work for you?

**Comment by matsko** [comment]
@petebacondarwin @Narretz's code was having issues with #11336. So this PR won't be compatible with the issues he's facing. However this issue still does exist for other versions of Angular and this patch corrects that.

**Comment by Narretz** [comment]
I'll check in 30 minutes 😊 

----- Ursprüngliche Nachricht -----
Von: "Pete Bacon Darwin" <notifications@github.com>
Gesendet: ‎31.‎03.‎2015 08:43
An: "angular/angular.js" <angular.js@noreply.github.com>
Cc: "Martin Staffa" <mjstaffa@googlemail.com>
Betreff: Re: [angular.js] fix(ngAnimate): ensure that minified repaint codeisn't removed (#11469)

LGTM. @Narretz does this work for you?

**Comment by petebacondarwin** [comment]
Fine by me

**Comment by Narretz** [comment]
Ah, I didn't see this was a new issue. Interesting, I never had this problem in Firefox before. At least not as visible.

**Comment by matsko** [comment]
MERGED

Landed as:
https://github.com/angular/angular.js/commit/c55a494433e619aad0c7ef9fddadc0b3fdf53915
https://github.com/angular/angular.js/commit/d5c99ea42b834343fd0362cfc572f47e7536ccfb
https://github.com/angular/angular.js/commit/b041b664752e34a42bbc65e02bf0009f0836c50c

**Pull request closed without merging**
