### PR TITLE
chore(*): update copyright year

### PR DESCRIPTION
**Pull request by AngelKitty**
Happy new year!

### CODE REVIEW

**Comment by AngelKitty** [comment]
@googlebot  I signed it!

**Comment by AngelKitty** [comment]
@petebacondarwin Can you review it?

**Review by petebacondarwin — APPROVED** [review]

**Comment by AngelKitty** [comment]
@gkalpak Can you review it?

**Comment by gkalpak** [comment]
There are a few more occurrences that need updating. Would you fancy updating them too?

**Comment by AngelKitty** [comment]
@gkalpak OK, can you review it again?

**Comment by AngelKitty** [comment]
@mgol Can you review it?

**Review by gkalpak — APPROVED** [review]
LGTM :+1: Thx, @AngelKitty!
(I will update the commit messages to adhere to [our conventions][1] and merge.)

[1]: https://github.com/angular/angular.js/blob/36f17c926/DEVELOPERS.md#commits

**Pull request closed without merging**
