### PR TITLE
docs(): clarify scope types and controllerAs

### PR DESCRIPTION
**Pull request by Narretz**

### CODE REVIEW

**Comment by petebacondarwin** [comment]
Sorry, @Narretz, this needs a rebase as I just landed a change to the same area.

**Comment by Narretz** [comment]
I rebased before I pinged you. Maybe it didn't pick it up in time. It should work now.

**Comment by petebacondarwin** [comment]
LGTM merging

**Comment by Narretz** [comment]
Thx!

**Pull request closed without merging**
