### PR TITLE
Update broken e2e tests.

### PR DESCRIPTION
**Pull request by benedictchen**
The e2e tests now don't work :-(.  This is an update to that.

### CODE REVIEW

**Comment by benedictchen** [comment]
CLA should be there right now...the tag is wrong.

**Comment by benedictchen** [comment]
Googlebot is frighteningly human.

**Comment by gkalpak** [comment]
Bah, I miss @mary-poppins :disappointed:

**Comment by benedictchen** [comment]
**nudge**

**Comment by petebacondarwin** [comment]
@benedictchen - is this actually fixing broken e2e tests or adding new tests that you think would be useful? I think that perhaps it is the latter, in which case this should appear in the **Experiments** section, yes?

**Comment by petebacondarwin** [comment]
Closing due to lack of activity. Please re-comment if you want to progress this PR further.

**Pull request closed without merging**
