### PR TITLE
docs($templateCache): let's get rid of ng-include not to create bad example

### PR DESCRIPTION
**Pull request by stevermeister**
- [x] The commit message follows our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [x] Docs have been added / updated (for bug fixes / features)

### CODE REVIEW

**Comment by Narretz** [comment]
Can you explain why this is a bad example?

**Comment by stevermeister** [comment]
@Narretz 
"ng-include" first thing that you need to remove from your project if you aim to have good component approach. 

http://teropa.info/blog/2015/10/18/refactoring-angular-apps-to-components.html#replace-ng-include-with-component-directive

**Comment by petebacondarwin** [comment]
How about we rework the order and emphasis here, rather than just deleting an outdated but perfectly valid example.

For instance, we could have three examples:

* use the template from a component directive
* access the template programmatically
* use the template via ng-include (perhaps with a comment that the recommended approach is to use components rather than including templates for most scenarios)

**Comment by stevermeister** [comment]
@petebacondarwin 
good point, will add it

**Comment by Narretz** [comment]
@stevermeister I'm gonna close this PR, but please feel free to reopen it when you have amended it based on Pete's ideas.

**Comment by stevermeister** [comment]
ok, created new one with component example - https://github.com/angular/angular.js/pull/15120

**Pull request closed without merging**
