### PR TITLE
$animate callbacks using DOM queries

### PR DESCRIPTION
**Pull request by matsko**
This patch fixes ngView to inject `$element` and also patches `$animate.on` and `$animate.off` to provide support for triggering callbacks based on a DOM-query.

All of this is to make using animation callbacks within controllers easier.

### CODE REVIEW

**Comment by matsko** [comment]
@petebacondarwin @IgorMinar this code works, but there is a potential leak where if a controller is destructed then the associated callback function is never removed unless element.off is called.

Perhaps we should document that you always MUST remember to deregister the callback?

**Comment by gkalpak** [comment]
> All of this is to make using animation callbacks within controllers easier.

I am frightened by this line :fearful: 
I hopw you mean directive controllers, right ? Right ?

**Comment by petebacondarwin** [comment]
@gkalpak I think we are talking about route controllers here, right?

@matsko could you not attach an event handler to the jqLite '$destroy' event on each DOM element that has an animation callback attached? This handler would remove all events on that element. This would prevent the leak since the element would be destroyed alongside the controller.

**Comment by gkalpak** [comment]
Hm...I thought accessing the DOM (even indirectly) from within a controller was an anti-pattern (unless it was a directive, which again is debatable if the DOM should be accessed from the controller or the linking functions).
Of course with the new router/ng2 each route/view will be a components (aka directive), but currently I am skeptical about suggesting having animations in route controllers.

--
Regarding the auto-$destroy suggestion, I don't think it's a fool-proof solution, since the controller might be animating elements out-living it. But it's definitely a step in the right direction.

**Comment by Narretz** [comment]
I am also not really sure we need animate callbacks in route controllers. @matsko is this something that was requested by someone?

**Comment by petebacondarwin** [comment]
I tend to agree with @Narretz here. What is the use case for handling animation callbacks inside a route controller? Surely this could be done by applying a new directive either inside the template or on the ng-view element?

**Comment by petebacondarwin** [comment]
Moving to post 1.4.0

**Pull request closed without merging**
