### PR TITLE
docs(ng.$log): show how log methods are bound to console

### PR DESCRIPTION
**Pull request by glebec**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

Docs update

**What is the current behavior? (You can also link to an open issue here)**

The fact that `$log` methods are applied to the `console` regardless of invocation context is useful but not noted anywhere.

**What is the new behavior (if this is a feature change)?**

An example is provided of how this pre-binding streamlines the use of `$log` methods as handler functions, e.g. for `$http` promises.

**Does this PR introduce a breaking change?**

No.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format

**Other information**:

N/A.

### CODE REVIEW

**Comment by gkalpak** [comment]
I don't think we want to document this (so people start relying on it).
It is an implementation detail and we should retain the flexibility to change it any time.

**Comment by glebec** [comment]
That's fair. For me it's one of the only reasons I use `$log` over `console`, so it seemed like a feature, even if accidental. But I can also accept that maybe it's not intended to be a feature. My questions would then be:

* How likely will it be that in the future, the `$log` methods will use the `this` keyword? If the answer is "conceivably that will happen," that lends more credence to not documenting this otherwise-useful characteristic of the `$log` service. If the answer is "almost certainly not," I would posit that this documentation provides a compelling use case for `$log`.
* If you *do* incorporate this PR, test cases might serve as an effective guard against accidentally or casually removing this functionality, at least not without altering the documentation to match and versioning it as a breaking change. Would that make this PR more or less palatable from your perspective?

Regards, —G.

**Comment by gkalpak** [comment]
> How likely will it be that in the future, the `$log` methods will use the `this` keyword?

Neither very likely, nor very unlikely. There have always been thoughts about providing a more powerful implementation for `$log` (one that might more heavily rely on prototype and `this`) - not very likely to happen, but there have been discussions :stuck_out_tongue: Or maybe we decide to delegate directly to `console` for whatever reason. Furthermore, if people start relying on `$log` methods not being context-sensitive, then all 3rd-party implementation that decorate or eplace `$log` will need to also ensure they have "context-insensitive" methods.

> test cases might serve as an effective guard

It's not about accidentally breaking it, it's more about being free to break it. By exposing implementation details, we tie ourselves to specific implementations, which makes it harder to swap them for something better.

--
Also note we are discussing about `$log.error` vs `$log.error.bind($log)` - it's really a minimal overhead :smiley:

I'll leave this open though - maybe be someone disagrees...

**Comment by glebec** [comment]
> It's not about accidentally breaking it, it's more about being free to break it.

I hear you. Okay, I don't feel very strongly about it in any case, it's a small thing. ;-) Cheers, —G.

**Comment by petebacondarwin** [comment]
Closing as won't fix. Thanks for the PR @glebec

**Pull request closed without merging**
