### PR TITLE
feat(ngModel): support locals being passed through to ngChange

### PR DESCRIPTION
**Pull request by dcherman**
This is a WIP proposal for #14683.  If the approach seems acceptable, I'll write up accompanying unit tests and documentation.

### CODE REVIEW

**Comment by gkalpak** [comment]
I'm not a big fan of this tbh. Things I don't like:

1. It doesn't feel like a common feature. Besides it is doable outside the core.
2. The concept of `locals` is not the most trivial one to explain. This adds an overhead to simple concepts, such as `ngChange`.

--
Anyway, it is a tiny change with minimal overhead. So, if others think this "view value metadata" feature would be useful, I won't stand in your way :stuck_out_tongue:

--
Things I would consider:

1. Making the metadata available via locals as `$metadata` or `$viewValueMetadata` or something. This would use the same mechanism under the hood, but users don't have to understand scope evaluation and locals.
2. Passing the metadata as argument to all `$viewChangeListeners`.

**Comment by dcherman** [comment]
It's more common for implementers of library controls with complex behaviors.

The two primary use cases that have come up for us are:

1.  Selectable Behaviors: When a user shift clicks or ctrl clicks multiple items, the resulting ngModel value is the value extracted from an expression on those items.  It's useful to provide additional information about the operation though such as the value of the item that was actually clicked; that metadata is used to provide behaviors like scrolling the item fully into view in case it was partially clipped.

2.  Drag and Drop - A similar thing, the ngModel value might be the values of the item(s) that were dropped, however additional metadata about the operation allows you to customize the behavior such as removing the item from the source if you're dragging between two lists.

These are admittedly not the common use case, but I figured it'd be worth seeing if others would find value in this.

**Comment by petebacondarwin** [comment]
I also don't feel very comfortable with this feature.
It would seem to me that a better place to do this is in a `$parser`. Then you can pass a complex object, containing the actual main value and any metadata, to the `$setViewValue` method and the `$parser` can do any special work that it wants before pulling out the main value and passing that down the pipeline.

**Comment by petebacondarwin** [comment]
Closing due to lack of response

**Pull request closed without merging**
