### PR TITLE
fix($timeout/$interval): throw when trying to cancel non-$timeout/$interval promise

### LINKED ISSUE #16424: Promise returned from $timeout should not be chained because $$timeoutId is lost
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [x] other 

**Current behavior:**

`$timeout` returns a `promise` that has been "decorated" with a `$$timeoutId` that is then required when attempting to cancel the timeout via `$timeout.cancel(promise)`. When chaining to this promise upon creation (i.e. `then`, `catch`, and/or `finally`), the promise returned from the chained function(s) is a new promise that **does not** contain `$$timeoutId`.

**Expected / new behavior:**

Ideally, Angular.js would not be adding properties willy-nilly to this promise. Secondly, it would be great if the chained calls would return back any extra properties set on the original promise (i.e. `$$timeoutId`). BUT, it would suffice if the documentation for `$timeout` could be enhanced to provide a note about this limitation.

**Minimal reproduction of the problem with instructions:**

[Plnkr](http://plnkr.co/edit/nZv9w8?p=info) - Take note that this is built with a chained `catch` and causes the timeout to not be canceled. If you remove the chained `catch` or move the `catch` to a separate line after initial assignment, it cancels just fine.

**AngularJS version:** 
1.6.6

**Browser:** 
All

**Anything else:**
I strongly would consider this a defect but because I don't think you're going to change your underlying `then`, `catch`, and `finally` implementation to copy any ole' properties from the chained promise, documentation would suffice for any other future souls.

The guilty line of code is here: https://github.com/angular/angular.js/blob/master/src/ng/timeout.js#L66

### PR DESCRIPTION
**Pull request by gkalpak**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Bug fix (sort of).

**What is the current behavior? (You can also link to an open issue here)**
Calling `$timeout/$interval.cancel()` with a non-$timeout/$interval promise silently does nothing.
This can for example happen, when calling `.then()`/`.catch()` on the returned promise, which creates a new promise and use that new promise for cancelling.

**What is the new behavior (if this is a feature change)?**
Passing a non-$timeout/$interval promise to `$timeout/$interval.cancel()` throws an error.
This will help catching issues tht would otherwise go unnoticed.

**Does this PR introduce a breaking change?**
Yes.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our [guidelines](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits)
- [x] Fix/Feature: [Docs](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#documentation) have been added/updated
- [x] Fix/Feature: Tests have been added; existing tests pass

**Other information**:
Fixes #16424.

### CODE REVIEW

**Review by mgol — APPROVED** [review]
LGTM. Maybe you could land the big indentation change in `src/ng/interval.js` separately but no biggie.

**Review by Narretz — CHANGES_REQUESTED** [review]
I'd also like to see the indentation changes in a separate commit :>

**Comment by gkalpak** [comment]
Moved indentation fixes to separate commits.

**Review by mgol — APPROVED** [review]

**Review by Narretz — APPROVED** [review]

**Comment by abobwhite** [comment]
Thanks for getting on this so quickly. I have a unit test in my app to prevent this in the future but certainly helps to have an exception safeguard!

**Pull request closed without merging**
