### PR TITLE
docs(ngModel.NgModelController): correct the mistake of demos

### PR DESCRIPTION
**Pull request by jasonxia23**
The demo of `$rollbackViewValue()` is kind of different from the doc.

### CODE REVIEW

**Comment by gkalpak** [comment]
Thx for the PR, but the example works as intended. Why do you think it is not?

**Comment by jasonxia23** [comment]
After type the `esc`, example of `$rollbackViewValue()` will set back to empty rather than the previous model value.

**Comment by jasonxia23** [comment]
`I signed it!`

**Comment by gkalpak** [comment]
That is exactly what it is supposed to do (as explained in tge example). Hitting ESC should empty the fields (not reset them to their last committed value).

What the example demonstrates, is the correct way of programmatically updating debounced inputs; i.e. roll back any pending view value updates first (via `$rollbackViewValue()`).

**Pull request closed without merging**
