### PR TITLE
fix(required): correctly validate when required on non-input element

### PR DESCRIPTION
**Pull request by kambleaa007**
# AngularJS is in LTS mode
We are no longer accepting changes that are not critical bug fixes into this project.
See https://blog.angular.io/stable-angularjs-and-long-term-support-7e077635ee9c for more detail.

**Does this PR fix a regression since 1.7.0, a security flaw, or a problem caused by a new browser version?**

**What is the current behavior? (You can also link to an open issue here)**

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change?**

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our [guidelines](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits)
- [ ] Fix/Feature: [Docs](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#documentation) have been added/updated
- [ ] Fix/Feature: Tests have been added; existing tests pass

**Other information**:

### CODE REVIEW

**Review by kambleaa007 — COMMENTED** [review]
Reviewed

**Comment by petebacondarwin** [comment]
I don't think you mean to make this into a PR.

**Comment by kambleaa007** [comment]
I really want to
It's for beginners
Simply di concepts in words

**Comment by petebacondarwin** [comment]
But this PR appears to try to apply the whole of the `master` branch to the `v1.7.x` branch, which cannot be correct :-) Perhaps you were trying to cherry-pick your changes to 1.7.x? Don't worry about that. We can do then when we merge your other PR.

**Pull request closed without merging**
