### PR TITLE
refactor(ngScenario): merge duplicate callback functions of StepFailu…

### PR DESCRIPTION
**Pull request by waitingcheung**
…re and StepError

The callback functions of StepFailure and StepError share the same functionality except that they are different in string literals. They can be merged into one to reduce maintenance efforts.

Remarks:
I am a student who is studying code clones. I try to refactor the code clones in your system and propose the following changes. The proposed changes have passed all unit tests on my machine. Please let me know what you think.

In case the proposed changes do not match your coding style or contain any issues, I would appreciate it if you can let me know how I can improve them. Thank you.

### CODE REVIEW

**Comment by kencheung** [comment]
It is my first time to commit and I have already signed the Contributor License Agreement. Please advice how to resolve it.

Thank you.

Ken

**Comment by gkalpak** [comment]
It LGTM (although keep in mind that `ngScenario` is kind of deprecated/not used any more - I'm not sure if it's used for testing older versions).
Regarding the CLA, make sure you signed it with the same e-mail address as the one appearing on the commit.

@petebacondarwin, what happened to moving `ngScenario` to https://github.com/angular/ngScenario ? Wasn't that the plan ?

**Comment by petebacondarwin** [comment]
We would like to move this module out into its own project so that it can be supported separately, perhaps by the community that use it. Hence https://github.com/angular/ngScenario
We don't have the resources to do this. @kencheung would you be interested in being involved in this.

**Comment by kencheung** [comment]
@petebacondarwin Sure. That sounds good to me.

**Comment by Narretz** [comment]
We've removed ngScenario from core, so this PR is obsolete

**Pull request closed without merging**
