### PR TITLE
Added image with replaced word "World"

### PR DESCRIPTION
**Pull request by SibuStephen**
`13704` image replaced.

### CODE REVIEW

**Comment by gkalpak** [comment]
@SituStephen, you need to have signed the CLA with e-mail of the author of the commit.

**Comment by SibuStephen** [comment]
@gkalpak  Verified CLA.

**Comment by SibuStephen** [comment]
@Narretz , @gkalpak  Please take a look on this PR. Thank you

**Comment by gkalpak** [comment]
LGTM

**Comment by gkalpak** [comment]
Backported to `v1.5.x` (02459a6) and `v1.4.x` (c219a87).

**Pull request closed without merging**
