### PR TITLE
bug($ng): change numberInputType to check for leading decimals

### PR DESCRIPTION
**Pull request by joeenzminger**
add check for leading decimal.  Some browsers swallow leading decimals on
input type="number".

fixes #5680

### CODE REVIEW

**Comment by credifiable** [comment]
Still facing this issue with angular 1.5.7 and FF 47.0.1.

**Comment by gkalpak** [comment]
@credifiable , this issue has been closed. If you still see the problem, please open a new issue providing a live reproduction (e.g. using CodePen, Plnkr etc).

**Comment by jamesvanleuven** [comment]
why is this issue closed? it's clearly not dealt with...

**Comment by gkalpak** [comment]
@jamesvanleuven, the issue is still open: #5680

**Pull request closed without merging**
