### PR TITLE
fix($compile): work around Firefox `DocumentFragment` bug

### LINKED ISSUE #16607: cloneLinkingFn sometimes gets an empty clone with multiple slots
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other 

**Current behavior:**
Since AngularJS 1.7.1 we sometimes see the following behavior in Firefox (Windows, Mac, Release and Nightly), but not in Chrome.

    HTML:
    <some-component>
      <slota>
      .. Tags and text
      </slota>
      <slotb>
      .. Tags and text
      </slotb>
    </some-component>

    Component someComponent:
     transclude: {
        'slota': 'slota',
        'slotb': '?slotb'
     },

     and in the template:
     <li  ng-repeat="item in items"
           ng-click... ng-class 
           ng-transclude="slota">
   
The content of li is sometimes just empty. Approx. one out of 20 tries. When I do the transclusion this way:

     $transclude(scope, function(clone) {
            element.append(clone);
        }, null, 'slota');

clone is sometimes empty, i.e. length===0, which normally means that I did a `<slota></slota>`. 

I tried the AngularJS versions 1.7.2, 1.7.1, 1.7.0 and 1.6.10 and it doesn't work with 1.7.2 and 1.7.1. Every other version is just fine. 

I checked the changes between 1.7.0 and 1.7.1 and tried to revert them in the 1.7..1 code. When I revert the change from this [commit](https://github.com/angular/angular.js/commit/789db83a8ae0e2db5db13289b2c29e56093d967a)m, everything works as before.

So far, I was unable to reproduce this in a Plunkr.  

**AngularJS version:** 1.7.1+

**Browser:** [ Firefox both Release and Nightly on Windows and macOS]

### PR DESCRIPTION
**Pull request by gkalpak**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Browser bug work-around.

**What is the current behavior? (You can also link to an open issue here)**
DOM nodes passed to `compilationGenerator()` will eventually be wrapped in `jqLite`, when the compilation actually happens. In Firefox 60+, there seems to be a `DocumentFragment`-related bug that sometimes causes the `childNodes` to be empty at the time the compilation happens.

**What is the new behavior (if this is a feature change)?**
This commit works around this bug by eagerly wrapping `childNodes` in `jqLite`.

**Does this PR introduce a breaking change?**
No.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our [guidelines](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits)
- [ ] ~~Fix/Feature: [Docs](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#documentation) have been added/updated~~
- [ ] ~~Fix/Feature: Tests have been added; existing tests pass~~

**Other information**:
Fixes #16607.

NOTE:
The wrapped nodes have references to their `DocumentFragment` container. This is "by design", since we want to be able to traverse the nodes via `nextSibling` (in order to correctly handle multi-element directives).

Once the nodes are compiled, they will be either moved to a new container element or the `jqLite` wrapper is release making them eligible for garbage collection. In both cases, the original `DocumentFragment` container should be eligible for garbage collection too.

### CODE REVIEW

**Comment by jbedard** [comment]
Did you find any FF bug to reference?

**Comment by gkalpak** [comment]
No, I couldn't find anything 😞

**Review by Narretz — CHANGES_REQUESTED** [review]
LGTM, except that this is a fix instead of a refactor.

**Comment by gkalpak** [comment]
Updated the commit message.

**Review by Narretz — APPROVED** [review]

**Comment by Narretz** [comment]
Just thought about this more ... should there be a  `// Support: Firefox 60` comment in the code? Ofc it's unlikely that we will touch this again even if the bug is fixed, but you never know.

**Comment by gkalpak** [comment]
I thought about this. I decided not to include a comment, since we are really not doing something special (in the sense that `compile` will eventually wrap the nodes in `jqLite()`; we are just doing it sooner, hence the original `refactor` type). But I was on the fence - happy to include a comment if you think it is more appropriate.

**Comment by Narretz** [comment]
Ok, let's jsut merge as is

**Pull request closed without merging**
