### PR TITLE
fix(linky): do not throw on non-string values

### LINKED ISSUE #13547: ngSanitize linky filter throws error if `text` is truthy but not a string
http://jsfiddle.net/an710xcL/16/

Stacktrace thrown in that fiddle:
```
TypeError: l.match is not a function
    at https://code.angularjs.org/1.4.8/angular-sanitize.min.js:15:169
    at fn (eval at <anonymous> (http://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.8/angular.js:13365:15), <anonymous>:4:159)
    at regularInterceptedExpression (http://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.8/angular.js:14446:55)
    at Object.expressionInputWatch [as get] (http://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.8/angular.js:14347:26)
    at Scope.$digest (http://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.8/angular.js:15888:40)
    at Scope.$apply (http://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.8/angular.js:16160:24)
    at bootstrapApply (http://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.8/angular.js:1679:15)
    at Object.invoke (http://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.8/angular.js:4523:17)
    at doBootstrap (http://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.8/angular.js:1677:14)
    at bootstrap (http://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.8/angular.js:1697:12)
```

If looping an array or dictionary and linkying each value, it would be nice if mixed types didn't fail. 

A simple workaround for now is to cast before passing to linky, e.g:
```
var text = 42;
$filter('linky')(''+text);
```

### PR DESCRIPTION
**Pull request by gkalpak**
Fixes #13547

### CODE REVIEW

**Comment by gkalpak** [comment]
I am not sure we want to fix this actually. We've been moving in the opposite direction with other filters lately (e.g. `filterFilter` and `orderBy` throwing if not passed an array).

In any case, I think it's better to either explicitly throw (as with other filters) or return the input unchanged, if it's not a string.

**Comment by lgalfaso** [comment]
I am leaning towards not making this change, but I am fine if enough people wants this change

**Comment by gkalpak** [comment]
@lgalfaso, do you think we should explicitly throw (a la https://github.com/angular/angular.js/blob/v1.5.0-rc.0/src/ng/filter/filter.js#L136) ?

**Comment by lgalfaso** [comment]
@gkalpak with the right BC notice, yes, I think that that way is much better

**Comment by petebacondarwin** [comment]
OK @gkalpak - let's go with throwing in non-sensical cases...

**Comment by gkalpak** [comment]
Closing in favor of #13693.
@lgalfaso, @petebacondarwin, feel free to take a look at #13693 :smile:

**Pull request closed without merging**
