### PR TITLE
Add CDNJS version badge in readme

### PR DESCRIPTION
**Pull request by x09326**
This will add the badge to show its version on CDNJS and also link to its page on CDNJS!

### CODE REVIEW

**Comment by x09326** [comment]
I signed it!

**Comment by gkalpak** [comment]
Since this is not something the team is actively involved in/in control of, I would rather not have this badge listed. I'll leave it open for a while to see what others think.

**Comment by Narretz** [comment]
Also not a big fan. The angular versions are picked up by various CDNs, and the only one we are involved with is the google cdn.

**Comment by petebacondarwin** [comment]
We also use unpkg for our examples.
Given that we only show the build status and not the raft of other possible badges that are available then I agree we should not land this.

**Pull request closed without merging**
