### PR TITLE
docs(tutorial/3 - Components): Adding Tag to Angular Mapping Info

### PR DESCRIPTION
**Pull request by joej164**
I was confused when reading the tutorial on how the HTML phone-list tag was mapped to the AngularJS component name.  Once I figured out it was the line of code that did this and how, I figured clarification would be helpful to other people.  

Also, I initially thought the tag mapping was done at the filename since that was the only thing in the javascript that matched the HTML tags.

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

**What is the current behavior? (You can also link to an open issue here)**

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change?**

**Please check if the PR fulfills these requirements**
- [ X] The commit message follows our [guidelines](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits)
- [ ] Fix/Feature: [Docs](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#documentation) have been added/updated
- [ ] Fix/Feature: Tests have been added; existing tests pass

**Other information**:

### CODE REVIEW

**Comment by joej164** [comment]
I signed it!

**Comment by gkalpak** [comment]
It is super-awesome that you came back to improve things for others once you figured it out yourself. A true [bridge builder][1] 💯 

##
That said, I feel that this is adequately explained [earlier in that step][2]:

> Remember that (since components are also directives) the name of the component is in `camelCase`
> (e.g. `myAwesomeComponent`), but we will use `kebab-case` (e.g. `my-awesome-component`) when
> referring to it in our HTML. (See [here][case-styles] for a description of different case styles.)

Then, [a little further below][3]:

> Let's see an example:
>
> ```js
> ...
> component('greetUser', { ... });
> ```
>
> Now, every time we include `<greet-user></greet-user>` in our view, AngularJS will expand it into a
> DOM sub-tree constructed using the provided `template` and managed by an instance of the specified
> controller.

##
WDYT?

[1]: https://medium.com/@frosty/become-a-bridge-builder-dc45824e590e
[2]: https://github.com/angular/angular.js/blob/4a0208ea73c1d44628bcd00e3e0bde3b132e195b/docs/content/tutorial/step_03.ngdoc#L70-L72
[3]: https://github.com/angular/angular.js/blob/4a0208ea73c1d44628bcd00e3e0bde3b132e195b/docs/content/tutorial/step_03.ngdoc#L78-L93

**Comment by joej164** [comment]
Hello,

My big issue with that was, in hindsight the documentation made sense, but
reading the first time it was not clear.

I was thinking a concrete code example showing the mapping of the
Javascript to the html tag would be helpful for initial understanding.

When I was trying to figure out how the mapping worked, I initially thought
that the mapping was occurring at the file level because the javascript
file (phone-list.component.js) name was the only thing
that had the HTML tag (<phone-list></phone-list>) in it.

It took me having the code up and changing things(trial and error) in the
javascript file before I realized that there was a CamelCase to Kebab case
conversion that was not clear on first read.

Even maybe a Note in the first section linked above stating that the "Camel
Case component name in line 6 of phone-list.component.js is what defines
the kebab-case phone-list tag in line 15 of index.html"
something like that would have made the understanding for a first time
reader a bit easier I think.

My background...
I'm a former telephony engineer moved into a Python Developer role in my
company within the last year.  The project I'm working on is using
Angular.js 1.5 for the front end, so I'm having to learn Angular.js and I'm
not coming into it with alot of understanding software documentation
background.

Let me know what you think.  Hopefully providing a bit of my thought
process and the problems I was having at that point might help with what I
was trying to get at.  I'm happy to tweak/modify if you think a better way
can be found.  Also if you'd rather not merge the PR, I understand as well.

Thanks for your time reviewing my PR either way.

Joe

**Comment by gkalpak** [comment]
Sorry for the late response, @joej164. (On the bright side, the tutorial is now updated (using newer versions of Angular/jQuery, using `npm` for monaging dependencies (instead of the deprecated `bower`), etc.) :tada:)

I can't argue with the fact that you missed this bit of information on first read, so making sure people don't miss this link is important.
But, instead of adding a third mention of it, I would rather make it more clear in one of the previous mentions (see https://github.com/angular/angular.js/pull/16740#issuecomment-432678128).

WDYT, about adding a more explicit explanation or `alert-info` div there?

**Comment by joej164** [comment]
Yes, that works, i think all that is missing in the alert-info div for a newbie is an explicit example of the new element used in some HTML.  I'll take a stab that and update my PR and see what you think.

**Comment by joej164** [comment]
Alright so I did an update from my work computer and it now has my work email address listed as a contributer.  While I could sign the CLA, i'm not sure that's a good idea from my work account, so i'm going to close this PR and open another one and reference this from that one.

**Comment by joej164** [comment]
https://github.com/angular/angular.js/pull/16768

As shown above, I updated the changes for this PR in https://github.com/angular/angular.js/pull/16768 to remove a work account of mine as a contributer of the PR.

**Pull request closed without merging**
