### PR TITLE
fix(ngAnimate): ensure that only string-based addClass/removeClass values are applied

### LINKED ISSUE #12458: ngAnimate throws jqLite/jQuery errors if a non-string value is passed as an addClass/removeClass option
This issue came up because of Material, however it is very hard to debug and ngAnimate should just check for this on its own.

### PR DESCRIPTION
**Pull request by matsko**
Closes #12458

### CODE REVIEW

**Comment by petebacondarwin** [comment]
@matsko - looks good but I think the implementation could be DRYer with a helper:

```js
function addRemoveClassesPostDigest(element, add, remove) {
  var data = postDigestQueue.get(element);
  var dataSet = false;
  var classVal;

  var updateData = function(classes, value) {
    var changed = false;
    if (classes) {
      add = isString(classes)
             ? classes.split(' ')
             : isArray(classes) ? classes : [];
      forEach(classes, function(className) {
        if (className) {
          changed = true;
          data[className] = value;
        }
      });
    }
    return changed;
  };

  if (!data) {
    postDigestQueue.put(element, data = {});
    postDigestElements.push(element);
  }

  dataSet = updateData(add, true);
  dataSet = dataSet || updateData(remove, false);


  if (!dataSet || postDigestElements.length > 1) return;

  ...

```

**Comment by ThomasBurleson** [comment]
@matsko, @petebacondarwin - Love the DRY refactor! Question: no support for `functions that return strings`?

**Comment by matsko** [comment]
@petebacondarwin the code has been updated. Please double check and merge in.

**Comment by petebacondarwin** [comment]
LGTM

**Comment by petebacondarwin** [comment]
Landed. Thanks @matsko.
Although I did tweak the test because I felt that it was clearer to have two `it` clauses with no conditional logic than the `they` clause. Hope you don't mind!

**Comment by petebacondarwin** [comment]
Doh! I only changes one of the test. Sorry.

**Comment by matsko** [comment]
Thank you sir :)

**Pull request closed without merging**
