### PR TITLE
chore(travis): update browsers to the latest version

### PR DESCRIPTION
**Pull request by lgalfaso**
Update the used browsers to the latest versions available

### CODE REVIEW

**Comment by petebacondarwin** [comment]
@lgalfaso - there appear to be two fixes in this commit.
One is related to a bug in Safari I believe? (The old 2px thing). I think this should be in a separate commit.

**Comment by lgalfaso** [comment]
Newer versions of Safari do not update the calculated properties (after a programatic css change) synchronously. The change to the test is needed to make it pass in Safari (I can make it 2 commits, but just the browser update without the change on the test will make the test fail in Safari)

**Comment by petebacondarwin** [comment]
You can always have commits that fail followed by commits that fix them as long as they are pushed together. But in this case, it is not needed. We just put the "fix" commit first.

**Comment by petebacondarwin** [comment]
I guess we backport to 1.3.x

**Pull request closed without merging**
