### PR TITLE
Angular.equals - Adding an example.

### PR DESCRIPTION
**Pull request by SHAHRUKH-KHAN**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Doc Update

**What is the current behavior? (You can also link to an open issue here)**

No Example. - https://docs.angularjs.org/api/ng/function/angular.equals

**What is the new behavior (if this is a feature change)?**

Adds a example

**Does this PR introduce a breaking change?**
No

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Other information**:

This Pull requests improves the doc by adding an example to `angular.equals` function.

### CODE REVIEW

**Comment by robinj** [comment]
I think the code needs a little reformatting to make it more consistent. e.g spacing between commas and parameters and a spacing between an object and attribute names.

**Comment by SHAHRUKH-KHAN** [comment]
[safari 7 OS X 10.9 #3] PID: 4379
[safari 7 OS X 10.9 #3] Using SauceLabs selenium server at http://ondemand.saucelabs.com:80/wd/hub
[safari 7 OS X 10.9 #3] FFFFFFFFFFFFF
[safari 7 OS X 10.9 #3] 
[safari 7 OS X 10.9 #3] Failures:
[safari 7 OS X 10.9 #3] 
[safari 7 OS X 10.9 #3]   1) doc.angularjs.org API pages should display links to code on GitHub
[safari 7 OS X 10.9 #3]   at 31.097s [Tue, 15 Mar 2016 05:02:04 GMT]
[safari 7 OS X 10.9 #3]    Message:
[safari 7 OS X 10.9 #3]      ScriptTimeoutError: Timed out awaiting response to command "executeScript" after 30001 ms (WARNING: The server did not provide any stacktrace information)
[safari 7 OS X 10.9 #3] Command duration or timeout: 30.01 seconds
[safari 7 OS X 10.9 #3] Build info: version: '2.48.0', revision: 'b7b081a', time: '2015-10-07 15:48:56'
[safari 7 OS X 10.9 #3] System info: host: 'itako46197.prod.miso', ip: '172.20.46.197', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.5', java.version: '1.8.0_74'
[safari 7 OS X 10.9 #3] Driver info: org.openqa.selenium.safari.SafariDriver
[safari 7 OS X 10.9 #3] Capabilities [{browserName=safari, takesScreenshot=true, javascriptEnabled=true, version=7.0.6, cssSelectorsEnabled=true, platform=MAC, secureSsl=true}]
[safari 7 OS X 10.9 #3] Session ID: null
[safari 7 OS X 10.9 #3]    Stacktrace:
[safari 7 OS X 10.9 #3]      ScriptTimeoutError: Timed out awaiting response to command "executeScript" after 30001 ms (WARNING: The server did not provide any stacktrace information)
[safari 7 OS X 10.9 #3] Command duration or timeout: 30.01 seconds
[safari 7 OS X 10.9 #3] Build info: version: '2.48.0', revision: 'b7b081a', time: '2015-10-07 15:48:56'
[safari 7 OS X 10.9 #3] System info: host: 'itako46197.prod.miso', ip: '172.20.46.197', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.5', java.version: '1.8.0_74'
[safari 7 OS X 10.9 #3] Driver info: org.openqa.selenium.safari.SafariDriver
[safari 7 OS X 10.9 #3] Capabilities [{browserName=safari, takesScreenshot=true, javascriptEnabled=true, version=7.0.6, cssSelectorsEnabled=true, platform=MAC, secureSsl=true}]
[safari 7 OS X 10.9 #3] Session ID: null
[safari 7 OS X 10.9 #3]     at Array.forEach (native)
[safari 7 OS X 10.9 #3] From: Task: Asynchronous test function: it()
[safari 7 OS X 10.9 #3] Error
[safari 7 OS X 10.9 #3]     at [object Object].<anonymous> (/home/travis/build/angular/angular.js/docs/app/e2e/api-docs/api-pages.scenario.js:7:5)
[safari 7 OS X 10.9 #3]     at [object Object].<anonymous> (/home/travis/build/angular/angular.js/docs/app/e2e/api-docs/api-pages.scenario.js:5:3)
[safari 7 OS X 10.9 #3]     at Object.<anonymous> (/home/travis/build/angular/angular.js/docs/app/e2e/api-docs/api-pages.scenario.js:3:1)

How to tackle this :(

**Comment by SHAHRUKH-KHAN** [comment]
@Narretz What about this request ? Does it need any improvements ?

**Comment by Narretz** [comment]
Thanks, merged. There was a typo in the end (missing / in the closing example), otherwise okay. Just remember for the next time, squash all commits into one.

**Pull request closed without merging**
