### PR TITLE
add standalone months to ngLocale

### PR DESCRIPTION
**Pull request by Narretz**
Cleaned up version of #3744. We could also add STANDALONESHORTMONTHS, but I don't think that's worth it.

### CODE REVIEW

**Comment by lgalfaso** [comment]
this looks fine, but do you plan on adding the support for this at `dateFilter`?

**Comment by Narretz** [comment]
I didn't think of that at all actually. I proposed it because a few people pointed out that it wasn't available. Can we add the support for dateFilter at a later time?

**Comment by petebacondarwin** [comment]
LGTM - merging

**Comment by petebacondarwin** [comment]
(For some reason the second commit added a full stop after `kr` currencies. I have reverted those changes when merging.)

**Pull request closed without merging**
