### PR TITLE
`component()` helper changes

### PR DESCRIPTION
**Pull request by petebacondarwin**

### CODE REVIEW

**Comment by gkalpak** [comment]
[The docs][1] still seem to imply that `restrict: 'E'` is just a configurable default (rather than an enforced value). Maybe we should be more explicit about it being non-configurable (e.g. remove the `default bahavior like` part).

LGTM otherwise.

[1]: https://github.com/angular/angular.js/pull/13741/files#diff-a732922b631efed1b9f33a24082ae0dbR983

**Comment by petebacondarwin** [comment]
OK, I'll improve the docs.

**Comment by Mischi** [comment]
removing the ability to set the `restrict` option makes angular.component()'s unusable with the new ngComponentRouter until the router will support `elements` next to `attributes` ...

See #13603

**Comment by petebacondarwin** [comment]
@Mischi that is actually a problem with the router that needs to be fixed. @btford ?

**Comment by AIMMOTH** [comment]
Why remove element? How do you preserve DOM structure which is important for SEO?

**Comment by petebacondarwin** [comment]
@AIMMOTH not sure I understand what you mean.

**Comment by AIMMOTH** [comment]
@petebacondarwin Recommendations is that the DOM structure should be arranged for SEO. For instance <article></article> should be used. If this article is a component, it was possible to add the component as attribute <article component></article> but now you need to destroy DOM structure with <component></component>

Or have I missed something?

**Pull request merged**
