### PR TITLE
fix(date filter): display localised era for `G` format code

### LINKED ISSUE #10503: angular-i18n has wrong dateformat in Thai.
The fulldate format in **angular-locale_th-th.js** and **angular-locale_th.js** are wrong.
Current value is "fullDate": "EEEE\u0e17\u0e35\u0e48 d MMMM G y",

Example : <dd id="checkIn">{{landingViewModel.bookingInfo.checkIn | date : 'fullDate'}}</dd>
It will generate a date like this "วันพุธที่ 17 ธันวาคม G 2014", 
which the G letter should be "พ.ศ." if year is 2557 Buddhist Era (BE)
and for A.D. 2014 it should be "ค.ศ."
or you can remove the G letter it will correct as well.

### PR DESCRIPTION
**Pull request by petebacondarwin**
Fixes #10503

### CODE REVIEW

**Comment by lgalfaso** [comment]
the patch is too big, so I cannot see if you modified the built-in locale. If you want to add the long names for eras, please use http://unicode.org/reports/tr35/tr35-dates.html#Date_Field_Symbol_Table as a reference.
Otherwise, please rebase this and LGTM

**Comment by petebacondarwin** [comment]
@lgalfaso - thanks for taking the time to review. The PR has three commits.  You probably want to look at ff69230e609a1153a9afddb51ee6526db9302dbc and ba384211314fee0999eb452564a5e54ec2c108ee

**Comment by lgalfaso** [comment]
LGTM

**Comment by petebacondarwin** [comment]
Added support for GG, GGG and GGGG
Removed ddescribe
Improved commit msgs

**Pull request closed without merging**
