### PR TITLE
docs(tutorial/Tutorial): First page of documents detail addition regarding node js

### PR DESCRIPTION
**Pull request by MrChriZ**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
docs update

**What is the current behavior? (You can also link to an open issue here)**

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change?**
No

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**Other information**:
On my system at least the node command did not work in my bash shell after freshly installing Node.JS. 
After restarting bash it must have picked up an updated path variable.

### CODE REVIEW

**Comment by MrChriZ** [comment]
I signed it

**Comment by gkalpak** [comment]
I feel that this kind of detail is out of scope for the tutorial (not to mention that different OS/versions may have different requirements).

Thx for taking the time to submit a PR :+1:
Keep 'em coming !

**Comment by MrChriZ** [comment]
Thanks Georgios - just for reference though the very next line is OS dependent and therefore beyond the scope of the tutorial:"In Debian based distributions, there might be a name clash with another utility called node. The suggested solution is to also install thenodejs-legacy apt package, which renames node to nodejs.apt-get install nodejs-legacy npm
nodejs --version npm --version"

So maybe those lines should be deleted too?

**Comment by gkalpak** [comment]
I think those were added at a time when Node.js wasn't so popular. TBH, I currently don't use the `nodejs-legacy` package on Debian - not sure if it's necessary any more.

If you ask me, I would gladly remove that comment too (because out of scope), but others might object :grin:

**Pull request closed without merging**
