### PR TITLE
docs(angular-mocks): replace $rootScope with scope

### PR DESCRIPTION
**Pull request by marcin-wosinek**
use scope instead of $rootScope in the code example

### CODE REVIEW

**Comment by Narretz** [comment]
Why not `$rootScope.$new()`? then you don't have to use the injector.

**Comment by marcin-wosinek** [comment]
I need to get the $rootScope in some way. So the other option would be:
```js
var scope, $rootScope;
/* ... */
$rootScope = $injector.get('$rootScope');
scope = $rootScope.$new();
```

**Comment by Narretz** [comment]
Yeah, sorry I didn't see that the $rootScope was not available before.

**Comment by caitp** [comment]
i'm not sure this is that useful, I think for documentation purposes, it's better to clearly spell out the services being used. In real apps, you can test it however you want of course

**Comment by caitp** [comment]
@Narretz if you agree please close it, otherwise land at will

**Comment by Narretz** [comment]
@marcin-wosinek What was your goal in changing this? Do you think this reflects testing reality more? Angular core uses both in tests, $rootScope and a derived scope.

**Comment by marcin-wosinek** [comment]
I was confused by the $rootScope in test code. The controller doesn't use any $methods from scope, and even empty object would be enough for the test to work. Because of $rootScope in the test code I was searching for some hacks related to promise resolution - as $rootScope.$digest() when testing code that uses $q

**Comment by Narretz** [comment]
I thought about this again and I have agree with @caitp that replacing rootScope with scope doesn't add much clarity to the test. Nevertheless, thanks for your contribution!

**Pull request closed without merging**
