### PR TITLE
docs(guide/Expressions): Redirection to MDN

### PR DESCRIPTION
**Pull request by franciscovelez**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
docs update

**What is the current behavior? (You can also link to an open issue here)**

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change?**

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**Other information**:

It is better to link to the English version of MDN rather than German version

### CODE REVIEW

**Comment by franciscovelez** [comment]
I signed it!

**Comment by Narretz** [comment]
I agree. Or maybe simply leave out the local modifier? That works too

**Comment by franciscovelez** [comment]
I think that is better use the local modifier to avoid the 301 redirection from "no local modifier" to "en-US" page

**Comment by Narretz** [comment]
Ok, that makes sense. Regarding the CLA, did you sign it with the same email with which you authored the commit? Otherwise it won't detect it.

**Comment by franciscovelez** [comment]
OK, I have signed the CLA with my other email

**Pull request merged**
