### PR TITLE
chore(travis): add commitplease validation to ci-checks

### PR DESCRIPTION
**Pull request by Narretz**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
chore

**What is the current behavior? (You can also link to an open issue here)**
PR commit messages are not validated

**What is the new behavior (if this is a feature change)?**
travis validates PR commit messages

**Does this PR introduce a breaking change?**
No

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format 😆 

**Other information**:

### CODE REVIEW

**Review by petebacondarwin — DISMISSED** [review]
How come this PR doesn't fail its own commitplease checks, since you have a `squash me` commit in there?
I don't think CI should pass for such commits.

**Comment by Narretz** [comment]
I saw this more as a help for contributors to check their PR commit message validity. PRs must be merged manually anyway and since we can squash via the UI I think it's unnecessary to require a full commit message on each fixup / squash.

**Comment by gkalpak** [comment]
I think fixup/squash commits are fine (contributors don't use them that much anyway :smiley:), but `commitplease` will also accept `WIP` and `Merge branch/<SHA>...` as valid, which isn't ideal.

<sub>(Given that this is an extra check compared to what we had before, I don't mind it being less strict.)</sub>

**Review by petebacondarwin — APPROVED** [review]

**Comment by Narretz** [comment]
I've opened an issue about WIP / Merge in the commitplease REPO. It's odd that this is hardcoded: https://github.com/jzaefferer/commitplease/issues/101

If you're being strict, Angular style commit message actually disallows Merge commits

**Pull request merged**
