### PR TITLE
docs: adding languages for code blocks that don't have

### LINKED ISSUE #15356: docs: Some of code examples in CHANGELOG.md are missing language
There are code examples in the CHANEGLOG.md that are not highlighted due to missing language in the code blocks.

### PR DESCRIPTION
**Pull request by NoHomey**
fixes #15356.

### CODE REVIEW

**Comment by NoHomey** [comment]
It looks like you've already signed this CLA. If you'd like to edit your contact information, you may do so below.

**Comment by NoHomey** [comment]
I signed it!

**Comment by gkalpak** [comment]
You have used the same author-email for the commit as for signing the CLA, right? (Just making sure :grin:)

**Comment by gkalpak** [comment]
@NoHomey, can you make sure the commit message adheres to our [commit guidelines][1]?
Other than that LGTM.

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit

**Comment by NoHomey** [comment]
@gkalpak thanks for the reminder for the email I actually did not configured git before commiting (did it in a hurry during the brake in the university, totally forgot about it :smiley:) .

**Pull request closed without merging**
