### PR TITLE
docs($http): Fix default $http cache name

### PR DESCRIPTION
**Pull request by oliversalzburg**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
docs update

**What is the current behavior? (You can also link to an open issue here)**

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change?**
No

**Please check if the PR fulfills these requirements**
- [X] The commit message follows our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [ ] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

**Other information**:

The name of the cache is actually the string "$http", not the symbol itself. https://github.com/angular/angular.js/blob/master/src/ng/http.js#L380

### CODE REVIEW

**Comment by gkalpak** [comment]
@googlebot , you there? Mind taking a look at this one?

**Comment by gkalpak** [comment]
@oliversalzburg , would you mind posting anything here to see if you can draw @googlebot's attention?

**Comment by oliversalzburg** [comment]
Hey @googlebot, I'm over here. Look at me!

**Comment by gkalpak** [comment]
It worked!

**Pull request closed without merging**
