### PR TITLE
docs: change "Google Inc." to "Google LLC"

### PR DESCRIPTION
**Pull request by gkalpak**
For more information, see For more information, see https://www.bloomberg.com/news/articles/2017-09-01/alphabet-wraps-up-reorganization-with-a-new-company-called-xxvi.

(Inspired by angular/angular#19671 :smiley:)

### CODE REVIEW

**Comment by petebacondarwin** [comment]
Only 6 changed files? Angular had over 2500!

**Review by petebacondarwin — APPROVED** [review]
I assume that you have done a comprehensive search @gkalpak :-)

**Comment by Narretz** [comment]
The commit message is incorrectly formatted 😱

**Comment by petebacondarwin** [comment]
Too much time spent on the angular/angular repo!

**Comment by Narretz** [comment]
Actually, is it correct to say 2010 - 2017 Google LLC, if Google just became a LLC this year? 🤔

**Comment by gkalpak** [comment]
No idea. I will hold off, until angular/angular#19671 is finalized/merged :smiley:

**Comment by Narretz** [comment]
Looks like the way to go is to remove the year(s) completely: https://github.com/angular/angular/pull/19671#discussion_r144376767

**Comment by Narretz** [comment]
The Angular PR was never merged, and this is now stale. Closing for now.

**Pull request closed without merging**
