### PR TITLE
feat(rootScope): allow $apply expressions to prevent unnecessary digest

### PR DESCRIPTION
**Pull request by shahata**
This allows, for example to prevent unnecessary digest in ngClick handler function in case the handler does not have any immediate side effects.

Closes #8286

### CODE REVIEW

**Comment by lgalfaso** [comment]
The main issue with this PR is that `$rootScope` already provides all the APIs to do partial digest and no digest at all. We should not be adding 10s of lines of code to `$rootScope`, and duplicate functionality already present there so a directive does not need to add 1-2 lines of code

**Comment by shahata** [comment]
I agree that the purpose of this change is only so that people will not have to duplicate directives, but I think it is a common enough use case that we can provide them the tools they need and not force them to duplicate code.

**Comment by lgalfaso** [comment]
Adding duplicate code/multiple ways to do the same thing in a critical component as it is `$rootScope`, is not nice.
BTW, there are too many edge cases that we should not care about. Eg, what should we do in each of these?
```
ng-click="a = 1; $partialDigest(); $partialDigest($parent.$nextSibling)"
ng-click="a = 1; $partialDigest(); $AbortDigest()"
```

**Comment by lgalfaso** [comment]
Merging this would make the migration to Angular 2 harder. I am going to close this.

In case I am missing something, feel free to reopen this issue

**Comment by dragosrususv** [comment]
I would have envisioned this with a lot less simpler interface. Just adding some options similar to ng-model-options to the directives themselves:
Example
<div ng-mouse-enter="onMouseEnter()" ng-options="{runApply: false}"

The above gives more power over the mechanics under the hood, but that is fine too as long as it fixes the problem.

@lgalfaso : Excuse me to say, but I find it very hard to understand your mode of thinking. These are problems that the community are facing TODAY and you are closing a PR on a project which will probably not be maintained in 2 years and you are pointing out to a FUTURE AngularJS 2.0 project in which NOBODY could implement anything as of today. **How is this helping? What am I missing here?**

**Comment by realityking** [comment]
@dragosrususv that wouldn't work with multiple  event handler when only some should skip the digest

**Comment by dragosrususv** [comment]
@realityking - touche. ng-mouse-enter-options? :)
I wanted to make it easier for @shahata because he's a nice guy :)

**Comment by lgalfaso** [comment]
@dragosrususv I understand that this might be frustrating, but not everything belongs to the core. In this specific case, if you think that there is a big need for directives that would handle events without triggering `$apply`, then create a module with such directives and put it in github. There are no core changes needed just normal directives.

**Comment by dragosrususv** [comment]
@lgalfaso : normal directives trigger a $digest/refresh on the whole application instead of just the current $scoping area. PERF wise, that's a disaster. And AngularJS has the right tools to fix this, even if backward compatibility is kept.

Still, I do agree that people who actually have this problem (or find the root cause of it!) would fall into the 2% category and it should only be added in framework as an option at most. I'll think about adding a module with such light directives, but I would prefer for people to have this by default instead of adding another bower dep.

**Comment by lgalfaso** [comment]
@dragosrususv I understand this may be frustrating, but there are two camps here:
* Developers who think that is a feature makes sense for a given % of developers, then it should be in the core
* Developers that think that Angular core should be small as they are already struggling with the download size of their application, and adding more features that they do not use adds bytes to the app download

Given that it is a lot easier to just add another library than to selectively remove chunks to save bytes, is that before something is added, we are forced to think several times
* Is this something that belongs to the core?
* Can this be done thru a third party module?
* What would be the impact on the previous two camps

**Pull request closed without merging**
