### PR TITLE
docs(modules):  example of testing run blocks

### LINKED ISSUE #12706: How do you test the run block?
http://stackoverflow.com/questions/32169240/how-should-the-run-block-be-dealt-with-in-angular-unit-tests

Would be useful to include a section on it in the [Unit Testing Guide](https://docs.angularjs.org/guide/unit-testing).

### PR DESCRIPTION
**Pull request by iamisti**
Add:
- example to the documentation of unit testing run blocks.

Closes #12706

### CODE REVIEW

**Comment by petebacondarwin** [comment]
My personal view is that you should not put code that needs unit testing in run blocks. Move it to a service, test it there, then simply call it from a run block. So I would rather not merge this as it implies that we would recommend such a practice.

**Comment by iamisti** [comment]
@petebacondarwin I agree with you. Best practice is not having code in run blocks. But still even if you have your logic behind a service method, you might want to check if you call that service in your run block (making sure that nobody will just simply remove it with a refactor or whatever).

**Comment by petebacondarwin** [comment]
Well you can check this by simply loading the module into the injector. By definition that will run the modules run blocks.

**Comment by iamisti** [comment]
@petebacondarwin so true! :) Thanks for clarifying that.

**Pull request closed without merging**
