### PR TITLE
Added hasBody to ngResource action configuration

### PR DESCRIPTION
**Pull request by yathos**
I would love to have a "hasBody" attribute on the action configuration of ngResource to be able to specify if a configured action requires a body.

### CODE REVIEW

**Comment by yathos** [comment]
I signed it!

**Comment by yathos** [comment]
I signed it!

**Comment by kaufholdr** [comment]
You are mistaken. I wrote this commit.

**Comment by yathos** [comment]
I authored these commits

**Comment by yathos** [comment]
I authored these commits

**Comment by kaufholdr** [comment]
I'm okay with the contribution of this commit.

**Pull request closed without merging**
