### PR TITLE
avoid publishing new releases to deprecated bower

### PR DESCRIPTION
**Pull request by graingert**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
N/A

**What is the current behavior? (You can also link to an open issue here)**
bower install angular
* installs latest version of angularjs *

**What is the new behavior (if this is a feature change)?**
bower install angular
installs old version of angular

**Does this PR introduce a breaking change?**
yes, no new bower releases.

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Other information**:

### CODE REVIEW

**Comment by graingert** [comment]
This will probably require some doc fixes for how people can transition to npm based angular, eg use `/node_modules/` rather than `/bower_components/`

**Comment by graingert** [comment]
currently this PR stops all new releases to bower, however it might be better to release 1.7 and above only on npm.

**Comment by gkalpak** [comment]
TBH, I don't see the benefit in doing so. Although not recommended for use in new projects, bower is still maintained and there are people using it. Given the next-to-zero overhead for us, I don't see why we should make the lives of people still using bower more difficult than they already are 😈

**Comment by graingert** [comment]
@gkalpak perhaps to start this off, I could make a PR that updates the tutorial to use plain old npm

**Comment by gkalpak** [comment]
Well, that would be nice, but...the tutorial uses `angular-seed` as a starting point, so we need to update [angular/angular-seed][1]. And there are currently three PRs open for that ([#385][2], [#389][3], [#390][4]) :flushed:

We should get one of those in (probably #390) and _then_ you could work on the tutorial :grin:

[1]: https://github.com/angular/angular-seed
[2]: https://github.com/angular/angular-seed/pull/385
[3]: https://github.com/angular/angular-seed/pull/389
[4]: https://github.com/angular/angular-seed/pull/390

**Comment by graingert** [comment]
@gkalpak #390 is closed

**Comment by gkalpak** [comment]
Wrong link. Try again :)

**Comment by dcherman** [comment]
Is there a cost to supporting bower?  It seems needlessly breaking to stop publishing to it even if it is deprecated, especially since it's probably an automated process that is doing so.

**Comment by Narretz** [comment]
I agree that stopping publishing to bower is a needless BC. I also agree that we can point out the deprecation where possible, but let's not track this in this PR.

**Pull request closed without merging**
