### PR TITLE
feat($http): remove deprecated callback methods: `success()/error()`

### PR DESCRIPTION
**Pull request by gkalpak**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Feature removal (refactor but with a breaking change).

**What is the current behavior? (You can also link to an open issue here)**
The promises returned by `$http` have additions, non-standard methods: `success()`, `error()`. They have beed deprecated since v1.4.4 (#12112).
Although there was a switch to disable them (`$httpProvider.useLegacyPromiseExtensions()`), they were enabled by default.

**What is the new behavior (if this is a feature change)?**
`success()` and `error()` are gone. Use the standard `then()`/`catch()` promise methods instead.

**Does this PR introduce a breaking change?**
Yes.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**Other information**:
- [ ] Add a note to the v1.5.x docs that the methods/switch will be removed in v1.6.0.

### CODE REVIEW

**Comment by Narretz** [comment]
Were all docs updated when this feature was deprecated? Otherwise we'd have to check that.

**Comment by gkalpak** [comment]
Good point. I saw there were docs updates in #12112, so I assumed all docs were updated.
It turns out there was one last survivor in `$sce`'s docs :smiley:

**Comment by Narretz** [comment]
LGTM.
Minor note: in the commit message BC notes, you advise using .catch for error handling, but you don't mention the second argument of then (the error handler fn). Is this on purpose?
Did you talk about the consequences in the meeting? We rarely removed deprecated features. What's the consensus on the impact of this change?

**Comment by gkalpak** [comment]
> In the commit message BC notes, you advise using `.catch` for error handling, but you don't mention the second argument of `then` (the error handler fn). Is this on purpose?

Yes and no. I don't specifically advise using `.catch` to replace `.error`. I have a generic statement that you should use `then`/`catch` now and I have one example, where `.error` is replaced by `.catch` (because in that particular example it is more straight-forward).

Pedantically speaking, `.then(onSuccess, onError)` is semantically closer to `.success(onSuccess).error(onError)`. But only because `.success`/`.error` were bad APIs :smiley: What people usually want is `.then(onSuccess).catch(onError)` (which is **not** equivalent to `.success(...).error(...)`).

So, while I didn't mean to explicitly advice people replacing `.success(...).error(...)` with `.then(...).catch(...)`, I do think it is good practice (i.e. better than `.then(..., ...)` - unless you know what you're doing).

But I don't feel strongly about it. If you have concerns about the implications of that, I would be happy to discuss :smiley:

--
Did you talk about the consequences in the meeting? We rarely removed deprecated features. What's the consensus on the impact of this change?

We didn't talk much about it. We just agreed it is time for this long-deprecated API to go.
The impact would be the same as with most breaking changes afaict: People will need to migrate their apps to not use the removed feature :smiley:

<sub>BTW, it is not true that we haven't removed other deprecated stuff before (don't judge by `replace: true` - it is a special case 😛 ).</sub>

--
I'll leave this unmerged for the time being and let's revisit on the next meeting to make sure we didn't miss anything.

**Pull request closed without merging**
