### PR TITLE
Angular build

### PR DESCRIPTION
**Pull request by hellofadude**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Bug fix

**What is the current behavior? (You can also link to an open issue here)**

>> Error: Unable to read CDN version, are you offline or has the CDN not been properly pushed?
>> Perhaps you want to set the NG1_BUILD_NO_REMOTE_VERSION_REQUESTS environment variable?
Warning: Task "default" not found. Use --force to continue.

Aborted due to warnings.

**What is the new behavior (if this is a feature change)?**

CDN version (remote): v1.6.5
Current version (remote): v1.6.5
yarn install v0.24.6
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.69s.
Running "bower" task
...

Running "compress:build" (compress) task
>> Compressed 3260 files.

Done.

**Does this PR introduce a breaking change?**

No

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format

**Other information**:

### CODE REVIEW

**Comment by Narretz** [comment]
This change is not correct. You basically just flipped the flag usage. Did you try to build without network acccess?

**Comment by hellofadude** [comment]
not sure why I am still seeing merge conflict on github, any help?

**Comment by hellofadude** [comment]
Narretz  no I did a little more than that. and I will walk you through it

**Comment by hellofadude** [comment]
!!process.env['NG1_BUILD_NO_REMOTE_VERSION_REQUESTS'] returns false because the value of NG1_BUILD_NO_REMOTE_VERSION_REQUESTS  = 1 which can not be converted to boolean.. once you understand this you can follow the logic

**Comment by hellofadude** [comment]
where !!bCondition = bCondition

**Comment by Narretz** [comment]
Yes, you can convert a value of `1` to boolean, that's the whole magic behind it. If `process.env['NG1_BUILD_NO_REMOTE_VERSION_REQUESTS']` is undefined, then `!!` will convert it to boolean `false` (first `undefined` to `true`, then `true` to `false`)
This should also work with numbers and boolean values for the env variable, because it is always a string.

**Comment by hellofadude** [comment]
The only reason you will get underfined is if you need remote access, then you do not set env variable. But if building locally then you must set NG1_BUILD_NO_REMOTE_VERSION_REQUESTS=1. 

underfined is one of those expressions that can be converted to false, that does not mean a number can also be converted to true. 1 is not a "truthy" value and therefore can not be converted to boolean

**Comment by hellofadude** [comment]
especially when used by a operator with only one operand

**Comment by frederikprijck** [comment]
> 1 is not a "truthy" value and therefore can not be converted to boolean

That's not correct, see: https://jsfiddle.net/c0qadpby/1/

As you can see in the plunkr, both 1 and "1" are truthy.

**Comment by hellofadude** [comment]
Narretz, I think we are essentially saying the same thing. 

If building locally then you must set NG1_BUILD_NO_REMOTE_VERSION_REQUESTS=1, which returns false. In that case in getCdnVersion(), we want to be able to flip that value to flip that value to land in the correct closure. .. // We do not want to make any remote calls to the CDN so just use the most recent version

**Comment by Narretz** [comment]
There's a difference between building "locally" and "without requests to the CDN"

You can build locally with requests to the CDN.
If you want to build "without requests to the CDN" you set NG1_BUILD_NO_REMOTE_VERSION_REQUESTS to **any** value. It doesn't have to be 1, any value is alright. And for the reasons me and @frederikprijck have given, the current logic is right. If you have problems, they must come from somewhere else.

**Comment by hellofadude** [comment]
Please read the code

**Comment by frederikprijck** [comment]
> Please read the code

The only (relevant) change that was made was changing `if (NO_REMOTE_REQUESTS) {` to `if (!NO_REMOTE_REQUESTS) {`and that's what we have been elaborating on correctly.

Looking at the code in ur pr, I can walk you through what's happening (and hopefully make u understand it's incorrect):

https://github.com/hellofadude/angular.js/blob/e5373c4f2b9eeee55a2fc12440cfde8592a7d4f7/lib/versions/version-info.js#L11

This changes `"1"` (which is a string due to `process.env`) to `true`.

https://github.com/hellofadude/angular.js/blob/e5373c4f2b9eeee55a2fc12440cfde8592a7d4f7/lib/versions/version-info.js#L151

This evaluates to `if(!true)` which is the same as `if(false)` and will not evaluate correctly.

**Comment by hellofadude** [comment]
@frederikprijck

> This changes "1" (which is a string due to process.env) to true (it also changes any value to true) and sets NO_REMOTE_REQUESTS to true

Have you actually tested this assertion? If so please described how.

**Comment by frederikprijck** [comment]
Did you look at the fiddle I linked above ? See https://github.com/angular/angular.js/pull/16108#issuecomment-315136925

**Comment by hellofadude** [comment]
No I didn't because your assertion is 

>  sets NO_REMOTE_REQUESTS to true

This is not fiddle. Please use test that fit within the context of the angularJS env

**Comment by frederikprijck** [comment]
That assertion is correct. I'm only trying to explain you why this PR is incorrect, there is no need for me to test it in the context of AngularJS, as this has nothing to do with AngularJS in particular. This is all about JavaScript, which can be done in a fiddle.

If you are interested in why this PR will not get merged in its current state, have a look at my explanation and take the time to understand the fiddle.

**Comment by hellofadude** [comment]
I am not sure if that is a very good reason not to merge my pull request, given I am only trying to help.

**Comment by Narretz** [comment]
I'll have to close this PR as everything has been said and it doesn't look like we're not coming to a conclusion here that satifies everyone.
I've also just tested the build locally with the variable set and not set, and it works as expected. In fact, this feature was built because I requested it. ;)

**Comment by hellofadude** [comment]
> This is all about JavaScript, which can be done in a fiddle.

This is not correct because process.env is a node implementation of a javascript global object which you can not possible replicate in fiddle

**Comment by hellofadude** [comment]
You can run this simple test to test - all you need is node.js

In your version-info.js file enter console.log("NO_REMOTE_REQUESTS")

Then do node version-info.js - 

Please share your result. 

Honestly, these things should be looked at objectively based on evidence when deciding whether to accept a PR. We are all after the same thing. To improve the code

**Comment by frederikprijck** [comment]
> Honestly, these things should be looked at objectively and based on evidence when deciding whether to accept a PR. We are all after the same thing. To improve the code

We have been looking into it with two people, explaining what's happening. Given that @Narretz (and me, but @Narretz  in particular) have a lot of experience with the angularjs codebase, we did check this and are confident about our replies.

The log (console.log(NO_REMOTE_REQUESTS)) saying shows `true` for me. If it logs something different for you, there's probably something else going wrong.

**Comment by hellofadude** [comment]
@Narretz - can you please accept PR after testing? - thanks

**Comment by Narretz** [comment]
> I am not sure if that is a very good reason not to merge my pull request, given I am only trying to help.

We welcome all sorts of contributions, but this PR is simply not doing the right thing. I'm sorry if I cannot explain this better.

What happens when you do `node lib/versions/version-info.js` obviously depends on what you have set the environment variable NG1_BUILD_NO_REMOTE_VERSION_REQUESTS to.

- if it is not set, `NO_REMOTE_REQUESTS`  is `false` which is the default and correct
- if it is set to *any*  value, `NO_REMOTE_REQUESTS`  is set to `true` which is also correct

**Comment by hellofadude** [comment]
> The log (console.log(NO_REMOTE_REQUESTS)) saying shows true for me.

I am sorry but I have that hard to believe

**Comment by hellofadude** [comment]
> if it is set to any value, NO_REMOTE_REQUESTS is set to true which is also correct

This is not correct. Please refer back to your Javascript specification. There has to be someway within the system to resolve this matter objectively?

**Comment by Narretz** [comment]
Objectively, the build process with `grunt ...` works as intended when you set the NG1_BUILD_NO_REMOTE_VERSION_REQUESTS environment variable. It doesn't make requests to get the version from the CDN.

The code in the version-info.js file is an implementation detail. You want to change the code, but I'm not even sure why.

You still haven't clearly said what your problem with the build is. Without looking at the code, what is the problem you are facing?

**Comment by hellofadude** [comment]
> You still haven't clearly said what your problem with the build is. Without looking at the code, what is the problem you are facing?

I have explained that in my documentation please see above

**Comment by hellofadude** [comment]
@Narretz 

> The code in the version-info.js file is an implementation detail. You want to change the code, but I'm not even sure why.

Because grunt.js file references version-info.js by testing `if (versionInfo.cdnVersion == null)`

**Comment by hellofadude** [comment]
> the build process with grunt ... works as intended when you set the NG1_BUILD_NO_REMOTE_VERSION_REQUESTS environment variable. It doesn't make requests to get the version from the CDN

This is not correct. If env var is set then  `NG1_BUILD_NO_REMOTE_VERSION_REQUESTS` is 1 and consequently `!!process.env['NG1_BUILD_NO_REMOTE_VERSION_REQUESTS']` returns false because 1 is not a "truthy" value. Please consult your documentation.

> Objectively,

Are you saying you have the final word on this and there is no remedy?

**Comment by frederikprijck** [comment]
I'm not sure where this conversation is leading to. Even tho u claim it to be otherwise, `1` is `truthy` in javascript, there's no need to advice us to read the docs if you're not familiar with falsy and truthyness in javascript. 

As you reject to read my replies and understand my fiddles (which clearly show `1` is `truthy`) I'm going to leave this thread be and let @narretz continue the conversation if neccesary.

**Comment by Narretz** [comment]
`NG1_BUILD_NO_REMOTE_VERSION_REQUESTS` is set to whatever you want it to be. It's only `'1'` if you set it to `'1'`. And it also doesn't matter what value it is. As long as it is set to any value, NO_REMOTE_REQUESTS becomes true.

And now we're back to square one ... literally. Because `!!'1'` and `!!1` is `true`. See https://jsfiddle.net/c0qadpby/1/ This is JavaScript 101, and if you are not willing to accept this, then this is were I draw the line in this discussion. This is something that is objectively true in programming JavaScript. You are basically questioning how JavaScript works! If you think `1` or `'1'` should not be a truthy value, then you have to take this to the ECMAScript Language Specification.

**Comment by hellofadude** [comment]
@frederikprijck

> As you reject to read my replies and understand my fiddles (which clearly show 1 is truthy) I'm going to leave this thread be and let @Narretz continue the conversation if neccesary.

I am sorry if I offended you but not looking at your code...:( I was only speaking matter-of-fact.. I do that sometime.. no offence..:-)

Just to explain - a truthy value is a value that is considered  true when evaluated in a Boolean context i.e `if(condition)` is a Boolean context and yes I accept Javascript uses type coercion in Boolean contexts but only for certain values eg " " or underfined.

Logical operators are typically used with Boolean (logical) values. When they are, they return a Boolean value.  logical NOT returns false if its single operand can be converted to true; otherwise, returns true.

"1" is not a Boolean value, it is a string value, a primitive type and so can not be converted or flipped.

**Comment by frederikprijck** [comment]
You didn't offend me at all, your only don't seem to be willing to understand what we are saying. And we can't keep repeating ourselves. 

What u are saying is true in most languages, but not in JavaScript.

> yes I accept Javascript uses type coercion in Boolean contexts but only for certain values eg " " or underfined.

Please read https://developer.mozilla.org/en-US/docs/Glossary/Truthy which lists all falsy values (and no, this is not only "" and undefined) . All other values in javascript are truthy.

**Comment by hellofadude** [comment]
> You didn't offend me at all, your only don't seem to be willing to understand what we are saying. And we can't keep repeating ourselves.

I have updated my comment. My point is `!!process.env['NG1_BUILD_NO_REMOTE_VERSION_REQUESTS']` returns `false`

**Comment by hellofadude** [comment]
@Narretz 

> NG1_BUILD_NO_REMOTE_VERSION_REQUESTS is set to whatever you want it to be. It's only '1' if you set it to '1'. And it also doesn't matter what value it is. As long as it is set to any value, NO_REMOTE_REQUESTS becomes true.

Yes I agree that `!process.env['NG1_BUILD_NO_REMOTE_VERSION_REQUESTS']` will equate to true if set with any number.

Do you agree that consequently `!!process.env['NG1_BUILD_NO_REMOTE_VERSION_REQUESTS']` will equate to false?

**Comment by hellofadude** [comment]
> You didn't offend me at all

Thank you..:)

**Comment by Narretz** [comment]
> Yes I agree that !process.env['NG1_BUILD_NO_REMOTE_VERSION_REQUESTS'] will equate to true if set with any number.

That is *not* what I wrote, and I have a hard time understanding how you can come to the conclusion that I did. 

I'm locking this issue, because not only has everything been said, it has been said at least twice now, and it didn't make any of us wiser.
Again, we appreciate contributions and you are welcome to contribute to AngularJS, but this PR is incorrect.

**Pull request closed without merging**
