### PR TITLE
docs($q): replace "array" with "object" in tests for hash argument 

### PR DESCRIPTION
**Pull request by mohsen1**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

**What is the current behavior? (You can also link to an open issue here)**

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change?**

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Other information**:

### CODE REVIEW

**Comment by gkalpak** [comment]
Good catch :smiley:
Can you please sign the CLA so we can merge this?

**Comment by mohsen1** [comment]
Done!

**Comment by Narretz** [comment]
@gkalpak Is the type "test" or "docs"?

**Comment by gkalpak** [comment]
Now it's `docs` :stuck_out_tongue: 
I always have a hard time with these changes, but I think we've been labeling them as `docs` and since the commit message says `docs`, let's roll with that :smile:

**Pull request closed without merging**
