### PR TITLE
test(*): introduce the `toEqualMinErr()` custom Jasmine matcher

### PR DESCRIPTION
**Pull request by gkalpak**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Test/Refactor.

**Does this PR introduce a breaking change?**
No.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [ ] ~~Tests for the changes have been added (for bug fixes / features)~~
- [ ] ~~Docs have been added / updated (for bug fixes / features)~~

**Other information**:
Discussed in https://github.com/angular/angular.js/pull/15213#discussion_r81749995.

### CODE REVIEW

**Comment by mgol** [comment]
It seems the `toThrowError` to `toThrowMinErr` changes belong in a separate commit but otherwise LGTM.

**Comment by gkalpak** [comment]
True (I got lazy 😳)
I'll split them :smiley:

**Comment by gkalpak** [comment]
I split the commits up and added a 3rd commit with a few more replacements.

**Comment by gkalpak** [comment]
LGTM'd by @mgol

**Pull request closed without merging**
