### PR TITLE
fix($route): allow preventing a route reload

### LINKED ISSUE #9824: event.preventDefault() does not work in $routeChangeStart after $route.reload()
**Angular version 1.3.0**

**Failing code**

``` javascript
	$rootScope.$on('$routeChangeStart', function(event, curr, prev) {
		if (...condition1...) {
			event.preventDefault();
			// do something to get condition1 == false
			$route.reload();
		}
		
		if (...condition2...) {
			event.preventDefault(); // <-- this is not preventing
			// do something to get condition2 == false
			$route.reload();
		}
	});
```

**Issue in source**

          reload: function() {
            forceReload = true;
            $rootScope.$evalAsync(function() {
              // Don't support cancellation of a reload for now...
              prepareRoute(); // <-- param is empty
              commitRoute();
            });
          },

...

    function prepareRoute($locationEvent) {
      var lastRoute = $route.current;

      preparedRoute = parseRoute();
      preparedRouteIsUpdateOnly = preparedRoute && lastRoute && preparedRoute.$$route === lastRoute.$$route
          && angular.equals(preparedRoute.pathParams, lastRoute.pathParams)
          && !preparedRoute.reloadOnSearch && !forceReload;

      if (!preparedRouteIsUpdateOnly && (lastRoute || preparedRoute)) {
        if ($rootScope.$broadcast('$routeChangeStart', preparedRoute, lastRoute).defaultPrevented) {
          if ($locationEvent) { <-- is undefined
            $locationEvent.preventDefault();
          }
        }
      }
    }

### PR DESCRIPTION
**Pull request by gkalpak**
Fixes #9824

### CODE REVIEW

**Comment by gkalpak** [comment]
(I'm not sure if it's a feature or a fix actually...)

**Comment by petebacondarwin** [comment]
LGTM

**Comment by petebacondarwin** [comment]
Let's call it a fix!

**Comment by gkalpak** [comment]
@petebacondarwin, backport to `v1.4.x` (since it's a fix) ?

**Comment by gkalpak** [comment]
Backported to `v1.4.x` as 4bc3031.

**Pull request closed without merging**
