### PR TITLE
Add Chinese version README.---Closed this PR, thank you.

### PR DESCRIPTION
**Pull request by damoqiongqiu**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

Added Chinese version README.

**What is the current behavior? (You can also link to an open issue here)**

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change?**

No, just README.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**Other information**:

I'am xiaofeiz@google.com, and I have signed CLA.

### CODE REVIEW

**Comment by damoqiongqiu** [comment]
I signed it!

**Comment by gkalpak** [comment]
Similar to #15524.

**Comment by gkalpak** [comment]
> I signed it!

@googlebot doesn't think so 😞

**Comment by damoqiongqiu** [comment]
@gkalpak 
Sorry, I didn't set email when commit the README doc, shall I post another PR instead or github will sync my latest commit automaticly?

**Comment by gkalpak** [comment]
All commits must have the email. Rebasing/squashing your commits and force-pushing should work.

**Comment by damoqiongqiu** [comment]
OK, thank you a lot, but I think the easiest way is discarding this PR and then post a new one, right? Because I don't want to break the original repo.

**Comment by gkalpak** [comment]
For reference: Closed in favor of #15558.

**Pull request closed without merging**
