### PR TITLE
Changed aria-live attribute value from polite to assertive

### PR DESCRIPTION
**Pull request by RaphStein**
For ngMessages directive ngAria generates aria-live with value assertive and not polite.

### CODE REVIEW

**Comment by Narretz** [comment]
Hi, thanks for the PR! Can you please sign the CLA?

**Comment by RaphStein** [comment]
Hi, i have signed the CLA.

**Comment by marcysutton** [comment]
"Assertive" was added for a reason: so that feedback would be given immediately as users type in text inputs. We talked about making this a configuration option, was that not considered?

**Comment by Narretz** [comment]
I'm not sure if I follow; is this now incorrect? It was only a change in the docs to match the behavior in code, so I assumed it was safe.

**Comment by marcysutton** [comment]
Ah ha, I totally read that wrong! Disregard. :)

**Pull request closed without merging**
