### PR TITLE
tests(jQuery): test on both oldest & latest supported jQuery version (+ a minor jqLite refactor)

### PR DESCRIPTION
**Pull request by mgol**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Refactor.

**What is the current behavior? (You can also link to an open issue here)**
1. The `useCapture` parameter is passed to `add/removeEventListener`, there are wrappers created for those methods.
2. Tests are run only in the oldest supported jQuery version.

**What is the new behavior (if this is a feature change)?**
1. A minor refactor in jqLite (removal of unnecessary add/removeEventListener wrappers, no longer passing the `useCapture` parameter).
2. Running tests on both oldest & newest jQuery version used.

**Does this PR introduce a breaking change?**
No.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [ ] ~~Tests for the changes have been added (for bug fixes / features)~~
- [ ] ~~Docs have been added / updated (for bug fixes / features)~~

**Other information**:
None.

### CODE REVIEW

**Comment by mgol** [comment]
I created 3 commits as they made sense as encapsulated changes.

**Comment by petebacondarwin** [comment]
A couple of minor comments but otherwise looks good.

**Comment by mgol** [comment]
The PR is ready but Travis can't connect to Sauce Labs:
```
Response: {"error": "Too many active user tunnels: 30 >= 30"}.
```
Do we have too many projects using the same Sauce key?

**Comment by petebacondarwin** [comment]
Landed! Thanks @mgol

**Pull request closed without merging**
