### PR TITLE
Purpose readme contribution

### PR DESCRIPTION
**Pull request by aashishnagpal**
To make AngularJS more approachable to a larger number of users — from informed developers to curious passers-by and new and interested visitors — I have added a new section to the AngularJS's  README.md. The section is entitled What to Use AngularJS for and When to Use It. As the name suggests, the new section, a brief paragraph, explains in plain and straight-forward language what AngularJS is used for and when one should use it.

Other repositories may begin to use this new informative and catchy section soon, as my colleagues contact open-source technologies in an effort to make them more accessible to the tens of thousands of new users learning to code and thousands joining GitHub every day.

I hope you also find this section informative and useful enough to include this section for all future visitors to the repository.

### CODE REVIEW

**Comment by aashishnagpal** [comment]
I am the one who signed the CLA and authored the commits. I have added the associated email address into my Google account. Hope this resolves the conflict.


Aashish


________________________________

**Comment by aashishnagpal** [comment]
I apologize, I understood the message incorrectly. I will ask my colleague to complete and sign the CLA.

**Comment by aashishnagpal** [comment]
@googlebot 
As per my colleague who was the author on a few commits, he also has signed the CLA.

**Comment by aashishnagpal** [comment]
@googlebot 
All the authors agree. There are only 2 authors. Myself (@aashishnagpal) and Vito (@vitoahmeny). Both have signed the CLA. Please proceed with the pull request. Thanks.

**Comment by petebacondarwin** [comment]
Thanks guys! I squashed the changes into a single commit

**Comment by vitoahmeny** [comment]
I am one of the commit authors Vito(@vitoahmeny) and I have signed the cla, please don't close the pull request due to cla issue.

Thanks

**Comment by aashishnagpal** [comment]
Thanks Pete @petebacondarwin for merging the changes into AngularJS README. Happy to contribute. :+1: 

@vitoahmeny, the request is closed as the changes have been accepted. :smile:

**Comment by vitoahmeny** [comment]
That's great! :+1:

**Pull request closed without merging**
