### PR TITLE
docs(angular.forEach): describe your change...

### PR DESCRIPTION
**Pull request by jjdeu**
In the forEach example the result is pushed to this instead to log

### CODE REVIEW

**Comment by jjdeu** [comment]
I signed it!

**Comment by gkalpak** [comment]
@jjdeu, the example is utilizing the third (optional) `context` argument (i.e. `log` will become the `this` inside the iterator function).

Thx for taking the time to submit a PR though :smiley:

**Comment by jjdeu** [comment]
Yes, I see it now, my bad! What a great first contribution ;-)
Cheers, JJ

**Comment by gkalpak** [comment]
@jjdeu, don't let it bring you down. Just keep the PRs coming :smiley:

--
BTW, if you are looking for great second contribution, you can take a look at the [issues with `PRs plz!` label][1] and find yourself an easy one. If you have any questions or get stuck, feel free to ask for help either here or on one of the [support channels][2].

[1]: https://github.com/angular/angular.js/issues?q=is%3Aopen+is%3Aissue+label%3A%22PRs+plz%21%22
[2]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

**Pull request closed without merging**
