### PR TITLE
Use strict DI notation in executeWithElement()

### PR DESCRIPTION
**Pull request by Chris380**

### CODE REVIEW

**Comment by Narretz** [comment]
Why do you think this needs to be  changed?

**Comment by Chris380** [comment]
Without this change I ran into an error while e2e-testing an app with strict DI activated:
Error: [$injector:strictdi] function($browser) is not using explicit annotation and can not be invoked in strict mode
http://errors.angularjs.org/1.4.6/$injector/strictdi?p0=function(%24delegate)

**Comment by Narretz** [comment]
Ah okay, I see. So you are using the scenario runner for e2e tests, and not protracotr? Because the scenario runner is deprecated.

**Comment by Chris380** [comment]
Yes, we still use the scenario runner for one (old) project. A switch to Protractor is not planned yet.

**Comment by Narretz** [comment]
If it's an old project, does it actually help you if this change lands in 1.4.x and above?

**Comment by Chris380** [comment]
We do regular updates of Angular and are currently using 1.4.6. Maybe that's a special scenario, so I don't have problems if this pull request is rejected.

**Comment by petebacondarwin** [comment]
The `ngScenario` module is deprecated and we are not accepting further code changes for it. Please look at using Protractor for your e2e testing or consider forking your own version of `ngScenario`.

**Comment by Chris380** [comment]
Thank's for your comment, Pete. I've already switched to Protractor for e2e-testing - works fine!

**Pull request closed without merging**
