### PR TITLE
docs($resource): document Resource#toJSON

### PR DESCRIPTION
**Pull request by jrvidal**
Document the `toJSON` method of Resource instances as part of its public API.

### CODE REVIEW

**Comment by gkalpak** [comment]
Thx for submit this! Could you expand a little bit on when `toJSON` is used and what it does? Maybe add a link to [MDN][1].

[1]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#toJSON()_behavior

**Comment by jrvidal** [comment]
> Could you expand a little bit on when toJSON is used and what it does? Maybe add a link to MDN.

Will do 👍 

I have just realized that `toJSON` [does not remove](https://github.com/jrvidal/angular.js/blob/df23708b9385062562168a87a12767a627da1c0e/src/ngResource/resource.js#L656-L661) `$cancelRequest`, so strictly speaking, it doesn't return a "simple object without the extra methods". Do you think it is pertinent to modify `toJSON` to do that, and if so, is it OK to do it in this PR?

**Comment by gkalpak** [comment]
`toJSON` is not a general purpose function - it's sole purpose is facilitating proper conversion to JSON. As such, it makes sense to do the least amount of work necessary. Functions are not serialized to JSON, so `$cancelRequest` is not deleted on purpose.

**Comment by jrvidal** [comment]
Gotcha, I will update the docs accordingly.

**Comment by jrvidal** [comment]
Notice however how this behavior means that the workaround I mentioned in #14637, where I tried to use a `toJSON` call as a way of getting "just the data", is not valid. In any case, documenting this method improves the situation so at least we know where we stand.

**Comment by jrvidal** [comment]
I rebased my commit with a better description.

**Pull request closed without merging**
