### PR TITLE
feat($http): setting JSONP callback name

### PR DESCRIPTION
**Pull request by ricardohbin**
Allow to define a name to angular.callbacks function. It would be useful to caching (varnish, etc).

Ex:

``` javascript
$http.jsonp("http://example.com?callback=JSON_CALLBACK(myFunction)").success(...)
```

Will always request

```
http://example.com?callback=angular.callbacks.myFunction
```

### CODE REVIEW

**Comment by katzlbt** [comment]
The pyramid web framework disallows angular callbacks since newer versions.
https://pyramid.readthedocs.org/en/master/_modules/pyramid/renderers.html
JSONP_VALID_CALLBACK = re.compile(r"^[a-zA-Z_$][0-9a-zA-Z_$]+$")

**Comment by pixelcort** [comment]
Still have an API that's not allowing dots; I know polluting global namespace is bad but right now the Angular feature can't be used because of this. An alternative is some flag to remove the dots.

**Comment by petebacondarwin** [comment]
I think this is annoying enough - and might require a breaking change - to be highlighted for 1.5

**Comment by petebacondarwin** [comment]
Could we alleviate this by moving the callback stuff into its own service, say `$jsonpCallbacks`, that developers can override.

The service could have two methods `getCallback(url : string?) : string` and `getData(callback: string): object|array`.

`getCallback(url)` would return a string describing the callback to be sent to the server. The built-in service would just return `'angular.callbacks.' + id`. Where `id` is computed just as in the current `$httpBackend` service.

`getData(callback)` would return the parsed JSON data for the the given callback.

**Comment by petebacondarwin** [comment]
@ricardohbin, @revolunet, @pixelcort, @katzlbt - please take a look at #14795
Closing this PR in favour of that one.

**Comment by rajeshmanepalli** [comment]
hi,

please unsubscribe my mailid

**Pull request closed without merging**
