### PR TITLE
updated isDate() function description

### PR DESCRIPTION
**Pull request by jparmar**
Provided proper description for isDate() function to help developers avoid confusion.

### CODE REVIEW

**Comment by Narretz** [comment]
Hi, can you sign the CLA please?

**Comment by pkozlowski-opensource** [comment]
@jparmar we can't really merge patches without a corresponding CLA... I'm going to close this PR now to clean up backlog but would be very happy to re-open it and merge your PR when you've got the CLA signed. Ping me when done!

**Comment by jparmar** [comment]
Hi, I am not able to sign the CLA certificate.
I am getting 404 page.

check the URL : https://cla.developers.google.com/clas/edit?id=692878148358&kind=KIND_INDIVIDUAL&domain=DOMAIN_GOOGLE&redirect=1

**Comment by pkozlowski-opensource** [comment]
@jeffbcross is there are contact e-mail for people facing issues with the CLA signing app?

**Comment by jeffbcross** [comment]
@willnorris any ideas here?

**Comment by willnorris** [comment]
Jeff, please contact the SignCLA team internally if you haven't already.

**Pull request closed without merging**
