### PR TITLE
fix(ngRoute): extract path params containing hashes and/or question marks correctly

### PR DESCRIPTION
**Pull request by susisu**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
This PR fixes a regression introduced by 840b5f0.

**What is the current behavior? (You can also link to an open issue here)**
If the path (`$location.path()`) contains hashes and/or question marks, path params are not correctly extracted.

For example, if you set `$routeProvider.when('/foo/:bar', {})` and navigate to `/foo/bar%23baz`, you will get `$routeParams.bar === "bar"`, not `$routeParams.bar === "bar#baz"`.

**What is the new behavior (if this is a feature change)?**
Path params are correctly extracted (`$routeParams.bar === "bar#baz"`).

**Does this PR introduce a breaking change?**
No.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our [guidelines](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits)
- [x] Fix/Feature: [Docs](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#documentation) have been added/updated
- [x] Fix/Feature: Tests have been added; existing tests pass

**Other information**:

### CODE REVIEW

**Comment by susisu** [comment]
I signed it!

**Review by gkalpak — CHANGES_REQUESTED** [review]
This PR seems to unnecessarily revert a large part of 840b5f0. Can you please only make the necessary changes and leave the rest untouched.

**Comment by susisu** [comment]
@gkalpak  Thanks for your review!
The previous `parseRoute` and `pathRegExp` functions have different types of arguments (urls and paths) so I thought they should be separate.

Anyway, I fixed it!

**Comment by gkalpak** [comment]
Awesome, thx!

##
> The previous `parseRoute` and `pathRegExp` functions have different types of arguments (urls and paths) so I thought they should be separate.

I know, but they have almost the same logic, so it makes sense to share (see https://github.com/angular/angular.js/issues/14173#issuecomment-192649766).

**Comment by gkalpak** [comment]
I created #16672 which adds some refactorings on top of your commits (mainly to simplify the implementation and decouple the two slightly different usecases of `ngRoute`/`ngMocks`).
Thx for providing the main fix, @susisu 💯

**Review by gkalpak — APPROVED** [review]

**Comment by Narretz** [comment]
Merged as https://github.com/angular/angular.js/commit/510404e5b34fcf47a4d0cc8094afe7431b0a0b63

**Pull request closed without merging**
