### PR TITLE
fix removeFromArray

### PR DESCRIPTION
**Pull request by someone235**
removeFromArray check if `val >= 0` before `arr.splice(index, 1)`, instead of `index >= 0`

### CODE REVIEW

**Comment by someone235** [comment]
I signed it!

**Comment by someone235** [comment]
I've signed the cia

**Comment by lgalfaso** [comment]
Hi, can you please:
* Squash this into one commit
* Create a test that shows the error and that this fixes

Thanks!

**Comment by Narretz** [comment]
removeFromArray is only used once, here: https://github.com/angular/angular.js/blob/9c7c494c3e4f325d7db3269c689ddfe5f78e0ec2/src/ngAnimate/animateCss.js#L846

This is used to store the `animation-play-state` style in the temporaryStyles, so it can be cleaned up when the animation ends. However, the style is already cleaned up at this point (before temporaryStyles): https://github.com/angular/angular.js/blob/9c7c494c3e4f325d7db3269c689ddfe5f78e0ec2/src/ngAnimate/animateCss.js#L725

So, yes there's a bug here, which could possibly remove a temporary style from an element if an animation is resumed.

We should simply remove this block: https://github.com/angular/angular.js/blob/9c7c494c3e4f325d7db3269c689ddfe5f78e0ec2/src/ngAnimate/animateCss.js#L844-L846

**Pull request closed without merging**
