### PR TITLE
Drag and Drop directives

### PR DESCRIPTION
**Pull request by eislasq**
This change will help to handle drag and drop events.
Example at http://plnkr.co/edit/d4OgfpeyI8dYE0mty5lP?p=preview

### CODE REVIEW

**Comment by eislasq** [comment]
I signed it!

**Comment by caitp** [comment]
This might be a bit niche to live in core, have you considered releasing this as a standalone library?

**Comment by eislasq** [comment]
I think this is not a bit nichem, rather it is very common to use drag and drop. But anyway I will publish it as standalone library.
Thanks

**Comment by caitp** [comment]
of course it's very common, but the requirements for different applications D&D behaviours can differ dramatically, as can the browser support and performance --- these things make it very hard to justify living in core. Thank you for publishing this externally =)

**Pull request closed without merging**
