### PR TITLE
docs(guide/Migrating from Previous Versions): Add an issue with HTML …

### PR DESCRIPTION
**Pull request by iwhp**
…select tag and numeric values

### CODE REVIEW

**Comment by iwhp** [comment]
I signed it!

**Comment by Narretz** [comment]
Thanks for the PR & for bringing this issue to our attention. I committed a little different version that explains possible workarounds. Keep up the good work!

**Comment by iwhp** [comment]
Thankx Narretz. This looks very good. Maybe it is just me, but I could not implement your second suggestion: "or implement a parser on ngModel that converts the option string value to a Number.". Could you please provide a sample. Thankx, Harry

**Comment by Narretz** [comment]
You are right, a parser alone doesn't work - you need a formatter, too: http://plnkr.co/edit/JZPay8jgm5AXKGXDCjSb

**Comment by iwhp** [comment]
Great - Thankx!

**Pull request closed without merging**
