### PR TITLE
docs(ngClass): added known issue to documentation

### PR DESCRIPTION
**Pull request by maxchernin**
PR of issue https://github.com/angular/angular.js/issues/16183

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Docs Update

**What is the current behavior? (You can also link to an open issue here)**
https://github.com/angular/angular.js/issues/16183

**What is the new behavior (if this is a feature change)?**
This is a docs update

**Does this PR introduce a breaking change?**
No

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ *] Docs have been added / updated (for bug fixes / features)

**Other information**:

### CODE REVIEW

**Comment by maxchernin** [comment]
I signed it!

**Comment by Narretz** [comment]
Where did you get the info that this is deprecated, causes memory leaks and is bad for performance? Only the latter is a valid point, although that depends on the complexity of the function.

It's also possible to use any kind of AngularJS expression in ngClass as long as the result is one of the 3 forms that are documented.

**Comment by frederikprijck** [comment]
I think that adding this to the `ngClass` docs is not a good idea as this is also true for other directives, not only `ngClass`.

**Comment by Narretz** [comment]
I'm going to close this issue because we haven't got required feedback. Feel free to reopen this issue if you can provide new feedback.

**Pull request closed without merging**
