### PR TITLE
Extend with customized reduce function

### PR DESCRIPTION
**Pull request by jl2922**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

feature

**What is the current behavior? (You can also link to an open issue here)**

'extend' will use new value to override original value

**What is the new behavior (if this is a feature change)?**

by using 'extendWith', user can specify the new value assigned with a customized function of both the destination value and source value.
The test case provides an example where concat is used as an customized function for array like properties. Without the if statement, extendWith will behave the same as extend.

**Does this PR introduce a breaking change?**

no

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**Other information**:

### CODE REVIEW

**Comment by jl2922** [comment]
I am a googler, LDAP: junhao

**Comment by Narretz** [comment]
Thanks for the PR. However, we usually only add angular.* helper functions to the core if the core actually benefits from it. This looks like a function for a very specific use case. So I don't think it should be added to core.

**Comment by gkalpak** [comment]
I agree that this doesn't belong in core.

<sub>(But IF we decided to get it in, we should probably implement all version (i.e. `extend`, `merge`, `extendWith`) with `reducers`. There is no reason for `baseExtend` to take both a `deep` **and** a `reducer` argument.)</sub>

**Comment by Narretz** [comment]
Closing as we have two votes against and no response from @jl2922

**Comment by jl2922** [comment]
Sorry for the late reply. I don't quite understand why you say it is a very specific use case. I feel it is common that instead of always using the source value to overwrite the destination value, it gives user an option to use value computed from both the source and destination, isn't it:)

This functionality will make the code written in Angular more organized and easy to understand than everyone giving up angular.extend and writing their own extend function when facing with this need.

Both extendWith and mergeWith like functions are already in lodash and are about to be added in underscore. My team is using AngularJS, so I feel it would be best that this could be in our own product. 

And if we agree upon the fact that deep and customized reducer can benefit users, I don't see any reason why combining them is not a general use case and why we don't try to extend the baseExtend but to create another baseExtendWith that contains all the codes in baseExtend.

**Pull request closed without merging**
