### PR TITLE
Add casts to avoid some 'non-existent property' warnings from Closure…

### PR DESCRIPTION
**Pull request by dimvar**
… Compiler.

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

**What is the current behavior? (You can also link to an open issue here)**

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change?**

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Other information**:

### CODE REVIEW

**Comment by dimvar** [comment]
Googler here. This PR is required for an internal cleanup. @IgorMinar advised to send PR instead of submitting internally.

**Comment by gkalpak** [comment]
Which branches does this need to go in?

**Review by gkalpak — APPROVED** [review]
It seems strange to me that these are the only places creating warnings (but it is probably because I am not very familiar with Closure Compiler).

**Comment by dimvar** [comment]
Internally it's v1_5, so any branches that correspond to that.

**Comment by IgorMinar** [comment]
LGTM. can we please get this merged to master soon and cherry-picked to v1.5.x to unblock an internal refactoring? Thanks!

**Comment by gkalpak** [comment]
Done

**Pull request closed without merging**
