### PR TITLE
fix($location): always decode special chars in `$location.url(value)`

### PR DESCRIPTION
**Pull request by petebacondarwin**
See https://github.com/angular/angular.js/issues/16312#issuecomment-348268476

@bourey - can you check that with this regression fix your original issue is still resolved?

### CODE REVIEW

**Comment by Narretz** [comment]
I have to admit that I don't really understand what we are trying to fix here. I think a bit more info in the commit message would be useful. 😅

**Comment by petebacondarwin** [comment]
I have updated the commit message @Narretz

**Comment by Narretz** [comment]
Thanks! That should help in the future. There were a few typos, here's a cleaned up version:

> The original fix for #16312 included changing how `$location.url(value)`
decoded the special characters passed to it as a setter.
This broke a number of use cases (mostly involving the ui-router).
Further analysis appears to show that we can solve #16312, to prevent
urls being rewritten with decoded values, without modifying the
behaviour of `$location.url`.
This commit reverts changes to `$location.url(value)` so that encoded
chars will be decoded and passed to `$location.path(value)`.
In particular it will convert encoded forward slashes, which changes how
the path is updated, since e.g. `a/b/%2Fc%2Fd will become `a/b/c/d`.
While this is arguably not "correct", appears that there are too many
use cases relying upon this behaviour.

**Comment by petebacondarwin** [comment]
Thanks updated again. Still looking for confirmation from @bourey

**Comment by christopherthielen** [comment]
FWIW, the ui-router test suite fails with this build.  I'll look into what's breaking.

**Comment by petebacondarwin** [comment]
I am going to land this in 1.6.x and then see if @bourey comes back with a further issue.

**Pull request merged**
