### PR TITLE
fix($filter): add int support for negated strict comparison

### LINKED ISSUE #10141: Filter issue when using negated int
Use case - While manipulation dataset with id as int values you run into problems when trying to use negated and strict comparison.

http://jsfiddle.net/pdvhwd26/2/

In the example I want to delete a user with id 1
not using strict deletes 11 as well
using strict doesn't delete anything as types don't match
The third option is the desired result I am after.

The problem is I am being forced to convert to string to be able to negate the id.

Suggesting either to allow negation in a way that doesn't change type. Or handle this scenario in another way using a shorthand.

### PR DESCRIPTION
**Pull request by adi-ads**
- negation is achieved by adding '!' which fails if key is a integer and strict comparison is set to true.
- This commit fixes it by checking typeof and parsing accordingly

Closes #10141

### CODE REVIEW

**Comment by petebacondarwin** [comment]
@gkalpak - what to do about this? Is it still relevant since the big $filter refactoring.

**Comment by gkalpak** [comment]
@petebacondarwin, the issue that this PR is trying to address is still relevant (as are my concerns expressed in comments).

As far as the implementation itself is concenred, (besides being a (little) breaking change) this is basically a trade-off (we support some new usecases, while we drop support for others), so I am not a fan of this change.

As discussed with @adi-ads, it would be nice to have a non-breaking way to explicitly specify a negation without having to turn the value to string. Still, considering that:

1. the usecases that would benefit from this aren't common
2. this would introduce extra complexity
3. there is already a way to support this (more or less) via custom comparators or a function expression

I think that it's not worth it (but I could be convinced otherwise :smiley:).

**Comment by petebacondarwin** [comment]
I agree with you @gkalpak. I don't like the fact that this breaks other expected results.
In the simple case you can just use a custom comparator: http://jsfiddle.net/00rqow9y/

One alternative could be that we provide a special internal object that indicates negativity, which is acquired via a helper function on the filterFilter. This would allow the type of the value to remain intact....

```
var filter = $filter('filter');
var not = filter.not;
$scope.users2 = filter($scope.users, id: not(1)}, true);
```

So I think we should close this PR. If we feel that this helper object/function would be viable then @adi-ads or someone else could implement it in a new PR.

**Comment by adi-ads** [comment]
Custom comparator is working for us for now, I like the internal object to indicate negativity - can open a new PR if we see a couple of more folks asking about this. But god for now.

**Comment by petebacondarwin** [comment]
Good.

**Pull request closed without merging**
