### PR TITLE
fix(currencyFilter): trim currency string

### PR DESCRIPTION
**Pull request by austinoneil**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

Bug fix

**What is the current behavior? (You can also link to an open issue here)**

For certain locales, when the `currencySymbol` is set to an empty string, there is trailing white space. [See issue #15018 ](https://github.com/angular/angular.js/issues/15018)

**What is the new behavior (if this is a feature change)?**

Any currency string will be trimmed.

**Does this PR introduce a breaking change?**

yes

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**Other information**:

Trim any beginning or trailing white space in a currency string.
Motivation: global fix for issue 15018

### CODE REVIEW

**Comment by austinoneil** [comment]
Correction: this is a breaking change.

**Comment by austinoneil** [comment]
Does anybody know how I would change locale for an automated test?

**Comment by Narretz** [comment]
You mean in a unit test?

**Comment by austinoneil** [comment]
Yes

**Comment by Narretz** [comment]
Why did you remove the fix from the commit?

**Comment by austinoneil** [comment]
@Narretz The fix is still there. I was just trying things to get a unit test. Check the "files changed" tab.

**Comment by Narretz** [comment]
Ah I see, sorry. The test code you changed is a docs end 2 end test,  not a unit test though. The filter spec files are in the test folder.

**Comment by austinoneil** [comment]
@Narretz Thanks!  Got the unit test in.

**Comment by gkalpak** [comment]
This does not fix #15018. In fact it just fixes certain cases (i.e. locales which put the currency symbol _after_ the number), but is not a generic fix (see https://github.com/angular/angular.js/issues/15018#issuecomment-239480197 for more details).

I am tempted to merge this even if it fixes only some of the cases (as a proper fix is quite more involved), but that would be "unfair" to certain locales :/

**Comment by austinoneil** [comment]
@gkalpak Would appending a `.replace(\-/s*\g, '-')` fix the potential issue with having a space between the negative sign and the currency amount?  I don't see any locale delimiting their currency with anything that would make the fix problematic.

I'll try to add some unit tests and fix based off those when I get home.

**Comment by gkalpak** [comment]
No, I don't think it would work for all cases (although it would take care of several more than the current implementation). Take into account that people might be overwriting the locals `pattern` object. E.g. in finance/accounting-related apps people prefer to display negative values wrapped in `(...)` instead of prefixing them with `-`.

I have a more general fix. I will submit a PR.

**Pull request closed without merging**
