### PR TITLE
fix($q): correctly set constructor on prototypes

### PR DESCRIPTION
**Pull request by bluepnume**
This patch will correctly set `Promise.prototype.constructor` and `Deferred.prototype.constructor`.

When prototype is set in the form `Foo.prototype = {x: y};`, the constructor will not be set correctly (as opposed to in the form `Foo.prototype.x = y;`.

As such, it is necessary to manually add the constructor to the prototype in these cases.

### CODE REVIEW

**Comment by lgalfaso** [comment]
Why not just
>
>
extend(Promise.prototype, {...});

?

**Comment by bluepnume** [comment]
Good suggestion! Done

**Comment by lgalfaso** [comment]
@bluepnume can you look into the Travis failure, it looks like a valid failure

**Comment by bluepnume** [comment]
I reset the previous commit. It looks like `extend` is not available at this point in the execution.

**Comment by lgalfaso** [comment]
@bluepnume look at `lib/promises-aplus/promises-aplus-test-adapter.js`, some copy & paste should be able to handle the rest

**Comment by lgalfaso** [comment]
Hi,
  This needs a little more work before it can land:
* add some tests
* rebase on top of master
* squash everything to a single commit

Thanks!

**Pull request closed without merging**
