### PR TITLE
fix($location): decode non-component special chars in Hashbang URLS

### PR DESCRIPTION
**Pull request by petebacondarwin**
Fixes https://github.com/angular/angular.js/pull/16316#issuecomment-347527097

### CODE REVIEW

**Review by gkalpak — APPROVED** [review]

**Comment by gkalpak** [comment]
🙈

**Comment by petebacondarwin** [comment]
> 🙈

Is that you washing your hands of this @gkalpak ?

**Comment by petebacondarwin** [comment]
Well this is a bit annoying:

```
- Invalid ticket reference, must be /^((([Cc]los|[Ff]ix|[Rr]esolv)(e[sd]))|([Cc]onnects)|(([Cc]onnect|[Cc]onnects|[Cc]onnected) to)) (.*#|gh-|[A-Z]{2,}-)[0-9]+/
Was: Fixes https://github.com/angular/angular.js/pull/16316#issuecomment-347527097
```

(https://travis-ci.org/angular/angular.js/jobs/308460518#L559)

**Comment by Narretz** [comment]
True. But it's the last check, so everything else has passed and you can merge it anyway.

**Comment by jasonaden** [comment]
Good timing! Just ran into and debugged this in g3, finding the same issue. Thanks @petebacondarwin!

**Comment by alonp99** [comment]
Should I wait for the next version to go out to get this fix?
Any estimation when it will be?

**Comment by gkalpak** [comment]
It should be in 1.6.8, which is expected to come out very soon :smiley:

**Pull request merged**
