### PR TITLE
directives: added drag-drop events

### PR DESCRIPTION
**Pull request by MrOutput**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

**What is the current behavior? (You can also link to an open issue here)**

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change?**

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Other information**:

### CODE REVIEW

**Comment by gkalpak** [comment]
The problem with dnd related events is that they usually happen multiple times per second and are not suitable for integration with the $digest loop. Maybe just add the few that make sense (e.g. `drop`).

**Comment by MrOutput** [comment]
gotcha, it is extremely helpful to have as an ngDirective. Perhaps, with these directives the digest loop should not fire for them? Is there some sort of exclusion array with the names of events to exclude, to stop the 250ms fire, from triggering the cycle?

**Comment by gkalpak** [comment]
There is no exclusion array. But you can always create your own directives :smiley:

**Comment by Narretz** [comment]
The fact that we have directives for mousemover etc. contradicts @gkalpak's arguments a bit. The logic is however that you usually have a more involved setup for these events anyway, so the ngEvent directives are probably not too useful in a lot of cases.

**Comment by gkalpak** [comment]
Some `ng-mouse` directives aren't appropriate either - it would be a breaking change to remove them thought :smiley:

**Comment by Narretz** [comment]
Let's not do it. These events are too specific to be very useful in the current design of the ngEvent directives.

**Comment by eislasq** [comment]
I also have sugested D&D #12469 about 1 year ago and was rejected. 
But now I have published as a library https://github.com/eislasq/drag-and-drop

**Pull request closed without merging**
