### PR TITLE
docs(form.FormController): *  $touched and $untouched

### PR DESCRIPTION
**Pull request by djleonskennedy**
docs update

no $touched and $untouched are described in the doc

 $touched and $untouched are described in the doc

**Does this PR introduce a breaking change?** no

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Other information**:

$touched and $untouched properties added to doc

### CODE REVIEW

**Comment by gkalpak** [comment]
Thx for submitting the PR, but this addition is invalid.
The FormController does not have `$touched/$untouched` properties.

**Comment by djleonskennedy** [comment]
@gkalpak Hmm, how do i use it in 1.5, if it doesn't have it ?

**Comment by gkalpak** [comment]
You don't :grin: You can't use a feature that does not exist. If you believe it would be useful to aggregate `$touched`/`$untouched` on the FormController, you can open a new issue (or even a PR :smiley:), so we can discuss this.
<sub>(But in any case, you should not document a feature that does not exist :smiley:)</sub>

**Comment by djleonskennedy** [comment]
@gkalpak take a look please http://prntscr.com/dx5rnb :)

**Comment by gkalpak** [comment]
The `$touched` property shown on the screenshot is not on a `FormController` instance (afaict).
I assume `vm.editUserForm` is the alias of a form (and thus points to a FormController instance) and `phone` is the name under which an input field is registered to the form. So, `vm.editUSerForm.phone` points to an **NgModelController** (which does indeed have `$touched/$untouched` properties, as documented).

**Pull request closed without merging**
