### PR TITLE
docs(error/numfmt): describe your change...

### PR DESCRIPTION
**Pull request by wowczarczyk**
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

docs update
- **What is the current behavior?** (You can also link to an open issue here)

Now the formatter function is used in place of with parser function and vice versa
- **What is the new behavior (if this is a feature change)?**

Functions have been swapped
- **Does this PR introduce a breaking change?**

No
- **Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- **Other information**:

Formatter function seems to be be swapped with parser function

### CODE REVIEW

**Comment by voodoorider** [comment]
I signed it!

pt., 11.03.2016 o 10:43 użytkownik googlebot <notifications@github.com>
napisał:

**Comment by Narretz** [comment]
That change is not right.The directive adds an additional parser / formatter that converts the input into a value that the original number type parsers / formatters expect. If you open the example in a plnkr, and make your changes, you will get the numfmt error again,

**Comment by voodoorider** [comment]
Still I find it a little odd and counter-intuitive that the formatter function returns numeric value and parser function returns string in terms of ```<input type="number">```

**Comment by Narretz** [comment]
I think this is explained in the error message. This example directive is only needed if you want your models for input[number] to be strings. Maybe we describe better what actually happens? How would you change the description?

**Comment by voodoorider** [comment]
Well after giving it a second though I think it is OK. Sorry for the confusion.

**Pull request closed without merging**
