### PR TITLE
chore(*): add a Git .mailmap with my new name

### PR DESCRIPTION
**Pull request by mgol**
In this way my past contributions are mapped correctly.

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Chore.

**What is the current behavior? (You can also link to an open issue here)**
Git thinks I'm 2 people.

**What is the new behavior (if this is a feature change)?**
I'm one person again.

**Does this PR introduce a breaking change?**
No.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- ~~Tests for the changes have been added (for bug fixes / features)~~
- ~~Docs have been added / updated (for bug fixes / features)~~

**Other information**:

Output of `git shortlog -nse | head -25` after this PR (I see we could use more `.mailmap` entries, there are lots of duplicates):
```
   931	Igor Minar <igor@angularjs.org>
   692	Misko Hevery <misko@hevery.com>
   677	Peter Bacon Darwin <pete@bacondarwin.com>
   503	Igor Minar <iiminar@gmail.com>
   364	Vojta Jina <vojta.jina@gmail.com>
   364	Matias Niemelä <matias@yearofmoo.com>
   259	Martin Staffa <mjstaffa@googlemail.com>
   196	Caitlin Potter <caitpotter88@gmail.com>
   192	Brian Ford <btford@umich.edu>
   169	Georgios Kalpakas <g.kalpakas@hotmail.com>
   140	Georgios Kalpakas <kalpakas.g@gmail.com>
   127	Pete Bacon Darwin <pete@bacondarwin.com>
   108	Jason Bedard <jason+github@jbedard.ca>
   108	Martin Staffa <mjstaffa@gmail.com>
    99	Tobias Bosch <tbosch1009@gmail.com>
    94	Michał Gołębiowski <m.goleb@gmail.com>
    71	Lucas Galfaso <lgalfaso@gmail.com>
    70	Shahar Talmi <shahar.talmi@gmail.com>
    65	Jeff Cross <middlefloor@gmail.com>
    52	Chirayu Krishnappa <chirayu@chirayuk.com>
    50	rodyhaddad <rody@rodyhaddad.com>
    47	Pawel Kozlowski <pkozlowski.opensource@gmail.com>
    45	Di Peng <pengdi@google.com>
    43	Vojta Jina <vojta@gemin-i.org>
    41	Lucas Mirelmann <lgalfaso@gmail.com>
```

### CODE REVIEW

**Comment by Narretz** [comment]
Interesting. Maybe that's why for a while my commits are saying Martin Staffa committed with Martin Staffa.
Can you add my canonical email "mjstaffa@gmail.com"?

**Comment by mgol** [comment]
@Narretz I added entries for all the people from top 25 or so that had multiple distinct entries in Git commit history. On your name:

Before:
```
$ git shortlog -nse | grep -i staffa
   259	Martin Staffa <mjstaffa@googlemail.com>
   108	Martin Staffa <mjstaffa@gmail.com>
     6	Narretz <mjstaffa@googlemail.com>
```

After:
```
$ git shortlog -nse | grep -i staffa
   373	Martin Staffa <mjstaffa@gmail.com>
```

**Comment by Narretz** [comment]
Cool, thanks. How did you determine which is the canonical email for Igor etc. where it is not exactly clear?

**Review by petebacondarwin — APPROVED** [review]

**Comment by mgol** [comment]
@Narretz Good question! I checked what mail he used in his latest commit to https://github.com/angular/angular; similarly for other people (for some I checked https://github.com/angular/angular.js instead).

**Comment by mgol** [comment]
BTW, apart from `git shortlog`, `.mailmap` is also consulted when `git blame`-ing. Unfortunately it's not consulted by default for `git log` or `git show` but it can be configured to do so:
```
git config --global log.mailmap true
```

**Review by Narretz — APPROVED** [review]
Ok, that sounds good. Feel free to merge

**Pull request merged**
