### PR TITLE
 docs(tutorial/10 - More Templating): On phone details page, add link to phone list...

### PR DESCRIPTION
**Pull request by kakoma**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
docs

**What is the current behavior? (You can also link to an open issue here)**
Phone details page doesn't have a link to the phone list page

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change?**
No

**Please check if the PR fulfills these requirements**
- [ X] The commit message follows our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Other information**:

### CODE REVIEW

**Comment by gkalpak** [comment]
Since this is just an introductory tutorial, I wouldn't be too concerned about all aspects of navigation. (It is kind of beyond the scope of the tutorial.)

But if you feel strongly about it, be my guest :smiley:
Here are the necessary tasks for adding this "feature":

1. Add a test.
2. Make sure all future references of the `phone-details` template included the new code (if necessary).
3. Make the corresponding changes in https://github.com/angular/angular-phonecat (the repo where the code for the tutorial is kept).
<sub>(This last step can be challenging, due to how the tutorial is set up with each step represented by one commit in history. Feel free to ping me if you need any help with that.)</sub>

**Comment by kakoma** [comment]
Hahahaha good point. No, I don't feel too strongly about it....I just kept manually navigating back to the list page throughout the tutorial to the point that I eventually decided to add a link

**Comment by gkalpak** [comment]
OK, then. I am going to close this :smiley:
(BTW, you know the back-button works, right? 😛)

**Comment by kakoma** [comment]
Back button? How do I install one? :grinning:

**Comment by gkalpak** [comment]
`npm install -g browser-back-button` 😛

**Pull request closed without merging**
