### PR TITLE
um, it is suppose to have that user in the callback right?

### PR DESCRIPTION
**Pull request by ycmjason**

### CODE REVIEW

**Comment by ycmjason** [comment]
I signed it!

On Sun, 14 Jun 2015 at 21:28 googlebot <notifications@github.com> wrote:

> Thanks for your pull request. It looks like this may be your first
> contribution to a Google open source project, in which case you'll need to
> sign a Contributor License Agreement (CLA).
>
> [image: :memo:] *Please visit https://cla.developers.google.com/
> <https://cla.developers.google.com/> to sign.*
>
> Once you've signed, please reply here (e.g. I signed it!) and we'll
> verify. Thanks.
> ------------------------------
>
>    - If you've already signed a CLA, it's possible we don't have your
>    GitHub username or you're using a different email address. Check your
>    existing CLA data <https://cla.developers.google.com/clas> and verify
>    that your email is set on your git commits
>    <https://help.github.com/articles/setting-your-email-in-git/>.
>    - If you signed the CLA as a corporation, please let us know the
>    company's name.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular/angular.js/pull/12110#issuecomment-111873845>.
>
-- 
YCM Jason

**Comment by petebacondarwin** [comment]
Well actually, if you don't provide it in the callback then it gets it from the closure, I think.

**Comment by gkalpak** [comment]
@petebacondarwin is right. This is also a duplicate of #9791 and #10486 (and maybe others).
See the discussion on #9791 (and especially https://github.com/angular/angular.js/pull/9791#issuecomment-60495160) for an explanation of what's going on.

Closing as it works as expected.

**Comment by gkalpak** [comment]
@ycmjason, thx for taking the time to submit a PR.
Keep them coming if you spot anything that needs fixing :)

**Pull request closed without merging**
