### PR TITLE
docs(ioc): principal implementation of di

### PR DESCRIPTION
**Pull request by kambleaa007**
inversion of control and IoC container are important principals and implementation must be added in it.

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Yes, the principle of Inversion of control is missing.
Yes, the dependency management is missing too.

**What is the current behavior? (You can also link to an open issue here)**
There is not clear idea about why DI is used here.

**What is the new behavior (if this is a feature change)?**
Gives you more clear idea about DI implementation of IoC Principle,
Helpful for beginner coders. 

**Does this PR introduce a breaking change?**
Not at all.

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our [guidelines](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits)
- [x] Fix/Feature: [Docs](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#documentation) have been added/updated
- [ ] Fix/Feature: Tests have been added; existing tests pass

**Other information**:

### CODE REVIEW

**Comment by Narretz** [comment]
I think the wording should be 
> Dependency Injection (DI) is a software design pattern that implements inversion of control and deals with how components get hold of

**Comment by kambleaa007** [comment]
Thanks, How can i do that,
I got lots of errors, didnt changed the code at all

**Comment by Narretz** [comment]
You can ignore the errors and just add another commit with the correct change.

**Comment by kambleaa007** [comment]
I am trying since morning
I think there is something broken
That i can't figure out

**Comment by Narretz** [comment]
In that case I'll close this PR and you can open a new one with the correct changes

**Pull request closed without merging**
