### PR TITLE
test($parse): fix csp setup

### PR DESCRIPTION
**Pull request by lgalfaso**
Run the parse interpreter for csp enabled tests

### CODE REVIEW

**Comment by jbedard** [comment]
Is there a way to actually test this? I think this has happened before...

**Comment by lgalfaso** [comment]
I can add an internal flag that express that the function is compiled or
interpreted and add a test. Slightly an overkill, but should work
>
>

**Comment by jbedard** [comment]
I'm not sure if it's worth adding a flag. What about just asserting the flag we are changing is already a boolean?

**Comment by lgalfaso** [comment]
@jbedard mmm... ok updated the PR

**Comment by jbedard** [comment]
LGTM then, hopefully that stops it from happening again...

**Comment by lgalfaso** [comment]
landed as ea2518fceac22f2ee2a9ce688e9608f776c207f1

**Pull request closed without merging**
