### PR TITLE
fix($sniffer): force $sniffer.history to be false when inside ff addon

### LINKED ISSUE #7241: $browser.url() broken when angular runs as contentscript in firefox add-on
Hello Everyone,

I am currently doing add-on development for Firefox using Angular. While in Chrome Angular did work seamlessly with *angular-csp*, I encountered some weird behavior with Angular running as content-script in Firefox addon.

# Overview of the problem

When injected as content-script and used with `ngRoute` module, Angular raises:

    10 iterations reached. Aborting!

From it's digest loop.

# How to reproduce?

While i cannot provide a Plunkr for this issue, I've created a repository available @ https://github.com/lambdafizz/angular-ff-addon-compat that provides temporary fix for this issue and allows to reproduce this bug.

To reproduce, you will need bower and cfx tool (see installation instructions https://developer.mozilla.org/en-US/Add-ons/SDK/Tutorials/Installation). Then after you bower-install the module:

    $ bower install angular-ff-addon-compat

Then just cd into the example:

    $ cd bower_components/angular-ff-addon-compat/example-plugin

And run the plugin:

    $ cfx run

*This will run  a fixed (monkey patched) version of the plugin*. To reproduce the bug, inside the `example-plugin` directory edit `data/js/app.js` and remove `lf.ff-addon-compat` from module's dependency. This will remove the monkey-patch and illustrate original behavior. You will be able to see *lots* of errors in the console, and route changes will become visibly slow.

# What actually is broken?

Short investigation shows, thet the infinite `$digest()` loop is caused by changing value of `changeCounter` inside `$locationWatch` which is a closure inside `$location`. I was suspecting `$location` to be guilty, but actually it's more complicated.

`$locationWatch` calls `$evalAsync`, that according to the docs will swallow all exceptions, and this is exactly what happens. Inside the `$locationWatch`, `$browser.url($location.absUrl(), currentReplace)` would normally raise, but the exception gets swallowed. The url does not actually change, so oldUrl is alway different than current one.

What is wrong with `$browser.url`? Well, it uses a "private" `$sniffer` service to decide if it should use HTML5 history API or oldschool `location.href`. Unfortunately, inside Firefox plugin `$sniffer` reports that history API is available, while actiual calls to `history.pushState` and `history.replaceState` throw exceptions (that are silenced by `$evalAsync`).

So, the `$sniffer` service is to blame, for reporting wrong value for `history`.

# How I fixed it (for now, and maybe for good?)

You can see in the repo I provided, that the fix is a simple check if `$window.XPCNativeWrapper` is defined. If yes, it means we're running inside FF plugin, and should not use the history API.

# Do we want this in angular and where is the pull request?

This patch, while currently resides in separate module, seems fully compatible with Angular, and probably does not break anything. Maybe we should merge it?

The pull request is on it's way, I just need a few spare hours :)

### PR DESCRIPTION
**Pull request by karolmajta**
Request Type: bug

How to reproduce: Described precisely in reported issue #7241

Component(s): misc core

Impact: small

Complexity: small

This issue is related to: 

**Detailed Description:**

`history.pushState` and `history.replaceState` seem broken when
executed in scope of firefox's addon contentscript. This causes angular
to behave unpredictably as described in issue #7241. This commit
adds extra check for presence of `XPCNativeWrapper` object and makes
`$sniffer.history` depend on it too.

**Other Comments:**

Closes #7241

### CODE REVIEW

**Comment by caitp** [comment]
I would be a lot happier to do this if the variable were testing for were vendor-prefixed. It's unlikely, but still technically possible that it could bite someone in the ass. Still, I guess I don't see much of a reason to not merge this.

The only reason I can really think of is, if the fix isn't actually needed anymore. Can someone verify that quickly?

**Comment by karolmajta** [comment]
I've checked and this bug is no longer reproducible.

Tested against:
- angular (1.3.8)
- angular-route (1.3.8)
- firefox (30.0)
- firefox addon-sdk (1.17)

**Comment by caitp** [comment]
okay, shall we close this then?

**Comment by karolmajta** [comment]
I think closing this issue is a reasonable thing to do. Number of affected users is probably close to zero anyway :)

**Comment by caitp** [comment]
Sounds good to me. Please open a new issue if there are future problems

**Pull request closed without merging**
