### PR TITLE
ngTransclude content by default

### PR DESCRIPTION
**Pull request by dmaslov**
Existing content of the element that this directive is placed on will be removed **only** if transcluded content exists. In other case the content will be saved and used as content by default.

It will be useful if you need to use default content in directive's template and replace it **only** in some directive instances.
##### Directive template:

``` html
<button>
    <span ng-transclude>
        <i class="fa fa-paperclip"></i>Add to dashboard
    </span>
  </button>
```
##### Directive instance with modified content:

``` html
<!-- modified button content -->
<pin-chart-button>
    <i class="fa fa-thumb-tack"></i>
</pin-chart-button>
```
##### Which would generate:

``` html
<button>
    <span>
        <i class="fa fa-thumb-tack"></i>
    </span>
  </button>
```
##### Directive instance without modified content:

``` html
<!-- default button content -->
<pin-chart-button></pin-chart-button>
```
##### Which would generate:

``` html
<button>
    <span>
        <i class="fa fa-paperclip"></i>Add to dashboard
    </span>
  </button>
```

### CODE REVIEW

**Comment by dmaslov** [comment]
I signed it!

**Comment by lgalfaso** [comment]
Hi, would it be possible for you to:
[ ] Make it clear what is the use case
[ ] Create the tests that show the new behavior

I am not very happy in changing the existing (already complex) transclude behavior, but with a good reason I can change my mind

**Comment by dmaslov** [comment]
Use case:

Just imagine we have a case when we need to use a majority of identic elements throughout the project, for example buttons with the same text, look and behavior. Also there will be elements with the same behaviour but different look and content (e.g. text).

```javascript
angular.module('transcludeDefaultContentExample', [])
.directive('myButton', function(){
            return {
              restrict: 'E',
              transclude: true,
              scope: true,
              template: '<button style="cursor: pointer;">' +
                          '<ng-transclude></ng-transclude>'
                        '</button>'
            };
        });
```

Now, having the current ```ngTransclude``` implementation, we need to duplicate the content of the ```ng-transclude``` element. And if there are many of such elements, we need to copy and paste the same content multiple times. 

For example:

```html
<my-button><b style="color: red;">Warning</b></my-button>
<my-button><b style="color: red;">Warning</b></my-button>
<my-button><b style="color: red;">Warning</b></my-button>
<my-button><b style="color: red;">Warning</b></my-button>
```

And only in case of elements with the different look and content we will type in another content. 

```html
<my-button><b style="color: green;">Ok</b></my-button>
```

The update I offer will let us avoid this multiple and useless copying & pasting. We will be able to set the ‘default’ look just once (as content of ng-transclude element) and change it only for the element that needs to look different. 

```javascript
angular.module('transcludeDefaultContentExample', [])
.directive('myButton', function(){
            return {
              restrict: 'E',
              transclude: true,
              scope: true,
              template: '<button style="cursor: pointer;">' +
                          '<ng-transclude>' +
                            '<b style="color: red;">Warning</b>' +
                          '</ng-transclude>' +
                        '</button>'
            };
        });
```

```html
<my-button></my-button>
<my-button></my-button>
<my-button></my-button>
<my-button></my-button>
<my-button><b style="color: green;">Ok</b></my-button>
```

**Comment by dmaslov** [comment]
Hi, @lgalfaso 

- [x] Make it clear what is the use case
- [x] Create the tests that show the new behavior
- [x] Make the documentation changes of the feature

**Comment by dmaslov** [comment]
related issue #7195

**Comment by dmaslov** [comment]
Hey!
@Narretz is something wrong with my PR? Or it's just bad idea to do what i did? :)

**Comment by PavloKovalov** [comment]
@dmaslov @Narretz sound reasonable :+1:

**Comment by drcool** [comment]
I like this feature a lot.  You've got my vote!

**Comment by Narretz** [comment]
It does sound useful. Features for 1.5.x are closed, but we can put it on the table for 1.6 (it needs a rebase, though).

**Comment by dmaslov** [comment]
@Narretz, done.

**Comment by pauljoey** [comment]
+1

**Pull request closed without merging**
