### PR TITLE
fix($templateRequest): propagate HTTP status on failed requests

### LINKED ISSUE #10514: $templateCache / $compile loses error context when HTTP request for template fails
The `$templateCache` service throws an exception if the HTTP request to fetch the template fails, however the exception message contains no useful context other than the fact that the request failed.

The exception should include the error code and other context.

https://github.com/angular/angular.js/blob/g3_v1_3/src/ng/templateRequest.js#L52

### PR DESCRIPTION
**Pull request by pkozlowski-opensource**
Fixes #10514

### CODE REVIEW

**Comment by caitp** [comment]
LGTM (mobile, might want another look)

**Comment by pkozlowski-opensource** [comment]
@caitp do you want to have another look at it or is it good to land?

**Comment by pkozlowski-opensource** [comment]
@caitp / @petebacondarwin / @lgalfaso (or anyone else!) - would you guys mind reviewing this one - it is pretty minimal

**Comment by petebacondarwin** [comment]
LGTM

**Comment by petebacondarwin** [comment]
LGTM

**Pull request closed without merging**
