### PR TITLE
docs($resource): Fix the @-prefixed parameter examples to match the p…

### PR DESCRIPTION
**Pull request by hawicz**
**What kind of change does this PR introduce? docs update

**What is the current behavior? (You can also link to an open issue here)**
n/a

**What is the new behavior (if this is a feature change)?**
n/a

**Does this PR introduce a breaking change?**
no

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Other information**:

…roperty names of the corresponding data objects.

### CODE REVIEW

**Comment by petebacondarwin** [comment]
I'm pretty sure we have had this discussion before, similar to #11544.
The `@id` refers to the property on the resource object, not the param name in the URL.

>If the parameter value is prefixed with @ then the value for that parameter will be extracted from the corresponding property on the data object (provided when calling an action method). For example, if the defaultParam object is {someParam: '@someProp'} then the value of someParam will be data.someProp.

**Comment by hawicz** [comment]
yes, and for some of the examples on the page @id is correct, but the ones that have a userId param also refer to an object whose property is called userId, not id.

**Comment by hawicz** [comment]
Take the first mention of userId on that page, in the "Returns" section:

    var User = $resource('/user/:userId', {userId:'@id'});
    var user = User.get({userId:123}, function() {
      user.abc = true;
      user.$save();
    });

how would the value 123 from the object passed to get() end up mapped into "/user/123" here?

**Comment by petebacondarwin** [comment]
In this case the object that is retrieved from the REST service has a property `user.id`.
Now, when we call save, the URL that is used in the POST request is `/user/123` because the `user.id == 123`.
You could test this by changing the `user.id` to something else and looking at what URL is requested in the POST when `$save()` is called

**Comment by gkalpak** [comment]
I think the confusion stems from the fact that non-get requests (e.g. `User.save({...})`) receive a `data` object (from which the parameters can be extracted using the `{userId: '@id'}` mapping), while get requests (e.g. `User.get({...})`) can receive a `params` object (which has to reference params usign their actual name (i.e. `userId`).

A similar explanation can be found [here][1] as well.

[1]: https://github.com/angular/angular.js/pull/9243/files#r17963997

**Comment by hawicz** [comment]
So, then perhaps the description of the @-parameters in the section about paramDefaults should say something like "...(provided when calling an action method, except for get() which uses the attributes in its passed object directly)..." ?

**Comment by petebacondarwin** [comment]
We do need to improve the docs on this as it keeps coming up.

**Comment by gkalpak** [comment]
I clarified this a bit in 7ab00f4.

**Comment by petebacondarwin** [comment]
Thanks @gkalpak

**Pull request closed without merging**
